// GM Battle Manager — compendium of SRD monsters for the DM library.
// Each entry maps onto the tracker's token model (see src/local.js saneToken):
// abilities auto-derive saves/checks, skillProf levels are 0.5/1/2, imm/res/vuln
// are damage types, condImm are condition names, dmg is a dice formula for the
// Attack action's damage roll. Values approximate the D&D 5e SRD (CR/XP, HP,
// AC, attack bonus, damage). Tap a card in the Compendium to drop the monster
// into the tracker with its full stat block.

export const COMPENDIUM = [
  { id: "goblin", name: "Goblin", type: "humanoid", cr: "1/4", xp: 50,
    color: "#5a9e3f", img: "https://user.uploads.dev/file/aaa15886dba405352f6e5d2ce0c9970f.jpg",
    hp: 7, ac: 15, atk: 4, dmg: "1d6+2", hd: "2d6",
    abilities: { str: 8, dex: 14, con: 10, int: 10, wis: 8, cha: 8 },
    saveProf: [], profBonus: 2, skillProf: { stealth: 2 },
    imm: [], res: [], vuln: [], condImm: [], langs: "Common, Goblin",
    note: "Nimble Escape — Disengage or Hide as a bonus action. Stealth +6." },

  { id: "kobold", name: "Kobold", type: "humanoid", cr: "1/8", xp: 25,
    color: "#c99b3f", img: "https://user.uploads.dev/file/7d18ad824e3f650682dd120ee2b6991e.jpg",
    hp: 5, ac: 12, atk: 4, dmg: "1d4+2", hd: "2d6-2",
    abilities: { str: 7, dex: 15, con: 9, int: 8, wis: 7, cha: 8 },
    saveProf: [], profBonus: 2, skillProf: { stealth: 1 },
    imm: [], res: [], vuln: [], condImm: [], langs: "Common, Draconic",
    note: "Pack Tactics — advantage when an ally is adjacent. Sunlight Sensitivity." },

  { id: "orc", name: "Orc", type: "humanoid", cr: "1/2", xp: 100,
    color: "#3f7a5a", img: "https://user.uploads.dev/file/a31b50e7a74974f135bff880d306a04c.jpg",
    hp: 15, ac: 13, atk: 5, dmg: "1d12+3", hd: "2d8+6",
    abilities: { str: 16, dex: 12, con: 16, int: 7, wis: 11, cha: 10 },
    saveProf: [], profBonus: 2, skillProf: { intimidation: 1 },
    imm: [], res: [], vuln: [], condImm: [], langs: "Common, Orc",
    note: "Aggressive — Dash toward an enemy as a bonus action. Greataxe." },

  { id: "hobgoblin", name: "Hobgoblin", type: "humanoid", cr: "1/2", xp: 100,
    color: "#a34f2f", img: "https://user.uploads.dev/file/4586eca36153546b87e7ad03bb8b08ad.jpg",
    hp: 11, ac: 18, atk: 3, dmg: "1d8+1", hd: "2d8+2",
    abilities: { str: 13, dex: 12, con: 12, int: 10, wis: 10, cha: 9 },
    saveProf: [], profBonus: 2, skillProf: {},
    imm: [], res: [], vuln: [], condImm: [], langs: "Common, Goblin",
    note: "Martial Advantage — +2d6 damage when an ally is adjacent. Longsword, chainmail + shield." },

  { id: "bugbear", name: "Bugbear", type: "humanoid", cr: "1", xp: 200,
    color: "#8a5a2b", hp: 27, ac: 16, atk: 4, dmg: "2d8+2", hd: "5d8+5",
    abilities: { str: 15, dex: 14, con: 13, int: 8, wis: 11, cha: 9 },
    saveProf: [], profBonus: 2, skillProf: { stealth: 2 },
    imm: [], res: [], vuln: [], condImm: [], langs: "Common, Goblin",
    note: "Surprise Attack — +2d6 on first hit vs a surprised target. Long arms. Morningstar." },

  { id: "cultist", name: "Cultist", type: "humanoid", cr: "1/8", xp: 25,
    color: "#6f4f9f", img: "https://user.uploads.dev/file/815dd5b08c7de7a6d6ec4b5e840921ec.jpg",
    hp: 9, ac: 12, atk: 3, dmg: "1d6+1", hd: "2d8",
    abilities: { str: 11, dex: 12, con: 10, int: 10, wis: 11, cha: 10 },
    saveProf: [], profBonus: 2, skillProf: { deception: 1, religion: 1 },
    imm: [], res: [], vuln: [], condImm: [], langs: "Common",
    note: "Dark Devotion — advantage on saves vs charm and fright. Scimitar." },

  { id: "bandit", name: "Bandit", type: "humanoid", cr: "1/8", xp: 25,
    color: "#8f5a3a", img: "https://user.uploads.dev/file/275b82e106747916dcd01d1affe6f079.jpg",
    hp: 11, ac: 12, atk: 3, dmg: "1d6+1", hd: "2d8+2",
    abilities: { str: 11, dex: 12, con: 12, int: 10, wis: 10, cha: 10 },
    saveProf: [], profBonus: 2, skillProf: {},
    imm: [], res: [], vuln: [], condImm: [], langs: "Common",
    note: "Scimitar. Carries a crossbow (1d8 piercing)." },

  { id: "thug", name: "Thug", type: "humanoid", cr: "1/2", xp: 100,
    color: "#7a4f4f", hp: 32, ac: 11, atk: 4, dmg: "1d6+2", hd: "5d8+10",
    abilities: { str: 15, dex: 11, con: 14, int: 10, wis: 10, cha: 11 },
    saveProf: [], profBonus: 2, skillProf: { intimidation: 1 },
    imm: [], res: [], vuln: [], condImm: [], langs: "Common",
    note: "Pack Tactics — advantage when an ally is adjacent. Mace." },

  { id: "veteran", name: "Veteran", type: "humanoid", cr: "3", xp: 700,
    color: "#a06a4a", hp: 58, ac: 17, atk: 5, dmg: "1d8+3", hd: "9d8+18",
    abilities: { str: 16, dex: 13, con: 14, int: 10, wis: 11, cha: 10 },
    saveProf: [], profBonus: 2, skillProf: { athletics: 1, perception: 1 },
    imm: [], res: [], vuln: [], condImm: [], langs: "Common",
    note: "Multiattack — two longsword attacks (or longsword + shortsword)." },

  { id: "knight", name: "Knight", type: "humanoid", cr: "3", xp: 700,
    color: "#9a7f2f", hp: 52, ac: 18, atk: 5, dmg: "2d6+3", hd: "8d8+16",
    abilities: { str: 16, dex: 11, con: 14, int: 11, wis: 11, cha: 15 },
    saveProf: ["str", "con"], profBonus: 2, skillProf: { athletics: 1 },
    imm: [], res: [], vuln: [], condImm: [], langs: "Common",
    note: "Brave — advantage vs fright. Leadership — bonus to allies' attacks. Greatsword." },

  { id: "mage", name: "Mage", type: "humanoid", cr: "6", xp: 2300,
    color: "#6a5ad0", hp: 40, ac: 12, atk: 5, dmg: "1d10", hd: "9d8",
    abilities: { str: 9, dex: 14, con: 11, int: 17, wis: 12, cha: 11 },
    saveProf: ["int", "wis"], profBonus: 3, skillProf: { arcana: 1, history: 1 },
    imm: [], res: [], vuln: [], condImm: [], langs: "Common + 3 languages",
    note: "Spellcaster (level 9). Fire bolt +5, 1d10. Casts shield, misty step, fireball, counterspell, fly, haste, lightning bolt." },

  { id: "priest", name: "Priest", type: "humanoid", cr: "2", xp: 450,
    color: "#c9a84f", hp: 27, ac: 13, atk: 2, dmg: "1d6", hd: "5d8+5",
    abilities: { str: 12, dex: 10, con: 12, int: 13, wis: 14, cha: 11 },
    saveProf: ["wis"], profBonus: 2, skillProf: { medicine: 1, religion: 1 },
    imm: [], res: [], vuln: [], condImm: [], langs: "Common",
    note: "Divine Eminence — +10 radiant damage once (bonus action). Spellcaster — bless, cure wounds, spirit guardians." },

  { id: "giant-rat", name: "Giant Rat", type: "beast", cr: "1/8", xp: 25,
    color: "#8a8a8a", img: "https://user.uploads.dev/file/720035b8cea6a4057e4ccbd30d25a6f9.jpg",
    hp: 7, ac: 12, atk: 4, dmg: "1d4+2", hd: "2d6",
    abilities: { str: 7, dex: 15, con: 11, int: 2, wis: 10, cha: 4 },
    saveProf: [], profBonus: 2, skillProf: {},
    imm: [], res: [], vuln: [], condImm: [], langs: "",
    note: "Keen Smell — advantage on smell Perception. Pack Tactics." },

  { id: "wolf", name: "Wolf", type: "beast", cr: "1/4", xp: 50,
    color: "#7a7d8f", img: "https://user.uploads.dev/file/961814cb1fb9ff04f464e24ec3baec15.jpg",
    hp: 11, ac: 13, atk: 4, dmg: "2d4+2", hd: "2d8+2",
    abilities: { str: 12, dex: 15, con: 12, int: 3, wis: 12, cha: 6 },
    saveProf: [], profBonus: 2, skillProf: { perception: 1, stealth: 1 },
    imm: [], res: [], vuln: [], condImm: [], langs: "",
    note: "Keen Hearing/Smell. Pack Tactics. Bite knocks targets prone (DC 11)." },

  { id: "dire-wolf", name: "Dire Wolf", type: "beast", cr: "1", xp: 200,
    color: "#5a6a8f", hp: 37, ac: 14, atk: 5, dmg: "2d6+3", hd: "5d10+10",
    abilities: { str: 17, dex: 15, con: 15, int: 3, wis: 12, cha: 7 },
    saveProf: [], profBonus: 2, skillProf: { perception: 1, stealth: 1 },
    imm: [], res: [], vuln: [], condImm: [], langs: "",
    note: "Keen Hearing/Smell. Pack Tactics. Bite knocks targets prone (DC 13)." },

  { id: "giant-spider", name: "Giant Spider", type: "beast", cr: "1", xp: 200,
    color: "#4f8a5f", hp: 26, ac: 14, atk: 5, dmg: "1d8+3", hd: "4d10+4",
    abilities: { str: 14, dex: 16, con: 12, int: 2, wis: 11, cha: 4 },
    saveProf: [], profBonus: 2, skillProf: { stealth: 1 },
    imm: [], res: [], vuln: [], condImm: [], langs: "",
    note: "Web Sense / Web Walker. Bite: 1d8+3 piercing + 2d6 poison (CON 11 halves)." },

  { id: "giant-scorpion", name: "Giant Scorpion", type: "beast", cr: "3", xp: 700,
    color: "#8f8a4f", hp: 52, ac: 15, atk: 4, dmg: "1d10+2", hd: "7d10+14",
    abilities: { str: 15, dex: 13, con: 15, int: 1, wis: 9, cha: 3 },
    saveProf: [], profBonus: 2, skillProf: {},
    imm: [], res: [], vuln: [], condImm: [], langs: "",
    note: "Multiattack — two claws (1d8+2) then a sting (1d10+2 + 4d10 poison, CON 12 halves)." },

  { id: "owlbear", name: "Owlbear", type: "monstrosity", cr: "3", xp: 700,
    color: "#9a6a4a", hp: 59, ac: 13, atk: 7, dmg: "1d10+5", hd: "7d10+21",
    abilities: { str: 19, dex: 12, con: 17, int: 3, wis: 12, cha: 7 },
    saveProf: [], profBonus: 2, skillProf: { perception: 1 },
    imm: [], res: [], vuln: [], condImm: [], langs: "",
    note: "Keen Sight/Smell. Multiattack — beak (1d10+5) and claws (2d6+5)." },

  { id: "troll", name: "Troll", type: "giant", cr: "5", xp: 1800,
    color: "#6f8a3f", hp: 84, ac: 15, atk: 7, dmg: "2d6+4", hd: "8d10+40",
    abilities: { str: 18, dex: 13, con: 20, int: 7, wis: 9, cha: 7 },
    saveProf: [], profBonus: 3, skillProf: { perception: 1 },
    imm: [], res: [], vuln: [], condImm: [], langs: "",
    note: "Regeneration — regains 10 HP at the start of its turn unless it took fire or acid damage. Keen Smell. Multiattack (bite + 2 claws)." },

  { id: "ogre", name: "Ogre", type: "giant", cr: "2", xp: 450,
    color: "#6a8f7a", hp: 59, ac: 11, atk: 6, dmg: "2d8+4", hd: "7d10+21",
    abilities: { str: 19, dex: 8, con: 16, int: 5, wis: 7, cha: 7 },
    saveProf: [], profBonus: 2, skillProf: {},
    imm: [], res: [], vuln: [], condImm: [], langs: "Common, Giant",
    note: "Greatclub 2d8+4. Javelin (thrown) 1d6+4." },

  { id: "skeleton", name: "Skeleton", type: "undead", cr: "1/4", xp: 50,
    color: "#cfcfcf", img: "https://user.uploads.dev/file/80afb8c2380db568ef8c42f79a6c88e1.jpg",
    hp: 13, ac: 13, atk: 4, dmg: "1d6+2", hd: "2d8+4",
    abilities: { str: 10, dex: 14, con: 15, int: 6, wis: 8, cha: 5 },
    saveProf: [], profBonus: 2, skillProf: {},
    imm: ["poison"], res: [], vuln: ["bludgeoning"], condImm: ["exhaustion", "poisoned"], langs: "",
    note: "Darkvision. Shortsword 1d6+2. Immune to poison; vulnerable to bludgeoning." },

  { id: "zombie", name: "Zombie", type: "undead", cr: "1/4", xp: 50,
    color: "#7a9e5f", img: "https://user.uploads.dev/file/12666abd324f3df13d1d203e3a6f99c0.jpg",
    hp: 22, ac: 8, atk: 3, dmg: "1d6+1", hd: "3d8+9",
    abilities: { str: 13, dex: 6, con: 16, int: 3, wis: 6, cha: 5 },
    saveProf: [], profBonus: 2, skillProf: {},
    imm: ["poison"], res: [], vuln: [], condImm: ["poisoned"], langs: "",
    note: "Undead Fortitude — if damage leaves it at 0 HP, DC 5+damage CON save instead drops to 1 HP." },

  { id: "ghoul", name: "Ghoul", type: "undead", cr: "1", xp: 200,
    color: "#7a6a5a", hp: 22, ac: 12, atk: 4, dmg: "2d4+2", hd: "5d8",
    abilities: { str: 13, dex: 15, con: 10, int: 7, wis: 10, cha: 6 },
    saveProf: [], profBonus: 2, skillProf: {},
    imm: ["poison"], res: [], vuln: [], condImm: ["charmed", "exhaustion", "poisoned"], langs: "",
    note: "Bite 1d6+2 / claws 2d4+2. Paralyzing Touch — CON 11 save or paralyzed for 1 minute." },

  { id: "ghast", name: "Ghast", type: "undead", cr: "2", xp: 450,
    color: "#8f7a6a", hp: 36, ac: 13, atk: 5, dmg: "2d6+3", hd: "8d8",
    abilities: { str: 16, dex: 17, con: 10, int: 11, wis: 10, cha: 8 },
    saveProf: [], profBonus: 2, skillProf: {},
    imm: ["poison"], res: [], vuln: [], condImm: ["charmed", "exhaustion", "poisoned"], langs: "Common",
    note: "Stench — creatures within 5 ft make DC 10 CON save or are poisoned. Paralyzing Touch (DC 11)." },

  { id: "wight", name: "Wight", type: "undead", cr: "3", xp: 700,
    color: "#5f5f7a", hp: 45, ac: 14, atk: 4, dmg: "1d8+2+2d6", hd: "6d8+18",
    abilities: { str: 15, dex: 14, con: 16, int: 10, wis: 13, cha: 15 },
    saveProf: [], profBonus: 2, skillProf: { perception: 1, stealth: 1 },
    imm: ["poison"], res: [], vuln: [], condImm: ["exhaustion", "poisoned"], langs: "Common + languages it knew",
    note: "Longsword 1d8+2 slashing + 2d6 necrotic; Life Drain (CON 13) drops max HP. Sunlight Sensitivity." },

  { id: "specter", name: "Specter", type: "undead", cr: "1", xp: 200,
    color: "#9a9ad0", hp: 22, ac: 12, atk: 4, dmg: "1d8+2", hd: "5d8",
    abilities: { str: 1, dex: 14, con: 11, int: 10, wis: 10, cha: 11 },
    saveProf: [], profBonus: 2, skillProf: {},
    imm: ["poison"], res: ["cold", "fire", "lightning", "thunder", "bludgeoning", "piercing", "slashing"], vuln: [],
    condImm: ["charmed", "exhaustion", "grappled", "paralyzed", "petrified", "poisoned", "prone", "restrained", "stunned", "unconscious"],
    langs: "",
    note: "Life Drain 1d8+2 necrotic — CON 10 save or max HP reduced. Incorporeal (resistances vs nonmagical)." },

  { id: "young-green-dragon", name: "Young Green Dragon", type: "dragon", cr: "8", xp: 3900,
    color: "#4f8a5f", hp: 136, ac: 18, atk: 7, dmg: "1d10+4+2d6", hd: "16d10+48",
    abilities: { str: 19, dex: 12, con: 17, int: 16, wis: 13, cha: 15 },
    saveProf: ["dex", "con", "wis", "cha"], profBonus: 3,
    skillProf: { deception: 1, insight: 1, perception: 1, stealth: 1 },
    imm: ["poison"], res: [], vuln: [], condImm: ["poisoned"], langs: "Common, Draconic",
    note: "Bite 1d10+4 piercing + 2d6 poison. Multiattack (bite + 2 claws 2d6+4). Poison Breath — 12d6 poison, DC 14 CON half." }
];
