import { designTokens, resolveVars, themeField } from "./tokens.js";

function slugify(name) {
  return String(name || "theme").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 40) || "theme";
}

function scaffoldCss(card, tokens) {
  const lines = [];
  for (const link of tokens.fontLinks) {
    if (/fonts\.googleapis/i.test(link) || /\.css($|[?#])/i.test(link)) lines.push("@import url('" + link + "');");
  }
  const vars = (card && card.cssVars) || {};
  const vkeys = Object.keys(vars);
  if (vkeys.length) {
    lines.push(":root {");
    for (const k of vkeys.slice(0, 40)) lines.push("  " + k + ": " + vars[k] + ";");
    lines.push("}");
  }
  const derived = [];
  if (tokens.fontFamily) derived.push("  --theme-font: " + tokens.fontFamily + ";");
  if (tokens.radius) derived.push("  --theme-radius: " + tokens.radius + ";");
  if (tokens.shadow) derived.push("  --theme-shadow: " + tokens.shadow + ";");
  if (tokens.background) derived.push("  --theme-bg: " + tokens.background + ";");
  if (tokens.textColor) derived.push("  --theme-text: " + tokens.textColor + ";");
  if (tokens.colors[0]) derived.push("  --theme-accent: " + tokens.colors[0].value + ";");
  if (derived.length) {
    lines.push(":root {");
    lines.push(...derived);
    lines.push("}");
  }
  const bg = tokens.background ? "var(--theme-bg)" : "#0e1016";
  const fg = tokens.textColor ? "var(--theme-text)" : "#e8eaf0";
  const font = tokens.fontFamily ? "var(--theme-font)" : "system-ui, sans-serif";
  const radius = tokens.radius ? "var(--theme-radius)" : "12px";
  lines.push(
    "",
    "body {",
    "  margin: 0;",
    "  min-height: 100vh;",
    "  display: flex;",
    "  align-items: center;",
    "  justify-content: center;",
    "  background: " + bg + ";",
    "  color: " + fg + ";",
    "  font-family: " + font + ";",
    "  text-align: center;",
    "}",
    "",
    ".app { width: min(640px, 92vw); padding: 24px; }",
    ".app-head h1 { margin: 0 0 6px; font-size: clamp(22px, 4vw, 34px); }",
    ".app-head .tagline { margin: 0 0 20px; opacity: 0.75; }",
    ".card {",
    "  border-radius: " + radius + ";",
    "  padding: 26px;",
    "  background: color-mix(in srgb, " + fg + " 6%, transparent);",
    "  border: 1px solid color-mix(in srgb, " + fg + " 14%, transparent);"
  );
  if (tokens.shadow) lines.push("  box-shadow: var(--theme-shadow);");
  lines.push(
    "}",
    ".out { font-size: clamp(18px, 3vw, 24px); line-height: 1.5; min-height: 3em; }",
    ".btn {",
    "  margin-top: 18px;",
    "  border: 0;",
    "  border-radius: calc(" + radius + " - 4px);",
    "  padding: 11px 22px;",
    "  font: inherit;",
    "  font-weight: 600;",
    "  cursor: pointer;",
    "  color: " + bg + ";",
    "  background: var(--theme-accent, " + fg + ");",
    "}",
    ".btn:hover { filter: brightness(1.08); }"
  );
  return lines.join("\n");
}

export function starterScaffold(card) {
  const c = card || {};
  const tokens = designTokens(c);
  const slug = slugify(c.name || c.title);
  const title = c.title || c.name || "Themed starter";
  const tags = (Array.isArray(c.tags) ? c.tags : []).slice(0, 8).join(", ");
  const genre = themeField(c.theme, "GENRE");
  const mood = themeField(c.theme, "MOOD/VIBE", "MOOD", "VIBE");
  const aesthetic = themeField(c.theme, "VISUAL AESTHETIC");
  const oneLine = themeField(c.theme, "THEME IN ONE LINE") || title;

  const html = [
    "<!-- index.html — the contents of the <body> for a new Perchance generator. -->",
    "<!-- Theme: " + title + " (captured from perchance.org/" + (c.name || "") + ") -->",
    "",
    "<style>",
    scaffoldCss(c, tokens),
    "</style>",
    "",
    '<div class="app">',
    '  <header class="app-head">',
    "    <h1>[title]</h1>",
    '    <p class="tagline">[tagline]</p>',
    "  </header>",
    '  <main class="card">',
    '    <div id="out" class="out">[sentence]</div>',
    '    <button id="rollBtn" class="btn">Roll again</button>',
    "  </main>",
    "</div>",
    "",
    "<script>",
    '  var out = document.getElementById("out");',
    '  document.getElementById("rollBtn").addEventListener("click", function () {',
    '    out.textContent = "[sentence]".evaluateItem;',
    "  });",
    "</script>"
  ].join("\n");

  const pjs = [
    "$meta",
    "  title = " + title,
    "  description = Themed starter generated by Extrax from perchance.org/" + (c.name || "a generator") + ".",
    (tags ? "  tags = " + tags : "  tags = theme, starter"),
    "",
    "title = " + title,
    "",
    "tagline",
    "  a themed experiment" + (genre ? ", " + genre.toLowerCase() : ""),
    "  " + (oneLine.replace(/[`${}]/g, "").slice(0, 120) || "built to match a captured look"),
    "",
    "opener",
    "  Welcome, traveller.",
    "  Greetings, friend.",
    "  Well met.",
    "",
    "subject",
    "  the wandering star",
    "  a quiet harbour",
    "  the old lighthouse",
    "  a field of lanterns",
    "",
    "sentence",
    "  [opener] [subject] awaits."
  ].join("\n");

  const css = scaffoldCss(c, tokens);

  const readme = [
    "# " + title + " — themed starter",
    "",
    "Generated by **Extrax** from `perchance.org/" + (c.name || "") + "`.",
    "",
    "- **Mood:** " + (mood || "(not captured)"),
    "- **Aesthetic:** " + (aesthetic || "(not captured)"),
    "",
    "## What's here",
    "",
    "- `index.html` — paste into your new generator's **index.html** (contents of the body).",
    "- `main.pjs` — paste into your generator's **main.pjs** (metadata + demo lists).",
    "- `theme.css` — the captured theme on its own, if you just want the styling.",
    "",
    "## Use it",
    "",
    "1. Create a new generator on Perchance.",
    "2. Replace its `index.html` with the file here.",
    "3. Replace its `main.pjs` with the file here.",
    "4. Save — the page renders `[sentence]`, and the button rolls a new one.",
    "",
    "The lists in `main.pjs` (`opener`, `subject`, `sentence`) are only there to demonstrate the look. Swap them for your own content.",
    ""
  ].join("\n");

  return {
    slug,
    title,
    css,
    files: [
      { name: "index.html", text: html, mime: "text/html;charset=utf-8" },
      { name: "main.pjs", text: pjs, mime: "text/plain;charset=utf-8" },
      { name: "theme.css", text: css, mime: "text/css;charset=utf-8" },
      { name: "README.md", text: readme, mime: "text/markdown;charset=utf-8" }
    ]
  };
}

export function scaffoldZipName(card) {
  return slugify((card && (card.name || card.title)) || "theme") + "-starter.zip";
}
