/* ════════════════════════════════════════════════════════════════
   D&D CHARACTER FORGE — curated spellbook
   A compact, commonly-used subset of 5e spells. Fields:
   lvl level, s school, t casting time, r range, c components,
   d duration, x "c" = concentration, desc one-line summary.
   ──────────────────────────────────────────────────────────── */
window.SPELLBOOK = (function () {
  "use strict";

  const S = {
    abj: "Abjuration", con: "Conjuration", div: "Divination", enc: "Enchantment",
    evo: "Evocation", ill: "Illusion", nec: "Necromancy", tra: "Transmutation",
  };

  const SP = {
    /* ── cantrips ── */
    "acid splash": { lvl: 0, s: "con", t: "1 action", r: "60 ft", c: "V, S", d: "Instant", desc: "Choose two creatures within 5 ft of each other: 1d6 acid damage." },
    "blade ward": { lvl: 0, s: "abj", t: "1 action", r: "Self", c: "V, S", d: "1 round", desc: "Resistance to bludgeoning, piercing, and slashing damage." },
    "booming blade": { lvl: 0, s: "evo", t: "1 action", r: "Self (5 ft)", c: "V, M", d: "1 round", desc: "Melee attack with weapon + thunder damage; moving creatures take extra thunder." },
    "chill touch": { lvl: 0, s: "nec", t: "1 action", r: "120 ft", c: "V, S", d: "1 round", desc: "1d8 necrotic; can't regain HP until next turn." },
    "dancing lights": { lvl: 0, s: "evo", t: "1 action", r: "120 ft", c: "V, S, M", d: "Conc, up to 1 min", x: "c", desc: "Create four lights that shed dim light." },
    "eldritch blast": { lvl: 0, s: "evo", t: "1 action", r: "120 ft", c: "V, S", d: "Instant", desc: "1d10 force; two beams at 5th, three at 11th, four at 17th. Warlock signature." },
    "fire bolt": { lvl: 0, s: "evo", t: "1 action", r: "120 ft", c: "V, S", d: "Instant", desc: "1d10 fire. Scales to 2d10/3d10/4d10 at 5/11/17." },
    "friends": { lvl: 0, s: "enc", t: "1 action", r: "Self", c: "S, M", d: "Conc, up to 1 min", x: "c", desc: "Advantage on Charisma checks against one creature; it may become hostile." },
    "guidance": { lvl: 0, s: "div", t: "1 action", r: "Touch", c: "V, S", d: "Conc, up to 1 min", x: "c", desc: "Target adds 1d4 to one ability check." },
    "light": { lvl: 0, s: "evo", t: "1 action", r: "Touch", c: "V, M", d: "1 hour", desc: "Touch an object to make it shed bright light for 60 ft." },
    "mage hand": { lvl: 0, s: "con", t: "1 action", r: "30 ft", c: "V, S", d: "1 min", desc: "A spectral hand manipulates objects within 30 ft." },
    "mage armor": { lvl: 0, s: "abj", t: "1 action", r: "Touch", c: "V, S, M", d: "8 hours", desc: "Target's AC becomes 13 + Dexterity modifier. (Cantrip in 2024)" },
    "mending": { lvl: 0, s: "tra", t: "1 min", r: "Touch", c: "V, S, M", d: "Instant", desc: "Repair a single break or tear in an object." },
    "message": { lvl: 0, s: "tra", t: "1 action", r: "120 ft", c: "V, S, M", d: "Instant", desc: "Whisper a message to a creature that can hear it." },
    "minor illusion": { lvl: 0, s: "ill", t: "1 action", r: "30 ft", c: "S, M", d: "1 min", desc: "Create a sound or image illusion." },
    "poison spray": { lvl: 0, s: "con", t: "1 action", r: "10 ft", c: "V, S", d: "Instant", desc: "1d12 poison damage, Con save for half." },
    "prestidigitation": { lvl: 0, s: "tra", t: "1 action", r: "10 ft", c: "V, S", d: "Up to 1 hour", desc: "Tiny magical effect: chill, warm, flavor, soil, clean." },
    "ray of frost": { lvl: 0, s: "evo", t: "1 action", r: "60 ft", c: "V, S", d: "Instant", desc: "1d8 cold damage and speed reduced by 10 ft." },
    "sacred flame": { lvl: 0, s: "evo", t: "1 action", r: "60 ft", c: "V, S", d: "Instant", desc: "Radiant damage, Dex save; ignores cover." },
    "shillelagh": { lvl: 0, s: "tra", t: "bonus", r: "Touch", c: "V, S, M", d: "1 min", desc: "Quarterstaff or club uses spellcasting modifier for attack/damage (d8)." },
    "shocking grasp": { lvl: 0, s: "evo", t: "1 action", r: "Touch", c: "V, S", d: "Instant", desc: "1d8 lightning; target can't take reactions." },
    "thorn whip": { lvl: 0, s: "tra", t: "1 action", r: "30 ft", c: "V, S, M", d: "Instant", desc: "Melee spell attack; pull target 10 ft; 1d6 piercing." },
    "vicious mockery": { lvl: 0, s: "enc", t: "1 action", r: "60 ft", c: "V", d: "Instant", desc: "Wis save or 1d4 psychic and disadvantage on next attack." },
    "produce flame": { lvl: 0, s: "con", t: "1 action", r: "Self", c: "V, S", d: "10 min", desc: "Shed light or hurl 1d8 fire." },
    "resistance": { lvl: 0, s: "abj", t: "1 action", r: "Touch", c: "V, S, M", d: "Conc, up to 1 min", x: "c", desc: "Target adds 1d4 to one saving throw." },
    "spare the dying": { lvl: 0, s: "nec", t: "1 action", r: "Touch", c: "V, S", d: "Instant", desc: "Stabilize a dying creature at 0 HP." },
    "thaumaturgy": { lvl: 0, s: "tra", t: "1 action", r: "30 ft", c: "V", d: "Up to 1 min", desc: "Manifest a minor wonder: voice boom, flames, doors, ground tremor." },
    "true strike": { lvl: 0, s: "div", t: "1 action", r: "Self", c: "S", d: "Conc, up to 1 round", x: "c", desc: "Advantage on your next attack roll." },
    "word of radiance": { lvl: 0, s: "evo", t: "1 action", r: "5 ft", c: "V, M", d: "Instant", desc: "Radiant damage to nearby enemies, Con save for half." },

    /* ── level 1 ── */
    "absorb elements": { lvl: 1, s: "abj", t: "reaction", r: "Self", c: "S", d: "1 round", desc: "Resistance to one damage type and extra damage on next hit." },
    "alarm": { lvl: 1, s: "abj", t: "1 min (R)", r: "30 ft", c: "V, S, M", d: "8 hours", desc: "Ward an area; mental or audible alarm when intruders cross." },
    "arms of hadar": { lvl: 1, s: "con", t: "1 action", r: "Self (10 ft)", c: "V, S", d: "Instant", desc: "Necrotic damage to nearby creatures; can't take reactions." },
    "bane": { lvl: 1, s: "enc", t: "1 action", r: "30 ft", c: "V, S, M", d: "Conc, up to 1 min", x: "c", desc: "Three targets subtract 1d4 from attacks and saves." },
    "bless": { lvl: 1, s: "enc", t: "1 action", r: "30 ft", c: "V, S, M", d: "Conc, up to 1 min", x: "c", desc: "Three allies add 1d4 to attacks and saves." },
    "burning hands": { lvl: 1, s: "evo", t: "1 action", r: "Self (15 ft cone)", c: "V, S", d: "Instant", desc: "3d6 fire in a cone, Dex save for half." },
    "charm person": { lvl: 1, s: "enc", t: "1 action", r: "30 ft", c: "V, S", d: "1 hour", desc: "Wis save or target regards you as a friend." },
    "chromatic orb": { lvl: 1, s: "evo", t: "1 action", r: "90 ft", c: "V, S, M", d: "Instant", desc: "3d8 damage of a chosen element, ranged spell attack." },
    "color spray": { lvl: 1, s: "ill", t: "1 action", r: "Self (15 ft cone)", c: "V, S, M", d: "1 round", desc: "Blind creatures with up to 6d10 total HP." },
    "command": { lvl: 1, s: "enc", t: "1 action", r: "60 ft", c: "V", d: "1 round", desc: "Wis save or obey a one-word command: flee, halt, kneel..." },
    "comprehend languages": { lvl: 1, s: "div", t: "1 action (R)", r: "Self", c: "V, S, M", d: "1 hour", desc: "Understand all spoken and written languages." },
    "cure wounds": { lvl: 1, s: "evo", t: "1 action", r: "Touch", c: "V, S", d: "Instant", desc: "Heal 1d8 + spellcasting modifier." },
    "detect magic": { lvl: 1, s: "div", t: "1 action (R)", r: "Self", c: "V, S", d: "Conc, 10 min", x: "c", desc: "Sense magic within 30 ft; see auras." },
    "disguise self": { lvl: 1, s: "ill", t: "1 action", r: "Self", c: "V, S", d: "1 hour", desc: "Change your appearance." },
    "earth tremor": { lvl: 1, s: "evo", t: "1 action", r: "Self (10 ft)", c: "V, S", d: "Instant", desc: "Bludgeoning damage to nearby creatures; prone." },
    "entangle": { lvl: 1, s: "con", t: "1 action", r: "90 ft", c: "V, S", d: "Conc, up to 1 min", x: "c", desc: "Vines restrain creatures in a 20 ft square." },
    "expeditious retreat": { lvl: 1, s: "tra", t: "bonus", r: "Self", c: "V, S", d: "Conc, up to 10 min", x: "c", desc: "Dash as a bonus action each turn." },
    "faerie fire": { lvl: 1, s: "evo", t: "1 action", r: "60 ft", c: "V", d: "Conc, up to 1 min", x: "c", desc: "Objects/creatures glow; attacks have advantage." },
    "false life": { lvl: 1, s: "nec", t: "1 action", r: "Self", c: "V, S, M", d: "1 hour", desc: "Gain 1d4 + 4 temporary hit points." },
    "feather fall": { lvl: 1, s: "tra", t: "reaction", r: "60 ft", c: "V, M", d: "1 min", desc: "Up to five creatures fall slowly." },
    "find familiar": { lvl: 1, s: "con", t: "1 hour (R)", r: "10 ft", c: "V, S, M", d: "Instant", desc: "Summon a small spirit familiar." },
    "fog cloud": { lvl: 1, s: "con", t: "1 action", r: "120 ft", c: "V, S", d: "Conc, up to 1 hour", x: "c", desc: "Heavily obscured sphere of fog." },
    "goodberry": { lvl: 1, s: "tra", t: "1 action", r: "Touch", c: "V, S, M", d: "Instant", desc: "Create ten berries that each heal 1 HP." },
    "grease": { lvl: 1, s: "con", t: "1 action", r: "60 ft", c: "V, S, M", d: "1 min", desc: "10 ft square of grease; Dex save or prone." },
    "guiding bolt": { lvl: 1, s: "evo", t: "1 action", r: "120 ft", c: "V, S", d: "1 round", desc: "4d6 radiant; next attack against target has advantage." },
    "healing word": { lvl: 1, s: "evo", t: "bonus", r: "60 ft", c: "V", d: "Instant", desc: "Heal 1d4 + spellcasting modifier." },
    "hellish rebuke": { lvl: 1, s: "evo", t: "reaction", r: "60 ft", c: "V, S", d: "Instant", desc: "2d10 fire to a creature that damaged you." },
    "hex": { lvl: 1, s: "enc", t: "bonus", r: "90 ft", c: "V, S, M", d: "Conc, up to 1 hour", x: "c", desc: "Extra 1d6 necrotic per hit; disadvantage on one ability." },
    "hunter's mark": { lvl: 1, s: "div", t: "bonus", r: "90 ft", c: "V", d: "Conc, up to 1 hour", x: "c", desc: "Mark a target; extra 1d6 damage from your attacks." },
    "identify": { lvl: 1, s: "div", t: "1 min (R)", r: "Touch", c: "V, S, M", d: "Instant", desc: "Learn a magic item's properties." },
    "illusory script": { lvl: 1, s: "ill", t: "1 min (R)", r: "Touch", c: "S, M", d: "10 days", desc: "Hide the true meaning of a written message." },
    "inflict wounds": { lvl: 1, s: "nec", t: "1 action", r: "Touch", c: "V, S", d: "Instant", desc: "3d10 necrotic on a melee spell attack." },
    "jump": { lvl: 1, s: "tra", t: "1 action", r: "Touch", c: "V, S, M", d: "1 min", desc: "Triple a creature's jump distance." },
    "longstrider": { lvl: 1, s: "tra", t: "1 action", r: "Touch", c: "V, S, M", d: "1 hour", desc: "+10 ft speed for one creature." },
    "magic missile": { lvl: 1, s: "evo", t: "1 action", r: "120 ft", c: "V, S", d: "Instant", desc: "Three darts, 1d4 + 1 force each; never misses." },
    "protection from evil and good": { lvl: 1, s: "abj", t: "1 action", r: "Touch", c: "V, S, M", d: "Conc, up to 10 min", x: "c", desc: "Protect a creature from aberrations, celestials, elementals, fey, fiends, undead." },
    "purify food and drink": { lvl: 1, s: "tra", t: "1 action (R)", r: "10 ft", c: "V, S", d: "Instant", desc: "Purify food or water in a 5 ft radius." },
    "ray of sickness": { lvl: 1, s: "nec", t: "1 action", r: "60 ft", c: "V, S", d: "Instant", desc: "2d8 poison; Con save or poisoned." },
    "sanctuary": { lvl: 1, s: "abj", t: "bonus", r: "30 ft", c: "V, S, M", d: "1 min", desc: "Warded creature can't be attacked until it attacks." },
    "shield": { lvl: 1, s: "abj", t: "reaction", r: "Self", c: "V, S", d: "1 round", desc: "+5 AC against an incoming attack; immune to magic missile." },
    "shield of faith": { lvl: 1, s: "abj", t: "bonus", r: "60 ft", c: "V, S, M", d: "Conc, up to 10 min", x: "c", desc: "+2 AC for a target." },
    "sleep": { lvl: 1, s: "enc", t: "1 action", r: "90 ft", c: "V, S, M", d: "1 min", desc: "Put 5d8 HP of creatures to sleep." },
    "speak with animals": { lvl: 1, s: "div", t: "1 action (R)", r: "Self", c: "V, S", d: "10 min", desc: "Communicate with beasts." },
    "tasha's hideous laughter": { lvl: 1, s: "enc", t: "1 action", r: "30 ft", c: "V, S, M", d: "Conc, up to 1 min", x: "c", desc: "Target falls prone, incapacitated with laughter." },
    "thunderwave": { lvl: 1, s: "evo", t: "1 action", r: "Self (15 ft cube)", c: "V, S", d: "Instant", desc: "2d8 thunder; push creatures back." },
    "witch bolt": { lvl: 1, s: "evo", t: "1 action", r: "30 ft", c: "V, S, M", d: "Conc, up to 1 min", x: "c", desc: "1d12 lightning each turn, bonus action to repeat." },

    /* ── level 2 ── */
    "aid": { lvl: 2, s: "abj", t: "1 action", r: "30 ft", c: "V, S, M", d: "8 hours", desc: "Three allies gain +5 max HP (up to their current total)." },
    "alter self": { lvl: 2, s: "tra", t: "1 action", r: "Self", c: "V, S", d: "Conc, up to 1 hour", x: "c", desc: "Change your appearance, grow gills, or grow claws." },
    "animal messenger": { lvl: 2, s: "enc", t: "1 action (R)", r: "30 ft", c: "V, S, M", d: "24 hours", desc: "A small beast delivers your message." },
    "animal friendship": { lvl: 2, s: "enc", t: "1 action", r: "30 ft", c: "V, S, M", d: "24 hours", desc: "Charm a beast that fails a Wis save." },
    "arcane lock": { lvl: 2, s: "abj", t: "1 action", r: "Touch", c: "V, S, M", d: "Until dispelled", desc: "Magically lock a door or chest." },
    "augury": { lvl: 2, s: "div", t: "1 min (R)", r: "Self", c: "V, S, M", d: "Instant", desc: "Learn if an action will be weal or woe." },
    "barkskin": { lvl: 2, s: "tra", t: "1 action", r: "Touch", c: "V, S, M", d: "Conc, up to 1 hour", x: "c", desc: "Target's AC can't be less than 16." },
    "blindness/deafness": { lvl: 2, s: "nec", t: "1 action", r: "30 ft", c: "V", d: "1 min", desc: "Blind or deafen a creature, Con save." },
    "blur": { lvl: 2, s: "ill", t: "1 action", r: "Self", c: "V", d: "Conc, up to 1 min", x: "c", desc: "Attacks against you have disadvantage." },
    "branding smite": { lvl: 2, s: "evo", t: "bonus", r: "Self", c: "V", d: "Conc, up to 1 min", x: "c", desc: "Extra 2d6 radiant; target becomes visible if invisible." },
    "cloud of daggers": { lvl: 2, s: "con", t: "1 action", r: "60 ft", c: "V, S, M", d: "Conc, up to 1 min", x: "c", desc: "4d4 slashing in a cube; enter = damage." },
    "continual flame": { lvl: 2, s: "evo", t: "1 action", r: "Touch", c: "V, S, M", d: "Until dispelled", desc: "Create a permanent flame that sheds light." },
    "crown of madness": { lvl: 2, s: "enc", t: "1 action", r: "120 ft", c: "V, S", d: "Conc, up to 1 min", x: "c", desc: "Target attacks whoever you choose." },
    "darkness": { lvl: 2, s: "evo", t: "1 action", r: "60 ft", c: "V, M", d: "Conc, up to 10 min", x: "c", desc: "Magical darkness fills a 15 ft radius sphere." },
    "darkvision": { lvl: 2, s: "tra", t: "1 action", r: "Touch", c: "V, S, M", d: "8 hours", desc: "Grant darkvision 60 ft." },
    "enhance ability": { lvl: 2, s: "tra", t: "1 action", r: "Touch", c: "V, S, M", d: "Conc, up to 1 hour", x: "c", desc: "Advantage on one ability's checks." },
    "enlarge/reduce": { lvl: 2, s: "tra", t: "1 action", r: "30 ft", c: "V, S, M", d: "Conc, up to 1 min", x: "c", desc: "Enlarge (advantage Str) or reduce a creature." },
    "flame blade": { lvl: 2, s: "evo", t: "bonus", r: "Self", c: "V, S, M", d: "Conc, up to 10 min", x: "c", desc: "A scimitar of fire: 3d6 fire on a melee spell attack." },
    "flaming sphere": { lvl: 2, s: "con", t: "1 action", r: "60 ft", c: "V, S, M", d: "Conc, up to 1 min", x: "c", desc: "Roll a 5 ft sphere of 2d6 fire; bonus action to move it." },
    "gust of wind": { lvl: 2, s: "evo", t: "1 action", r: "Self (60 ft line)", c: "V, S, M", d: "Conc, up to 1 min", x: "c", desc: "A line of wind pushes creatures and douses flames." },
    "heat metal": { lvl: 2, s: "tra", t: "1 action", r: "60 ft", c: "V, S, M", d: "Conc, up to 1 min", x: "c", desc: "Heat a metal object; 2d8 fire, disadvantage to hold it." },
    "hold person": { lvl: 2, s: "enc", t: "1 action", r: "60 ft", c: "V, S, M", d: "Conc, up to 1 min", x: "c", desc: "Paralyze a humanoid, Wis save." },
    "invisibility": { lvl: 2, s: "ill", t: "1 action", r: "Touch", c: "V, S, M", d: "Conc, up to 1 hour", x: "c", desc: "Become invisible until you attack or cast." },
    "knock": { lvl: 2, s: "tra", t: "1 action", r: "60 ft", c: "V", d: "Instant", desc: "Unlock a door, chest, or lock." },
    "lesser restoration": { lvl: 2, s: "abj", t: "1 action", r: "Touch", c: "V, S", d: "Instant", desc: "Cure disease, poison, blindness, deafness, or paralysis." },
    "levitate": { lvl: 2, s: "tra", t: "1 action", r: "60 ft", c: "V, S, M", d: "Conc, up to 10 min", x: "c", desc: "Float a creature or object up to 20 ft." },
    "magic weapon": { lvl: 2, s: "tra", t: "bonus", r: "Touch", c: "V, S", d: "Conc, up to 1 hour", x: "c", desc: "Make a weapon magical (+1 to attack and damage)." },
    "mirror image": { lvl: 2, s: "ill", t: "1 action", r: "Self", c: "V, S", d: "1 min", desc: "Create three illusory duplicates that absorb attacks." },
    "misty step": { lvl: 2, s: "con", t: "bonus", r: "Self", c: "V", d: "Instant", desc: "Teleport up to 30 ft." },
    "moonbeam": { lvl: 2, s: "evo", t: "1 action", r: "120 ft", c: "V, S, M", d: "Conc, up to 1 min", x: "c", desc: "2d10 radiant in a 5 ft cylinder." },
    "pass without trace": { lvl: 2, s: "abj", t: "1 action", r: "Self", c: "V, S, M", d: "Conc, up to 1 hour", x: "c", desc: "+10 to Stealth for the party." },
    "prayer of healing": { lvl: 2, s: "evo", t: "10 min", r: "30 ft", c: "V", d: "Instant", desc: "Heal 2d8 + mod to up to six allies." },
    "protection from poison": { lvl: 2, s: "abj", t: "1 action", r: "Touch", c: "V, S", d: "1 hour", desc: "Neutralize poison; advantage vs poisoned." },
    "scorching ray": { lvl: 2, s: "evo", t: "1 action", r: "120 ft", c: "V, S", d: "Instant", desc: "Three rays, each 2d6 fire." },
    "see invisibility": { lvl: 2, s: "div", t: "1 action", r: "Self", c: "V, S, M", d: "1 hour", desc: "See invisible creatures and objects." },
    "shadow blade": { lvl: 2, s: "ill", t: "bonus", r: "Self", c: "V, S", d: "Conc, up to 1 min", x: "c", desc: "A shadowy blade: 2d8 psychic, advantage in dim light." },
    "shatter": { lvl: 2, s: "evo", t: "1 action", r: "60 ft", c: "V, S, M", d: "Instant", desc: "3d8 thunder in a 10 ft sphere, Con save." },
    "silence": { lvl: 2, s: "ill", t: "1 action (R)", r: "120 ft", c: "V, S", d: "Conc, up to 10 min", x: "c", desc: "A 20 ft sphere of silence." },
    "spider climb": { lvl: 2, s: "tra", t: "1 action", r: "Touch", c: "V, S, M", d: "Conc, up to 1 hour", x: "c", desc: "Walk on ceilings and walls." },
    "spiritual weapon": { lvl: 2, s: "evo", t: "bonus", r: "60 ft", c: "V, S", d: "1 min", desc: "A spectral weapon attacks for 1d8 + mod, bonus action." },
    "suggestion": { lvl: 2, s: "enc", t: "1 action", r: "30 ft", c: "V, M", d: "Conc, up to 8 hours", x: "c", desc: "Wis save or follow a reasonable suggestion." },
    "warding bond": { lvl: 2, s: "abj", t: "1 action", r: "Touch", c: "V, S, M", d: "1 hour", desc: "Share damage and AC bonuses with a creature." },
    "web": { lvl: 2, s: "con", t: "1 action", r: "60 ft", c: "V, S, M", d: "Conc, up to 1 hour", x: "c", desc: "Restrain creatures in a web-filled area." },

    /* ── level 3 ── */
    "animate dead": { lvl: 3, s: "nec", t: "1 min", r: "10 ft", c: "V, S, M", d: "Instant", desc: "Raise a skeleton or zombie under your control." },
    "beacon of hope": { lvl: 3, s: "abj", t: "1 action", r: "30 ft", c: "V, S", d: "Conc, up to 30 min", x: "c", desc: "Allies within 30 ft have advantage on Wis saves and healing." },
    "bestow curse": { lvl: 3, s: "nec", t: "1 action", r: "Touch", c: "V, S", d: "Conc, up to 1 min", x: "c", desc: "Curse a creature with a variety of effects." },
    "blink": { lvl: 3, s: "tra", t: "1 action", r: "Self", c: "V, S", d: "1 min", desc: "Blink between the Ethereal and Material plane each turn." },
    "call lightning": { lvl: 3, s: "con", t: "1 action", r: "120 ft", c: "V, S", d: "Conc, up to 10 min", x: "c", desc: "3d10 lightning strikes, repeated with an action." },
    "clairvoyance": { lvl: 3, s: "div", t: "10 min", r: "1 mile", c: "V, S, M", d: "Conc, up to 10 min", x: "c", desc: "See or hear a distant location." },
    "counterspell": { lvl: 3, s: "abj", t: "reaction", r: "60 ft", c: "S", d: "Instant", desc: "Cancel another spell as it's cast." },
    "create food and water": { lvl: 3, s: "con", t: "1 action", r: "30 ft", c: "V, S", d: "Instant", desc: "Create food and water for 15 creatures." },
    "daylight": { lvl: 3, s: "evo", t: "1 action", r: "60 ft", c: "V, S", d: "1 hour", desc: "Bright light in a 60 ft radius; dispels darkness." },
    "dispel magic": { lvl: 3, s: "abj", t: "1 action", r: "120 ft", c: "V, S", d: "Instant", desc: "End spells of 3rd level or lower." },
    "fear": { lvl: 3, s: "ill", t: "1 action", r: "Self (30 ft cone)", c: "V, S, M", d: "Conc, up to 1 min", x: "c", desc: "Frightened creatures drop weapons and flee." },
    "fireball": { lvl: 3, s: "evo", t: "1 action", r: "150 ft", c: "V, S, M", d: "Instant", desc: "8d6 fire in a 20 ft radius, Dex save for half." },
    "fly": { lvl: 3, s: "tra", t: "1 action", r: "Touch", c: "V, S, M", d: "Conc, up to 10 min", x: "c", desc: "Grant a flying speed of 60 ft." },
    "gaseous form": { lvl: 3, s: "tra", t: "1 action", r: "Touch", c: "V, S, M", d: "Conc, up to 1 hour", x: "c", desc: "Turn a creature into a misty cloud." },
    "haste": { lvl: 3, s: "tra", t: "1 action", r: "30 ft", c: "V, S, M", d: "Conc, up to 1 min", x: "c", desc: "Target gains +2 AC, doubled speed, and an extra action." },
    "hypnotic pattern": { lvl: 3, s: "ill", t: "1 action", r: "120 ft", c: "S, M", d: "Conc, up to 1 min", x: "c", desc: "Fascinate creatures in a 30 ft cube." },
    "lightning bolt": { lvl: 3, s: "evo", t: "1 action", r: "Self (100 ft line)", c: "V, S, M", d: "Instant", desc: "8d6 lightning in a line, Dex save." },
    "major image": { lvl: 3, s: "ill", t: "1 action", r: "120 ft", c: "V, S, M", d: "Conc, up to 10 min", x: "c", desc: "Create a realistic image with sound." },
    "mass healing word": { lvl: 3, s: "evo", t: "bonus", r: "60 ft", c: "V", d: "Instant", desc: "Heal 1d4 + mod to up to six creatures." },
    "nondetection": { lvl: 3, s: "abj", t: "1 action", r: "Touch", c: "V, S, M", d: "8 hours", desc: "Hide a creature from divination magic." },
    "plant growth": { lvl: 3, s: "tra", t: "1 action or 8 hours", r: "150 ft", c: "V, S", d: "Instant", desc: "Enrich land or create impenetrable overgrowth." },
    "protection from energy": { lvl: 3, s: "abj", t: "1 action", r: "Touch", c: "V, S", d: "Conc, up to 1 hour", x: "c", desc: "Resistance to one damage type." },
    "revivify": { lvl: 3, s: "nec", t: "1 action", r: "Touch", c: "V, S, M", d: "Instant", desc: "Return a creature that died within the last minute to 1 HP." },
    "sleet storm": { lvl: 3, s: "con", t: "1 action", r: "150 ft", c: "V, S, M", d: "Conc, up to 1 min", x: "c", desc: "Freezing rain and sleet; heavily obscured." },
    "slow": { lvl: 3, s: "tra", t: "1 action", r: "120 ft", c: "V, S, M", d: "Conc, up to 1 min", x: "c", desc: "Six creatures are slowed: -2 AC, fewer actions." },
    "speak with dead": { lvl: 3, s: "nec", t: "1 action", r: "10 ft", c: "V, S, M", d: "10 min", desc: "Ask a corpse up to five questions." },
    "spirit guardians": { lvl: 3, s: "con", t: "1 action", r: "Self (15 ft radius)", c: "V, S, M", d: "Conc, up to 10 min", x: "c", desc: "Spectral guardians damage and slow nearby enemies." },
    "vampiric touch": { lvl: 3, s: "nec", t: "1 action", r: "Self", c: "V, S", d: "Conc, up to 1 min", x: "c", desc: "3d6 necrotic; heal half the damage." },
    "water breathing": { lvl: 3, s: "tra", t: "1 action (R)", r: "30 ft", c: "V, S, M", d: "24 hours", desc: "Grant the ability to breathe underwater." },
    "water walk": { lvl: 3, s: "tra", t: "1 action (R)", r: "30 ft", c: "V, S, M", d: "1 hour", desc: "Walk on liquid surfaces." },

    /* ── level 4 ── */
    "banishment": { lvl: 4, s: "abj", t: "1 action", r: "60 ft", c: "V, S, M", d: "Conc, up to 1 min", x: "c", desc: "Send a creature to another plane." },
    "blight": { lvl: 4, s: "nec", t: "1 action", r: "30 ft", c: "V, S", d: "Instant", desc: "8d8 necrotic, Con save for half." },
    "confusion": { lvl: 4, s: "enc", t: "1 action", r: "90 ft", c: "V, S, M", d: "Conc, up to 1 min", x: "c", desc: "Confuse creatures in a 10 ft radius." },
    "conjure minor elementals": { lvl: 4, s: "con", t: "1 min", r: "90 ft", c: "V, S", d: "Conc, up to 1 hour", x: "c", desc: "Summon up to eight small elementals." },
    "control water": { lvl: 4, s: "tra", t: "1 action", r: "300 ft", c: "V, S, M", d: "Conc, up to 10 min", x: "c", desc: "Control flood, part, redirect, or whirlpool water." },
    "death ward": { lvl: 4, s: "abj", t: "1 action", r: "Touch", c: "V, S", d: "8 hours", desc: "Drop to 1 HP instead of 0 when you would die." },
    "dimension door": { lvl: 4, s: "con", t: "1 action", r: "500 ft", c: "V", d: "Instant", desc: "Teleport yourself and one willing creature." },
    "divination": { lvl: 4, s: "div", t: "1 action (R)", r: "Self", c: "V, S, M", d: "Instant", desc: "Receive a prophetic vision." },
    "dominate beast": { lvl: 4, s: "enc", t: "1 action", r: "60 ft", c: "V, S", d: "Conc, up to 1 min", x: "c", desc: "Control a beast's actions." },
    "fabricate": { lvl: 4, s: "tra", t: "10 min", r: "120 ft", c: "V, S", d: "Instant", desc: "Transform raw materials into a finished item." },
    "fire shield": { lvl: 4, s: "evo", t: "1 action", r: "Self", c: "V, S, M", d: "10 min", desc: "A shroud of flames; cold/fire damage to attackers." },
    "freedom of movement": { lvl: 4, s: "abj", t: "1 action", r: "Touch", c: "V, S, M", d: "1 hour", desc: "Ignore difficult terrain and magical restraint." },
    "greater invisibility": { lvl: 4, s: "ill", t: "1 action", r: "Touch", c: "V, S", d: "Conc, up to 1 min", x: "c", desc: "Turn invisible while attacking or casting." },
    "guardian of faith": { lvl: 4, s: "con", t: "1 action", r: "30 ft", c: "V", d: "8 hours", desc: "A spectral guardian attacks creatures in an area." },
    "ice storm": { lvl: 4, s: "evo", t: "1 action", r: "300 ft", c: "V, S, M", d: "Instant", desc: "2d8 bludgeoning + 4d6 cold in a 20 ft radius." },
    "phantasmal killer": { lvl: 4, s: "ill", t: "1 action", r: "120 ft", c: "V, S", d: "Conc, up to 1 min", x: "c", desc: "A target's worst fear manifests; psychic damage." },
    "polymorph": { lvl: 4, s: "tra", t: "1 action", r: "60 ft", c: "V, S, M", d: "Conc, up to 1 hour", x: "c", desc: "Transform a creature into a beast." },
    "stone skin": { lvl: 4, s: "abj", t: "1 action", r: "Touch", c: "V, S, M", d: "Conc, up to 1 hour", x: "c", desc: "Resistance to nonmagical bludgeoning, piercing, slashing." },
    "wall of fire": { lvl: 4, s: "evo", t: "1 action", r: "120 ft", c: "V, S, M", d: "Conc, up to 1 min", x: "c", desc: "A wall of fire, 5d8 damage on one side." },

    /* ── level 5 ── */
    "animate objects": { lvl: 5, s: "tra", t: "1 action", r: "120 ft", c: "V, S", d: "Conc, up to 1 min", x: "c", desc: "Animate up to ten small objects." },
    "antilife shell": { lvl: 5, s: "abj", t: "1 action", r: "Self (10 ft)", c: "V, S", d: "Conc, up to 1 hour", x: "c", desc: "A barrier that keeps living creatures out." },
    "banishing smite": { lvl: 5, s: "abj", t: "bonus", r: "Self", c: "V", d: "Conc, up to 1 min", x: "c", desc: "Extra 5d10 force; banish a target below 50 HP." },
    "bigby's hand": { lvl: 5, s: "evo", t: "1 action", r: "120 ft", c: "V, S, M", d: "Conc, up to 1 min", x: "c", desc: "A giant spectral hand grapples, shoves, or strikes." },
    "cloudkill": { lvl: 5, s: "con", t: "1 action", r: "120 ft", c: "V, S", d: "Conc, up to 10 min", x: "c", desc: "A 20 ft radius of poisonous gas, 5d8 damage." },
    "cone of cold": { lvl: 5, s: "evo", t: "1 action", r: "Self (60 ft cone)", c: "V, S, M", d: "Instant", desc: "8d8 cold in a 60 ft cone, Con save for half." },
    "conjure elemental": { lvl: 5, s: "con", t: "1 min", r: "90 ft", c: "V, S, M", d: "Conc, up to 1 hour", x: "c", desc: "Summon an elemental servant." },
    "contagion": { lvl: 5, s: "nec", t: "1 action", r: "Touch", c: "V, S", d: "7 days", desc: "Inflict a disease; three failed saves." },
    "creation": { lvl: 5, s: "ill", t: "1 min", r: "30 ft", c: "V, S, M", d: "Special", desc: "Create a nonliving object from nothing." },
    "destructive wave": { lvl: 5, s: "evo", t: "1 action", r: "Self (30 ft radius)", c: "V", d: "Instant", desc: "Radiant/necrotic damage, knock back; paladin signature." },
    "dominate person": { lvl: 5, s: "enc", t: "1 action", r: "60 ft", c: "V, S", d: "Conc, up to 1 min", x: "c", desc: "Control a humanoid's actions." },
    "dispel evil and good": { lvl: 5, s: "abj", t: "1 action", r: "Self", c: "V, S, M", d: "Conc, up to 1 min", x: "c", desc: "Banish fey/elementals and gain protection against aberrations and fiends." },
    "flame strike": { lvl: 5, s: "evo", t: "1 action", r: "60 ft", c: "V, S, M", d: "Instant", desc: "4d6 fire + 4d6 radiant in a 10 ft radius." },
    "greater restoration": { lvl: 5, s: "abj", t: "1 action", r: "Touch", c: "V, S, M", d: "Instant", desc: "End curses, petrification, exhaustion, and more." },
    "hold monster": { lvl: 5, s: "enc", t: "1 action", r: "90 ft", c: "V, S, M", d: "Conc, up to 1 min", x: "c", desc: "Paralyze any creature, Wis save." },
    "holy weapon": { lvl: 5, s: "evo", t: "bonus", r: "Touch", c: "V, S", d: "Conc, up to 1 hour", x: "c", desc: "A weapon becomes holy: +2d8 radiant per hit." },
    "insect plague": { lvl: 5, s: "con", t: "1 action", r: "300 ft", c: "V, S, M", d: "Conc, up to 10 min", x: "c", desc: "A swarm of locusts deals 4d10 piercing." },
    "legend lore": { lvl: 5, s: "div", t: "10 min", r: "Self", c: "V, S, M", d: "Instant", desc: "Learn legends about a person, place, or object." },
    "mass cure wounds": { lvl: 5, s: "evo", t: "1 action", r: "60 ft", c: "V, S", d: "Instant", desc: "Heal 5d8 + mod to creatures within 60 ft." },
    "mislead": { lvl: 5, s: "ill", t: "1 action", r: "Self", c: "S", d: "Conc, up to 1 hour", x: "c", desc: "Become invisible while an illusion takes your place." },
    "modify memory": { lvl: 5, s: "enc", t: "1 action", r: "30 ft", c: "V, S", d: "Conc, up to 1 min", x: "c", desc: "Alter a creature's memories." },
    "passwall": { lvl: 5, s: "tra", t: "1 action", r: "30 ft", c: "V, S, M", d: "1 hour", desc: "Open a 5 ft passage through a wall." },
    "scrying": { lvl: 5, s: "div", t: "10 min", r: "Self", c: "V, S, M", d: "Conc, up to 10 min", x: "c", desc: "See and hear a distant creature." },
    "seeming": { lvl: 5, s: "ill", t: "1 action", r: "30 ft", c: "V, S", d: "8 hours", desc: "Change the appearance of many creatures." },
    "telekinesis": { lvl: 5, s: "tra", t: "1 action", r: "60 ft", c: "V, S", d: "Conc, up to 10 min", x: "c", desc: "Move objects or creatures with your mind." },
    "wall of force": { lvl: 5, s: "evo", t: "1 action", r: "120 ft", c: "V, S, M", d: "Conc, up to 10 min", x: "c", desc: "An invisible, indestructible wall." },
    "wall of stone": { lvl: 5, s: "evo", t: "1 action", r: "120 ft", c: "V, S, M", d: "Conc, up to 10 min", x: "c", desc: "Create a permanent wall of stone." },

    /* ── level 6 ── */
    "blade barrier": { lvl: 6, s: "evo", t: "1 action", r: "Self (100 ft line)", c: "V, S", d: "Conc, up to 10 min", x: "c", desc: "A wall of whirling blades." },
    "chain lightning": { lvl: 6, s: "evo", t: "1 action", r: "150 ft", c: "V, S, M", d: "Instant", desc: "4 bolts of 10d8 lightning; arc to more targets." },
    "circle of death": { lvl: 6, s: "nec", t: "1 action", r: "150 ft", c: "V, S, M", d: "Instant", desc: "8d6 necrotic in a 60 ft radius." },
    "contingency": { lvl: 6, s: "evo", t: "10 min", r: "Self", c: "V, S, M", d: "10 days", desc: "Set a spell to trigger under a condition." },
    "disintegrate": { lvl: 6, s: "tra", t: "1 action", r: "60 ft", c: "V, S, M", d: "Instant", desc: "10d6 + 40 force; destroy on 0 HP." },
    "eyebite": { lvl: 6, s: "nec", t: "1 action", r: "Self", c: "V, S", d: "Conc, up to 1 min", x: "c", desc: "Your eyes inflict panic, sleep, or sickness." },
    "find the path": { lvl: 6, s: "div", t: "1 min", r: "Self", c: "V, S, M", d: "Conc, up to 1 day", x: "c", desc: "Know the shortest path to a destination." },
    "flesh to stone": { lvl: 6, s: "tra", t: "1 action", r: "60 ft", c: "V, S, M", d: "Conc, up to 1 min", x: "c", desc: "Turn a creature to stone over three failed saves." },
    "globe of invulnerability": { lvl: 6, s: "abj", t: "1 action", r: "Self (10 ft)", c: "V, S, M", d: "Conc, up to 1 min", x: "c", desc: "A barrier that blocks low-level spells." },
    "heal": { lvl: 6, s: "evo", t: "1 action", r: "60 ft", c: "V, S", d: "Instant", desc: "Restore 70 hit points and end most conditions." },
    "heroes' feast": { lvl: 6, s: "con", t: "10 min", r: "30 ft", c: "V, S, M", d: "Instant", desc: "A feast that grants benefits for 24 hours." },
    "irresistible dance": { lvl: 6, s: "enc", t: "1 action", r: "30 ft", c: "V", d: "Conc, up to 1 min", x: "c", desc: "A creature dances uncontrollably." },
    "mass suggestion": { lvl: 6, s: "enc", t: "1 action", r: "60 ft", c: "V, M", d: "Conc, up to 24 hours", x: "c", desc: "Suggest a course of action to twelve creatures." },
    "move earth": { lvl: 6, s: "tra", t: "1 action", r: "120 ft", c: "V, S, M", d: "Conc, up to 2 hours", x: "c", desc: "Shape dirt and stone over a large area." },
    "programmed illusion": { lvl: 6, s: "ill", t: "1 action", r: "120 ft", c: "V, S, M", d: "Until dispelled", desc: "An illusion that triggers on a condition." },
    "sunbeam": { lvl: 6, s: "evo", t: "1 action", r: "Self (60 ft line)", c: "V, S, M", d: "Conc, up to 1 min", x: "c", desc: "A beam of 6d8 radiant, repeatable; blinds." },
    "true seeing": { lvl: 6, s: "div", t: "1 action", r: "Touch", c: "V, S, M", d: "1 hour", desc: "See through illusions, darkness, and shapeshifters." },
    "word of recall": { lvl: 6, s: "con", t: "1 action", r: "5 ft", c: "V", d: "Instant", desc: "Teleport to a previously designated sanctuary." },

    /* ── level 7 ── */
    "conjure celestial": { lvl: 7, s: "con", t: "1 min", r: "90 ft", c: "V, S", d: "Conc, up to 1 hour", x: "c", desc: "Summon a celestial being." },
    "delayed blast fireball": { lvl: 7, s: "evo", t: "1 action", r: "150 ft", c: "V, S, M", d: "Conc, up to 1 min", x: "c", desc: "A fireball that detonates when released." },
    "divine word": { lvl: 7, s: "evo", t: "bonus", r: "30 ft", c: "V", d: "Instant", desc: "Kill or banish creatures by HP thresholds." },
    "etherealness": { lvl: 7, s: "tra", t: "1 action", r: "Self", c: "V, S", d: "Up to 8 hours", desc: "Enter the Ethereal Plane." },
    "fire storm": { lvl: 7, s: "evo", t: "1 action", r: "150 ft", c: "V, S", d: "Instant", desc: "7d10 fire across a 10 ft × 10 ft area." },
    "forcecage": { lvl: 7, s: "evo", t: "1 action", r: "100 ft", c: "V, S, M", d: "1 hour", desc: "Imprison a creature in a cage of force." },
    "mirage arcane": { lvl: 7, s: "ill", t: "10 min", r: "Sight", c: "V, S", d: "10 days", desc: "Change the landscape's appearance over a mile." },
    "plane shift": { lvl: 7, s: "con", t: "1 action", r: "Touch", c: "V, S, M", d: "Instant", desc: "Transport creatures to another plane." },
    "prismatic spray": { lvl: 7, s: "evo", t: "1 action", r: "Self (60 ft cone)", c: "V, S", d: "Instant", desc: "A spray of multicolored light with random effects." },
    "project image": { lvl: 7, s: "ill", t: "1 action", r: "500 miles", c: "V, S, M", d: "Conc, up to 1 day", x: "c", desc: "Send a duplicate of yourself across the realm." },
    "regenerate": { lvl: 7, s: "tra", t: "1 min", r: "Touch", c: "V, S, M", d: "1 hour", desc: "Regrow limbs and regain 4d8 + 15 HP." },
    "resurrection": { lvl: 7, s: "nec", t: "1 hour", r: "Touch", c: "V, S, M", d: "Instant", desc: "Return a creature that died within a century to life." },
    "reverse gravity": { lvl: 7, s: "tra", t: "1 action", r: "100 ft", c: "V, S, M", d: "Conc, up to 1 min", x: "c", desc: "A 50 ft cylinder where gravity is reversed." },
    "symbol": { lvl: 7, s: "abj", t: "1 min", r: "Touch", c: "V, S, M", d: "Until dispelled", desc: "Inscribe a glyph with a harmful effect." },
    "teleport": { lvl: 7, s: "con", t: "1 action", r: "10 ft", c: "V", d: "Instant", desc: "Teleport to a destination you know." },

    /* ── level 8 ── */
    "antimagic field": { lvl: 8, s: "abj", t: "1 action", r: "Self (10 ft)", c: "V, S, M", d: "Conc, up to 1 hour", x: "c", desc: "Suppress all magic in a 10 ft radius." },
    "clone": { lvl: 8, s: "nec", t: "1 hour", r: "Touch", c: "V, S, M", d: "120 days", desc: "Create a clone that your soul inhabits on death." },
    "control weather": { lvl: 8, s: "tra", t: "10 min", r: "Self (5 miles)", c: "V, S, M", d: "Conc, up to 8 hours", x: "c", desc: "Change the weather over a large area." },
    "dominate monster": { lvl: 8, s: "enc", t: "1 action", r: "60 ft", c: "V, S", d: "Conc, up to 1 hour", x: "c", desc: "Control any creature's actions." },
    "earthquake": { lvl: 8, s: "evo", t: "1 action", r: "500 ft", c: "V, S, M", d: "Conc, up to 1 min", x: "c", desc: "Tremor that damages and topples structures." },
    "feeblemind": { lvl: 8, s: "enc", t: "1 action", r: "150 ft", c: "V, S, M", d: "Instant", desc: "A creature's intelligence and charisma drop to 1." },
    "holy aura": { lvl: 8, s: "abj", t: "1 action", r: "Self", c: "V, S, M", d: "Conc, up to 1 min", x: "c", desc: "Allies within 30 ft gain advantage on saves and resistance." },
    "incendiary cloud": { lvl: 8, s: "con", t: "1 action", r: "150 ft", c: "V, S", d: "Conc, up to 1 min", x: "c", desc: "A cloud of fire that deals 10d8 fire." },
    "maze": { lvl: 8, s: "con", t: "1 action", r: "60 ft", c: "V, S", d: "Conc, up to 10 min", x: "c", desc: "Banish a creature into a labyrinthine demiplane." },
    "mind blank": { lvl: 8, s: "abj", t: "1 action", r: "Touch", c: "V, S", d: "24 hours", desc: "Immune to psychic damage and mind-reading." },
    "power word stun": { lvl: 8, s: "enc", t: "1 action", r: "60 ft", c: "V", d: "Instant", desc: "Stun a creature with 150 HP or less." },
    "sunburst": { lvl: 8, s: "evo", t: "1 action", r: "150 ft", c: "V, S, M", d: "Instant", desc: "12d6 radiant; blind creatures; destroy undead." },

    /* ── level 9 ── */
    "astral projection": { lvl: 9, s: "nec", t: "1 hour", r: "10 ft", c: "V, S, M", d: "Special", desc: "Project your soul into the Astral Plane." },
    "foresight": { lvl: 9, s: "div", t: "1 min", r: "Touch", c: "V, S, M", d: "8 hours", desc: "The target sees flashes of the future: advantage everywhere." },
    "gate": { lvl: 9, s: "con", t: "1 action", r: "60 ft", c: "V, S, M", d: "Conc, up to 1 min", x: "c", desc: "Open a portal to another plane." },
    "imprisonment": { lvl: 9, s: "abj", t: "1 min", r: "30 ft", c: "V, S, M", d: "Until dispelled", desc: "Imprison a creature for eternity in a binding form." },
    "mass heal": { lvl: 9, s: "evo", t: "1 action", r: "60 ft", c: "V, S", d: "Instant", desc: "Heal up to 700 HP divided among creatures." },
    "meteor swarm": { lvl: 9, s: "evo", t: "1 action", r: "1 mile", c: "V, S", d: "Instant", desc: "Four meteors deal 20d6 fire + 20d6 bludgeoning." },
    "power word heal": { lvl: 9, s: "evo", t: "1 action", r: "Touch", c: "V, S", d: "Instant", desc: "Fully restore one creature's hit points." },
    "power word kill": { lvl: 9, s: "enc", t: "1 action", r: "60 ft", c: "V", d: "Instant", desc: "Instantly kill a creature with 100 HP or less." },
    "prismatic wall": { lvl: 9, s: "abj", t: "1 action", r: "60 ft", c: "V, S", d: "10 min", desc: "A wall of seven colored layers." },
    "psychic scream": { lvl: 9, s: "enc", t: "1 action", r: "90 ft", c: "S", d: "Instant", desc: "14d6 psychic; stun creatures." },
    "time stop": { lvl: 9, s: "tra", t: "1 action", r: "Self", c: "V", d: "Instant", desc: "Take 1d4+1 extra turns." },
    "true polymorph": { lvl: 9, s: "tra", t: "1 action", r: "30 ft", c: "V, S, M", d: "Conc, up to 1 hour", x: "c", desc: "Permanently transform a creature or object." },
    "true resurrection": { lvl: 9, s: "nec", t: "1 hour", r: "Touch", c: "V, S, M", d: "Instant", desc: "Restore any creature that died in the last century." },
    "wish": { lvl: 9, s: "con", t: "1 action", r: "Self", c: "V", d: "Instant", desc: "Duplicate any spell, or reshape reality (with risk)." },
    "weird": { lvl: 9, s: "ill", t: "1 action", r: "120 ft", c: "V, S", d: "Conc, up to 1 min", x: "c", desc: "Horrific fears deal psychic damage." },
  };

  const SCHOOLS = S;

  /* class spell lists (ids, by level) */
  const CLASS_LISTS = {
    bard: {
      cantrips: ["vicious mockery", "prestidigitation", "mage hand", "minor illusion", "light", "dancing lights", "friends", "message"],
      1: ["cure wounds", "faerie fire", "healing word", "thunderwave", "charm person", "comprehend languages", "disguise self", "feather fall", "hideous laughter", "sleep", "tasha's hideous laughter"],
      2: ["blindness/deafness", "calm emotions", "hold person", "invisibility", "lesser restoration", "shatter", "silence", "suggestion", "enhance ability", "heat metal"],
      3: ["dispel magic", "fear", "hypnotic pattern", "major image", "plant growth", "slow", "speak with dead", "stinking cloud"],
      4: ["dimension door", "freedom of movement", "greater invisibility", "phantasmal killer", "polymorph", "confusion", "dominate beast"],
      5: ["animate objects", "greater restoration", "hold monster", "mass cure wounds", "mislead", "modify memory", "seeming", "teleportation circle"],
      6: ["eyebite", "irresistible dance", "mass suggestion", "programmed illusion", "true seeing"],
      7: ["forcecage", "mirage arcane", "prismatic spray", "project image", "resurrection"],
      8: ["feeblemind", "glibness", "mind blank", "power word stun"],
      9: ["foresight", "power word heal", "psychic scream", "true polymorph"],
    },
    cleric: {
      cantrips: ["guidance", "light", "resistance", "sacred flame", "spare the dying", "thaumaturgy", "mending"],
      1: ["bless", "command", "cure wounds", "detect magic", "guiding bolt", "healing word", "inflict wounds", "protection from evil and good", "purify food and drink", "sanctuary", "shield of faith"],
      2: ["aid", "augury", "blindness/deafness", "hold person", "lesser restoration", "prayer of healing", "protection from poison", "silence", "spiritual weapon", "warding bond"],
      3: ["beacon of hope", "create food and water", "daylight", "dispel magic", "mass healing word", "protection from energy", "revivify", "speak with dead", "spirit guardians"],
      4: ["banishment", "death ward", "divination", "freedom of movement", "guardian of faith", "stone skin"],
      5: ["contagion", "dispel evil and good", "flame strike", "greater restoration", "holy weapon", "insect plague", "legend lore", "mass cure wounds", "scrying"],
      6: ["blade barrier", "heal", "heroes' feast", "true seeing", "word of recall"],
      7: ["conjure celestial", "divine word", "fire storm", "regenerate", "resurrection"],
      8: ["antimagic field", "control weather", "earthquake", "holy aura", "sunburst"],
      9: ["astral projection", "gate", "mass heal", "power word heal", "true resurrection"],
    },
    druid: {
      cantrips: ["druidcraft", "guidance", "produce flame", "resistance", "shillelagh", "thorn whip", "mending"],
      1: ["animal friendship", "cure wounds", "detect magic", "entangle", "faerie fire", "goodberry", "healing word", "longstrider", "speak with animals", "thunderwave"],
      2: ["animal messenger", "barkskin", "beast sense", "darkvision", "enhance ability", "flame blade", "flaming sphere", "gust of wind", "heat metal", "lesser restoration", "moonbeam", "pass without trace", "spider climb"],
      3: ["call lightning", "conjure animals", "daylight", "plant growth", "protection from energy", "sleet storm", "speak with plants", "water breathing", "water walk"],
      4: ["blight", "conjure minor elementals", "control water", "dominate beast", "freedom of movement", "ice storm", "polymorph", "stone skin"],
      5: ["antilife shell", "conjure elemental", "contagion", "insect plague", "mass cure wounds", "scrying", "wall of stone"],
      6: ["conjure fey", "find the path", "heal", "move earth", "sunbeam", "transport via plants"],
      7: ["fire storm", "mirage arcane", "plane shift", "regenerate", "reverse gravity"],
      8: ["animal shapes", "antipathy/sympathy", "control weather", "earthquake", "feeblemind", "sunburst"],
      9: ["foresight", "shapechange", "storm of vengeance", "true resurrection"],
    },
    sorcerer: {
      cantrips: ["acid splash", "chill touch", "fire bolt", "light", "mage hand", "minor illusion", "prestidigitation", "ray of frost", "shocking grasp"],
      1: ["burning hands", "chromatic orb", "color spray", "detect magic", "disguise self", "expeditious retreat", "false life", "feather fall", "mage armor", "magic missile", "shield", "sleep", "thunderwave"],
      2: ["alter self", "blur", "darkness", "enhance ability", "enlarge/reduce", "hold person", "invisibility", "levitate", "mirror image", "misty step", "scorching ray", "shatter", "spider climb", "suggestion", "web"],
      3: ["blink", "counterspell", "dispel magic", "fireball", "fly", "haste", "hypnotic pattern", "lightning bolt", "major image", "slow"],
      4: ["banishment", "blight", "dimension door", "dominate beast", "greater invisibility", "ice storm", "polymorph", "stone skin", "wall of fire"],
      5: ["animate objects", "cloudkill", "cone of cold", "hold monster", "seeming", "telekinesis", "wall of force", "wall of stone"],
      6: ["chain lightning", "circle of death", "disintegrate", "eyebite", "globe of invulnerability", "sunbeam"],
      7: ["delayed blast fireball", "etherealness", "finger of death", "plane shift", "prismatic spray", "reverse gravity", "teleport"],
      8: ["incendiary cloud", "maze", "power word stun", "sunburst"],
      9: ["meteor swarm", "power word kill", "time stop", "wish"],
    },
    warlock: {
      cantrips: ["chill touch", "eldritch blast", "mage hand", "minor illusion", "poison spray", "prestidigitation", "friends", "booming blade"],
      1: ["armor of agathys", "arms of hadar", "charm person", "comprehend languages", "expeditious retreat", "hellish rebuke", "hex", "protection from evil and good", "witch bolt"],
      2: ["cloud of daggers", "crown of madness", "darkness", "hold person", "invisibility", "mirror image", "misty step", "scorching ray", "shadow blade", "suggestion"],
      3: ["counterspell", "dispel magic", "fear", "fly", "hypnotic pattern", "major image", "vampiric touch"],
      4: ["banishment", "blight", "dimension door", "phantasmal killer", "shadow of moil"],
      5: ["banishing smite", "hold monster", "scrying", "telekinesis", "wall of force"],
      6: ["circle of death", "conjure fey", "eyebite", "mass suggestion", "true seeing"],
      7: ["finger of death", "forcecage", "plane shift"],
      8: ["demilich", "dominate monster", "feeblemind", "power word stun"],
      9: ["foresight", "gate", "power word kill", "true polymorph"],
    },
    wizard: {
      cantrips: ["fire bolt", "mage hand", "prestidigitation", "ray of frost", "shocking grasp", "minor illusion", "booming blade", "message", "light", "mending"],
      1: ["absorb elements", "burning hands", "charm person", "chromatic orb", "comprehend languages", "detect magic", "disguise self", "expeditious retreat", "false life", "feather fall", "find familiar", "fog cloud", "grease", "identify", "jump", "longstrider", "mage armor", "magic missile", "protection from evil and good", "shield", "sleep", "thunderwave", "witch bolt"],
      2: ["alter self", "arcane lock", "blur", "cloud of daggers", "continual flame", "darkness", "darkvision", "enhance ability", "enlarge/reduce", "flaming sphere", "gust of wind", "hold person", "invisibility", "knock", "levitate", "magic weapon", "mirror image", "misty step", "scorching ray", "see invisibility", "shatter", "spider climb", "suggestion", "web"],
      3: ["animate dead", "blink", "clairvoyance", "counterspell", "dispel magic", "fireball", "fly", "gaseous form", "haste", "hypnotic pattern", "lightning bolt", "major image", "nondetection", "protection from energy", "slow", "vampiric touch", "water breathing"],
      4: ["banishment", "blight", "confusion", "conjure minor elementals", "dimension door", "fabricate", "fire shield", "greater invisibility", "ice storm", "phantasmal killer", "polymorph", "stone skin", "wall of fire"],
      5: ["animate objects", "bigby's hand", "cloudkill", "cone of cold", "conjure elemental", "hold monster", "legend lore", "passwall", "scrying", "telekinesis", "wall of force", "wall of stone"],
      6: ["chain lightning", "circle of death", "contingency", "disintegrate", "globe of invulnerability", "move earth", "programmed illusion", "sunbeam", "true seeing"],
      7: ["delayed blast fireball", "etherealness", "forcecage", "mirage arcane", "plane shift", "prismatic spray", "project image", "reverse gravity", "symbol", "teleport"],
      8: ["antimagic field", "clone", "control weather", "dominate monster", "feeblemind", "incendiary cloud", "maze", "mind blank", "power word stun", "sunburst"],
      9: ["astral projection", "foresight", "gate", "imprisonment", "meteor swarm", "power word kill", "prismatic wall", "psychic scream", "time stop", "true polymorph", "weird", "wish"],
    },
    paladin: {
      1: ["bless", "command", "compelled duel", "cure wounds", "detect evil and good", "detect magic", "divine favor", "heroism", "protection from evil and good", "shield of faith", "thunderous smite", "wrathful smite"],
      2: ["aid", "branding smite", "find steed", "lesser restoration", "magic weapon", "protection from poison", "zone of truth"],
      3: ["aura of vitality", "blinding smite", "crusader's mantle", "daylight", "dispel magic", "revivify", "spirit guardians"],
      4: ["banishment", "death ward", "find greater steed", "locate creature", "staggering smite"],
      5: ["banishing smite", "circle of power", "destructive wave", "dispel evil and good", "holy weapon", "raise dead"],
    },
    ranger: {
      1: ["alarm", "animal friendship", "cure wounds", "detect magic", "detect poison and disease", "ensnaring strike", "fog cloud", "goodberry", "hunter's mark", "longstrider", "speak with animals"],
      2: ["animal messenger", "barkskin", "darkvision", "find traps", "lesser restoration", "pass without trace", "protection from poison", "silence", "spike growth"],
      3: ["conjure animals", "daylight", "lightning arrow", "plant growth", "protection from energy", "speak with plants", "water breathing", "water walk", "wind wall"],
      4: ["conjure woodland beings", "freedom of movement", "grasping vine", "locate creature", "stone skin"],
      5: ["commune with nature", "conjure volley", "swift quiver", "tree stride"],
    },
    artificer: {
      cantrips: ["acid splash", "booming blade", "fire bolt", "guidance", "light", "mage hand", "message", "prestidigitation", "shocking grasp"],
      1: ["absorb elements", "alarm", "cure wounds", "detect magic", "disguise self", "expeditious retreat", "faerie fire", "false life", "feather fall", "grease", "identify", "longstrider", "sanctuary"],
      2: ["aid", "alter self", "arcane lock", "blur", "continual flame", "darkvision", "enhance ability", "enlarge/reduce", "heat metal", "invisibility", "lesser restoration", "levitate", "magic weapon", "protection from poison", "see invisibility", "web"],
      3: ["animate dead", "blink", "counterspell", "daylight", "dispel magic", "fly", "gaseous form", "glyph of warding", "hypnotic pattern", "protection from energy", "revivify", "water breathing"],
      4: ["banishment", "death ward", "fabricate", "freedom of movement", "greater invisibility", "polymorph", "stone skin"],
      5: ["animate objects", "create homunculus", "greater restoration", "hold monster", "wall of force", "wall of stone"],
    },
  };

  function titleCase(s) { return s.replace(/\b\w/g, (c) => c.toUpperCase()); }
  function byId(id) {
    const sp = SP[id];
    return sp ? Object.assign({}, sp, { n: titleCase(id) }) : null;
  }
  function forClass(klass, edition) {
    const l = CLASS_LISTS[klass] || {};
    return l;
  }
  function schoolName(code) { return S[code] || code; }
  function all() { return SP; }

  return { all, byId, forClass, schoolName, SCHOOLS };
})();
