// Webuntu OS — PDF Viewer (POST-52, Task 61)
// A real document viewer powered by pdf.js (3.11.174). It renders any valid
// PDF by opening it three ways:
//   • double-click a .pdf file in the File Manager (window.PDFViewer.openPath),
//   • the app's own Open dialog (scans the virtual FS for .pdf files),
//   • drag-and-drop a real PDF from the computer onto the window.
// The engine loads lazily on first use from esm.sh (main bundle) and a raw
// CDN classic script (worker) — the worker script runs as pdf.js's main-thread
// "fake worker", so no cross-origin Web Worker is needed. Features: thumbnail
// sidebar, page nav + jump, fit-width / fit-page / actual-size / zoom, search
// across pages, a selectable (invisible) text layer, status bar and graceful
// loading / error states.
// On first boot the module also seeds three sample PDFs into
// /home/user/Documents, generated by a tiny in-app PDF writer (uncompressed,
// ASCII-safe content streams + correct xref) so the viewer has something to
// open even with no network besides the two engine CDN files.

(function () {
  "use strict";

  function el(tag, cls, text) {
    const n = document.createElement(tag);
    if (cls) n.className = cls;
    if (text !== undefined) n.textContent = text;
    return n;
  }
  function baseName(path) {
    const p = String(path || "").split("/").filter(Boolean);
    return p.length ? p[p.length - 1] : (path || "");
  }
  function fmt(n) {
    return String(Math.round(n * 100) / 100);
  }

  // ---------------- Latin-1 <-> bytes (the virtual FS stores PDFs as text) --
  function latin1ToBytes(str) {
    const s = String(str || "");
    const bytes = new Uint8Array(s.length);
    for (let i = 0; i < s.length; i++) bytes[i] = s.charCodeAt(i) & 0xFF;
    return bytes;
  }
  function isPdfString(content) {
    return typeof content === "string" && /^%PDF-/i.test(content.trim());
  }
  function isPdfNode(node) {
    return !!node && node.type === "file" && /\.pdf$/i.test(node.name || "") && isPdfString(node.meta && node.meta.content);
  }

  // ---------------- tiny PDF writer (seeded sample documents) ---------------
  // Helvetica width table (per 1000 units) for approximate line wrapping.
  const WIDTHS = {
    " ":278,"!":278,'"':355,"#":556,"$":556,"%":889,"&":667,"'":191,"(":333,")":333,"*":389,
    "+":584,",":278,"-":333,".":278,"/":278,"0":556,"1":556,"2":556,"3":556,"4":556,"5":556,
    "6":556,"7":556,"8":556,"9":556,":":278,";":278,"<":584,"=":584,">":584,"?":556,"@":1015,
    "A":667,"B":667,"C":722,"D":722,"E":667,"F":611,"G":778,"H":722,"I":278,"J":500,"K":667,
    "L":556,"M":833,"N":722,"O":778,"P":667,"Q":778,"R":722,"S":667,"T":611,"U":722,"V":667,
    "W":944,"X":667,"Y":667,"Z":611,"[":278,"\\":278,"]":278,"^":469,"_":556,"`":333,
    "a":556,"b":556,"c":500,"d":556,"e":556,"f":278,"g":556,"h":556,"i":222,"j":222,"k":500,
    "l":222,"m":833,"n":556,"o":556,"p":556,"q":556,"r":333,"s":500,"t":278,"u":556,"v":500,
    "w":722,"x":500,"y":500,"z":500,"{":334,"|":260,"}":334,"~":584,"\u00b7":278,
  };
  function textWidth(s, fs) {
    let w = 0;
    for (const ch of String(s)) w += (WIDTHS[ch] != null ? WIDTHS[ch] : 556);
    return (w * fs) / 1000;
  }
  function escPdfText(s) {
    return String(s)
      .replace(/[^\x20-\x7e\xa0-\xff]/g, "?")
      .replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");
  }
  function wrapText(text, fs, maxW) {
    const words = String(text).split(/\s+/).filter(Boolean);
    const lines = [];
    let line = "";
    for (const w of words) {
      const test = line ? line + " " + w : w;
      if (!line || textWidth(test, fs) <= maxW) line = test;
      else { lines.push(line); line = w; }
    }
    if (line) lines.push(line);
    return lines;
  }
  function hexToOps(hex) {
    const m = /^#?([0-9a-f]{6})$/i.exec(String(hex || ""));
    if (!m) return "0.486 0.424 1";
    const n = parseInt(m[1], 16);
    return ((n >> 16) & 255) / 255 + " " + ((n >> 8) & 255) / 255 + " " + (n & 255) / 255;
  }

  const PDF_W = 612, PDF_H = 792, PDF_ML = 56, PDF_MR = 56, PDF_MT = 64, PDF_MB = 54, PDF_LW = PDF_W - PDF_ML - PDF_MR;
  const ACCENT = "#7c6cff", GRAY = "#7d8494";

  function blockHeight(b) {
    switch (b.t) {
      case "title": return 4 + 32 + 2;
      case "subtitle": return 19 + 2;
      case "h1": return 16 + 20 + 4;
      case "h2": return 10 + 17 + 2;
      case "p": return wrapText(b.text, 10.5, PDF_LW).length * 15.5 + 2;
      case "li": return wrapText(b.text, 10.5, PDF_LW - 18).length * 15.5 + 2;
      case "small": return wrapText(b.text, 8.5, PDF_LW).length * 12 + 2;
      case "rule": return 4 + 16;
      case "spacer": return b.h || 10;
    }
    return 10;
  }

  function blockOps(b, page) {
    const ops = page.ops;
    let y = page.y;
    const addText = (lines, font, fs, lh, colorOps, x) => {
      ops.push(colorOps + " rg");
      for (const ln of lines) {
        ops.push("BT " + font + " " + fs + " Tf 1 0 0 1 " + fmt(x) + " " + fmt(y) + " Tm (" + escPdfText(ln) + ") Tj ET");
        y -= lh;
      }
      page.y = y;
    };
    switch (b.t) {
      case "title": {
        y -= 6;
        addText(wrapText(b.text, 26, PDF_LW), "/F2", 26, 32, "0 0 0", PDF_ML);
        page.y = y - 2;
        break;
      }
      case "subtitle":
        addText([b.text], "/F1", 13, 19, hexToOps(b.color || ACCENT), PDF_ML);
        page.y = y - 4;
        break;
      case "h1":
        page.y = y - 16;
        addText(wrapText(b.text, 14.5, PDF_LW), "/F2", 14.5, 20, "0 0 0", PDF_ML);
        page.y = page.y - 4;
        break;
      case "h2":
        page.y = y - 10;
        addText(wrapText(b.text, 12, PDF_LW), "/F2", 12, 17, "0 0 0", PDF_ML);
        page.y = page.y - 2;
        break;
      case "p":
        addText(wrapText(b.text, 10.5, PDF_LW), "/F1", 10.5, 15.5, "0 0 0", PDF_ML);
        page.y = y - 2;
        break;
      case "li": {
        const wrapped = wrapText(b.text, 10.5, PDF_LW - 18);
        ops.push("0 0 0 rg");
        ops.push("BT /F1 10.5 Tf 1 0 0 1 " + fmt(PDF_ML) + " " + fmt(y) + " Tm (\u00b7) Tj ET");
        y -= 15.5;
        for (let i = 0; i < wrapped.length; i++) {
          ops.push("BT /F1 10.5 Tf 1 0 0 1 " + fmt(PDF_ML + 18) + " " + fmt(y) + " Tm (" + escPdfText(wrapped[i]) + ") Tj ET");
          y -= 15.5;
        }
        page.y = y - 2;
        break;
      }
      case "small":
        addText(wrapText(b.text, 8.5, PDF_LW), "/F1", 8.5, 12, hexToOps(b.color || GRAY), PDF_ML);
        page.y = y - 2;
        break;
      case "rule":
        ops.push(hexToOps(b.color || ACCENT) + " rg");
        ops.push(fmt(PDF_ML) + " " + fmt(y - 4) + " " + fmt(PDF_LW) + " 1.6 re f");
        page.y = y - 16;
        break;
      case "spacer":
        page.y = y - (b.h || 10);
        break;
    }
  }

  // doc: { title, author, pages: [ { blocks: [block...] } ] }
  function buildPdf(doc) {
    const rendered = [];      // { content } per page
    let cur = { y: PDF_H - PDF_MT, ops: [] };
    for (const pg of doc.pages || []) {
      if (cur.ops.length) { rendered.push(cur); cur = { y: PDF_H - PDF_MT, ops: [] }; }
      for (const b of pg.blocks || []) {
        if (b.t === "pagebreak") { if (cur.ops.length) rendered.push(cur); cur = { y: PDF_H - PDF_MT, ops: [] }; continue; }
        const h = blockHeight(b);
        if (cur.ops.length && cur.y - h < PDF_MB + 8) { rendered.push(cur); cur = { y: PDF_H - PDF_MT, ops: [] }; }
        blockOps(b, cur);
      }
    }
    if (cur.ops.length) rendered.push(cur);
    const N = rendered.length || 1;
    for (let i = 0; i < N; i++) {
      const footer = "Webuntu 12 \u00b7 Perch Mint";
      const num = "Page " + (i + 1) + " of " + N;
      const f = rendered[i].ops;
      f.push(hexToOps(GRAY) + " rg");
      f.push("BT /F1 8 Tf 1 0 0 1 " + fmt(PDF_ML) + " 30 Tm (" + escPdfText(footer) + ") Tj ET");
      f.push("BT /F1 8 Tf 1 0 0 1 " + fmt(PDF_W - PDF_MR - textWidth(num, 8)) + " 30 Tm (" + escPdfText(num) + ") Tj ET");
      rendered[i].content = f.join("\n") + "\n";
    }

    const chunks = [];
    let off = 0;
    const offsets = [0];
    function push(s) { chunks.push(s); off += s.length; }
    function obj(n, body) { offsets[n] = off; push(n + " 0 obj\n" + body + "\nendobj\n"); }

    push("%PDF-1.4\n%\u00e2\u00e3\u00cf\u00d3\n");
    obj(1, "<< /Type /Catalog /Pages 2 0 R >>");
    const kids = [];
    for (let i = 0; i < N; i++) kids.push((3 + i) + " 0 R");
    obj(2, "<< /Type /Pages /Kids [" + kids.join(" ") + "] /Count " + N + " >>");
    for (let i = 0; i < N; i++) {
      obj(3 + i, "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 " + PDF_W + " " + PDF_H + "] /Contents " + (3 + N + i) + " 0 R /Resources << /Font << /F1 " + (3 + 2 * N) + " 0 R /F2 " + (4 + 2 * N) + " 0 R >> >> >>");
    }
    for (let i = 0; i < N; i++) {
      const c = rendered[i].content;
      obj(3 + N + i, "<< /Length " + c.length + " >>\nstream\n" + c + "endstream");
    }
    const infoTitle = escPdfText((doc && doc.title) || "Webuntu document");
    const infoAuthor = escPdfText((doc && doc.author) || "Webuntu OS");
    obj(3 + 2 * N, "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>");
    obj(4 + 2 * N, "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>");
    obj(5 + 2 * N, "<< /Title (" + infoTitle + ") /Author (" + infoAuthor + ") /Producer (Webuntu 12 PDF Writer) /CreationDate (D:20260828120000Z) >>");

    const xrefStart = off;
    const total = 6 + 2 * N;
    let xref = "xref\n0 " + total + "\n0000000000 65535 f \n";
    for (let i = 1; i < total; i++) xref += String(offsets[i]).padStart(10, "0") + " 00000 n \n";
    push(xref);
    push("trailer\n<< /Size " + total + " /Root 1 0 R /Info " + (5 + 2 * N) + " 0 R >>\nstartxref\n" + xrefStart + "\n%%EOF\n");
    return chunks.join("");
  }

  // ---------------- sample documents (seeded into Documents) ----------------
  const SAMPLES = [
    {
      name: "Webuntu 12 Release Notes.pdf",
      title: "Webuntu 12 \u201cPerch Mint\u201d - Release Notes",
      pages: [
        {
          blocks: [
            { t: "title", text: "Webuntu 12 \"Perch Mint\" - Release Notes" },
            { t: "subtitle", text: "Rathji Desktop 5.2 \u00b7 Release 12.4.1 \u00b7 August 2026" },
            { t: "rule" },
            { t: "p", text: "Webuntu 12 \"Perch Mint\" is a fictional Debian-based Linux fork built on the Perch platform. It ships the Rathji Desktop environment, a full in-browser window manager, and a virtual filesystem that behaves like the real thing - folders, files, Trash, even a Software Center." },
            { t: "h1", text: "What's new in this release" },
            { t: "li", text: "A desktop shell with a themed Start menu, quick-launch taskbar and system tray (Wi-Fi, volume, clock, notifications)." },
            { t: "li", text: "A window manager with drag-to-move, resize, minimize, maximize, snap and touch gestures." },
            { t: "li", text: "A virtual filesystem with File Manager, Terminal, Trash and per-user home folders." },
            { t: "li", text: "Mail, Weather, PDF Viewer, Image Viewer, Notes, Text Editor, Minesweeper, System Monitor and more." },
            { t: "li", text: "The Board Game Network and Video Game Network folders, full of curated Perchance games." },
            { t: "li", text: "A notifications center, live chat with online presence, and a per-run wallpaper picker." },
            { t: "rule" },
            { t: "small", text: "This document was generated by the Webuntu PDF Writer and rendered by the built-in PDF Viewer app." },
          ],
        },
        {
          blocks: [
            { t: "h1", text: "Known issues" },
            { t: "li", text: "Online chat shows a single user until you save the generator to the Perchance network." },
            { t: "li", text: "The unsaved preview emulates the server, so shared state resets when the tab reloads." },
            { t: "li", text: "System Monitor's animation timer pauses while its window is hidden." },
            { t: "h1", text: "Built-in documents" },
            { t: "li", text: "Perch Desktop User Guide - everything from the Start menu to the Terminal." },
            { t: "li", text: "Keyboard Shortcuts - the full list of desktop and app shortcuts." },
            { t: "p", text: "Enjoy Perch Mint! We hope you like it." },
          ],
        },
      ],
    },
    {
      name: "Perch Desktop User Guide.pdf",
      title: "Perch Desktop User Guide",
      pages: [
        {
          blocks: [
            { t: "title", text: "Perch Desktop User Guide" },
            { t: "subtitle", text: "Webuntu 12 \u00b7 Perch Mint Edition" },
            { t: "rule" },
            { t: "h1", text: "Getting started" },
            { t: "p", text: "When you sign in you land on the desktop. The taskbar at the bottom holds the Start button, quick-launch icons for your favourite apps, and the system tray on the right. Right-click the desktop for a context menu with display settings, wallpaper and more." },
            { t: "h1", text: "The File Manager" },
            { t: "p", text: "Open the File Manager from the desktop, the Start menu or the taskbar. Double-click a folder to enter it, a file to open it in the right app (images open in the Image Viewer, PDFs in the PDF Viewer, text in the Text Editor), and press Delete to move an item to the Trash. You can switch between grid and list views, and every folder shows breadcrumb navigation." },
            { t: "h1", text: "The Terminal" },
            { t: "p", text: "The Terminal understands the classic commands: ls, cd, pwd, cat, mkdir, touch, rm, echo and more. It resolves paths against the same virtual filesystem the File Manager uses, so changes appear everywhere instantly." },
          ],
        },
        {
          blocks: [
            { t: "h1", text: "Notes" },
            { t: "p", text: "The Notes app keeps a stack of colourful sticky notes. Every note is saved to /home/user/Documents/Notes, so it survives reloads and shows up in the File Manager." },
            { t: "h1", text: "Control Center" },
            { t: "p", text: "Open Settings from the tray or Start menu to change the wallpaper, switch between dark and light themes, pick an accent colour, adjust text scaling, and toggle sounds, toasts and the boot screen." },
            { t: "h1", text: "The Software Center" },
            { t: "p", text: "The Software Center lists Perchance generators you can visit in the built-in browser. Community hubs like The Boardgame Network and The Video Game Network curate games for every taste, and planned Webuntu apps appear with a \"Coming in a later release\" badge until they ship." },
            { t: "h1", text: "Staying in touch" },
            { t: "p", text: "The tray bell collects notifications from the OS - new mail, chat messages and Minesweeper victories. Mail bundles a full inbox with contacts, folders and search, and the Perch Chat app shows who else is online." },
          ],
        },
        {
          blocks: [
            { t: "h1", text: "Keyboard shortcuts" },
            { t: "li", text: "Super + F opens the File Manager; Super + T the Terminal; Super + N Notes; Super + S Settings." },
            { t: "li", text: "Alt + Tab cycles windows; Super + Arrow keys snap or maximize the focused window." },
            { t: "li", text: "Inside the PDF Viewer: arrow keys flip pages, + / - zoom, 0 fits the page, F fits the width." },
            { t: "li", text: "Inside the Image Viewer: arrows move between images, + / - zoom, 0 fits." },
            { t: "rule" },
            { t: "small", text: "Full list: see the Keyboard Shortcuts document in Documents." },
          ],
        },
      ],
    },
    {
      name: "Keyboard Shortcuts.pdf",
      title: "Webuntu 12 Keyboard Shortcuts",
      pages: [
        {
          blocks: [
            { t: "title", text: "Keyboard Shortcuts" },
            { t: "subtitle", text: "Webuntu 12 \u00b7 Perch Mint" },
            { t: "rule" },
            { t: "h1", text: "Desktop & windows" },
            { t: "li", text: "Super + F - File Manager" },
            { t: "li", text: "Super + T - Terminal" },
            { t: "li", text: "Super + N - Notes" },
            { t: "li", text: "Super + S - Settings" },
            { t: "li", text: "Alt + Tab - cycle through windows" },
            { t: "li", text: "Super + Arrow keys - snap / maximize focused window" },
            { t: "li", text: "Alt + F4 - close focused window" },
            { t: "h1", text: "PDF Viewer" },
            { t: "li", text: "Arrow keys / Space / PageUp PageDown - flip pages" },
            { t: "li", text: "+ / - - zoom in / out" },
            { t: "li", text: "0 - fit page, F - fit width" },
            { t: "li", text: "Ctrl + F - focus search" },
            { t: "h1", text: "Image Viewer" },
            { t: "li", text: "Arrow keys - previous / next image" },
            { t: "li", text: "+ / - - zoom, 0 - fit" },
            { t: "h1", text: "File Manager" },
            { t: "li", text: "Delete - move to Trash" },
            { t: "li", text: "F2 - rename, Enter - open" },
            { t: "li", text: "Ctrl + A - select all in folder" },
          ],
        },
      ],
    },
  ];

  function ensureSamplePdfs() {
    try {
      const docs = window.FS && window.FS.resolve ? window.FS.resolve("/home/user/Documents") : null;
      if (!docs) return;
      for (const s of SAMPLES) {
        const content = buildPdf({ title: s.title, author: "Webuntu OS", pages: s.pages });
        const existing = docs.children.find((c) => c.name === s.name);
        if (existing) {
          if (existing.meta && existing.meta.content === content) continue;
          existing.meta.content = content;
          existing.meta.size = content.length;
          existing.meta.modified = Date.now();
          continue;
        }
        window.FS.create("/home/user/Documents", {
          type: "file", name: s.name, icon: "📕",
          meta: { content, size: content.length, modified: Date.now() },
        });
      }
    } catch (e) {
      console.warn("PDF sample seeding failed:", e);
    }
  }

  // ---------------- pdf.js engine (lazy, cached) ----------------------------
  let enginePromise = null;
  function ensureEngine() {
    if (!enginePromise) {
      enginePromise = (async () => {
        const mod = await import("https://esm.sh/pdfjs-dist@3.11.174");
        const pdfjs = mod.default;
        pdfjs.GlobalWorkerOptions.workerSrc = "https://cdn.jsdelivr.net/npm/pdfjs-dist@3.11.174/build/pdf.worker.min.js";
        return pdfjs;
      })();
      enginePromise.catch(() => { enginePromise = null; });
    }
    return enginePromise;
  }

  // ---------------- viewer instance ----------------------------------------
  function createViewer() {
    const inst = {
      root: el("div", "pv"),
      win: null,
      doc: null,
      page: 1,
      numPages: 0,
      name: null,
      path: null,
      cssScale: 1,
      dpr: 1,
      zoomMode: "fit-width",
      customScale: 1,
      renderTask: null,
      renderVer: 0,
      thumbToken: 0,
      disposed: false,
    };

    // ---- toolbar ----
    const bar = el("div", "pv-bar");
    const thumbsBtn = el("button", "set-btn pv-ico", "\u2630");
    thumbsBtn.type = "button"; thumbsBtn.title = "Toggle page thumbnails";
    const openBtn = el("button", "set-btn", "Open\u2026");
    openBtn.type = "button";
    const openWrap = el("div", "pv-openwrap");
    const openPanel = el("div", "pv-openpanel");
    openPanel.hidden = true;
    openWrap.append(openBtn, openPanel);

    const searchWrap = el("div", "pv-searchwrap");
    const searchInput = el("input", "set-input pv-search");
    searchInput.type = "text";
    searchInput.placeholder = "Search this document\u2026";
    searchInput.spellcheck = false;
    const searchRes = el("div", "pv-searchres");
    searchRes.hidden = true;
    searchWrap.append(searchInput, searchRes);

    const nav = el("div", "pv-nav");
    const prevBtn = el("button", "set-btn pv-ico", "\u2039");
    prevBtn.type = "button"; prevBtn.title = "Previous page";
    const jumpInput = el("input", "pv-jump");
    jumpInput.type = "number"; jumpInput.min = "1"; jumpInput.step = "1"; jumpInput.value = "1";
    const pageLabel = el("span", "pv-pagelabel", "/ 1");
    const nextBtn = el("button", "set-btn pv-ico", "\u203a");
    nextBtn.type = "button"; nextBtn.title = "Next page";
    nav.append(prevBtn, jumpInput, pageLabel, nextBtn);

    const zoom = el("div", "pv-zoom");
    const fitWBtn = el("button", "set-btn", "Fit width");
    fitWBtn.type = "button"; fitWBtn.title = "Fit page to window width";
    const fitPBtn = el("button", "set-btn", "Fit page");
    fitPBtn.type = "button"; fitPBtn.title = "Fit whole page in the window";
    const oneBtn = el("button", "set-btn", "1:1");
    oneBtn.type = "button"; oneBtn.title = "Actual size";
    const zoBtn = el("button", "set-btn pv-ico", "\u2212");
    zoBtn.type = "button"; zoBtn.title = "Zoom out";
    const zoomPct = el("span", "pv-zoompct", "100%");
    const ziBtn = el("button", "set-btn pv-ico", "\uff0b");
    ziBtn.type = "button"; ziBtn.title = "Zoom in";
    zoom.append(fitWBtn, fitPBtn, oneBtn, zoBtn, zoomPct, ziBtn);

    bar.append(thumbsBtn, openWrap, searchWrap, nav, zoom);

    // ---- body: thumbnails + stage ----
    const body = el("div", "pv-body");
    const thumbs = el("div", "pv-thumbs");
    thumbs.hidden = true;
    const stage = el("div", "pv-stage");
    const wrap = el("div", "pv-canvaswrap");
    const canvas = el("canvas", "pv-canvas");
    canvas.height = 2; canvas.width = 2;
    const textLayer = el("div", "pv-tl");
    wrap.append(canvas, textLayer);
    const empty = el("div", "pv-empty");
    const emptyIcon = el("div", "pv-empty-icon", "\ud83d\udcd5");
    const emptyHead = el("div", "pv-empty-head", "No document open");
    const emptyText = el("p", "muted", "Open a PDF from the File Manager, from the Open button, or drop a PDF file onto this window.");
    const emptyOpen = el("button", "set-btn", "Open a document\u2026");
    emptyOpen.type = "button";
    const emptySamples = el("div", "pv-samples");
    empty.append(emptyIcon, emptyHead, emptyText, emptyOpen, emptySamples);
    const loading = el("div", "pv-loading");
    loading.hidden = true;
    const loadText = el("span", "pv-loadtext", "Loading PDF engine\u2026");
    loading.appendChild(loadText);
    const error = el("div", "pv-error");
    error.hidden = true;
    const errText = el("div", "pv-errtext", "This document couldn't be loaded.");
    const errRetry = el("button", "set-btn", "Try again");
    errRetry.type = "button";
    error.append(errText, errRetry);
    const dropOverlay = el("div", "pv-drop", "Drop a PDF to open it");
    dropOverlay.hidden = true;
    stage.append(wrap, empty, loading, error, dropOverlay);
    body.append(thumbs, stage);

    // ---- status bar ----
    const status = el("div", "pv-status");
    const statusName = el("span", "pv-status-name", "PDF Viewer");
    const statusRight = el("span", "pv-status-right", "");
    status.append(statusName, statusRight);

    inst.root.append(bar, body, status);

    // ---- helpers ----
    function setLoading(txt, on) {
      loadText.textContent = txt;
      loading.hidden = !on;
      if (on) { empty.hidden = true; error.hidden = true; }
    }
    function setError(txt) {
      errText.textContent = txt || "This document couldn't be loaded.";
      error.hidden = false;
      empty.hidden = true;
      loading.hidden = true;
    }
    function setTitle() {
      const t = inst.name ? inst.name + " \u2014 PDF Viewer" : "PDF Viewer";
      if (inst.win) window.WM.setTitle(inst.win.id, t);
    }
    function updateStatus() {
      statusName.textContent = inst.name || "PDF Viewer";
      const z = Math.round(inst.cssScale * 100);
      statusRight.textContent = inst.doc
        ? "Page " + inst.page + " / " + inst.numPages + " \u00b7 " + Math.round(z) + "%"
        : "";
      jumpInput.value = inst.page || 1;
      jumpInput.max = String(inst.numPages || 1);
      pageLabel.textContent = "/ " + (inst.numPages || 1);
      zoomPct.textContent = Math.round(z) + "%";
      prevBtn.disabled = inst.page <= 1;
      nextBtn.disabled = inst.page >= inst.numPages;
    }
    function goPage(p) {
      if (!inst.doc) return;
      p = Math.max(1, Math.min(inst.numPages, Math.round(p || 1)));
      if (p === inst.page) return;
      inst.page = p;
      updateStatus();
      renderCurrent();
    }

    async function buildTextLayer(page, viewport, cssScale, dpr) {
      let tc;
      try { tc = await page.getTextContent(); } catch (e) { return; }
      textLayer.innerHTML = "";
      const frag = document.createDocumentFragment();
      for (const item of tc.items) {
        if (!item.str) continue;
        let pt;
        try { pt = viewport.convertToViewportPoint(item.transform[4], item.transform[5]); } catch (e) { continue; }
        const fs = Math.max(4, (item.height || 10) * cssScale);
        const s = el("span", "pv-tl-span");
        s.textContent = item.str;
        s.style.left = Math.round(pt[0] / dpr) + "px";
        s.style.top = Math.round(pt[1] / dpr - fs * 0.8) + "px";
        s.style.fontSize = fs + "px";
        frag.appendChild(s);
      }
      textLayer.appendChild(frag);
    }

    async function renderCurrent() {
      if (!inst.doc || inst.disposed) return;
      const ver = ++inst.renderVer;
      let page;
      try { page = await inst.doc.getPage(inst.page); } catch (e) { return; }
      if (ver !== inst.renderVer || inst.disposed) return;
      const base = page.getViewport({ scale: 1 });
      const stageW = Math.max(80, stage.clientWidth - 28);
      const stageH = Math.max(80, stage.clientHeight - 28);
      const pw = base.width, ph = base.height;
      let css;
      if (inst.zoomMode === "fit-width") css = stageW / pw;
      else if (inst.zoomMode === "fit-page") css = Math.min(stageW / pw, stageH / ph);
      else if (inst.zoomMode === "actual") css = 1;
      else css = inst.customScale;
      css = Math.max(0.05, Math.min(6, css));
      inst.cssScale = css;
      const dpr = Math.min(window.devicePixelRatio || 1, 2);
      inst.dpr = dpr;
      const vp = page.getViewport({ scale: css * dpr });
      canvas.width = Math.max(2, Math.floor(vp.width));
      canvas.height = Math.max(2, Math.floor(vp.height));
      const cssW = Math.max(2, Math.floor(vp.width / dpr));
      const cssH = Math.max(2, Math.floor(vp.height / dpr));
      canvas.style.width = cssW + "px";
      canvas.style.height = cssH + "px";
      wrap.style.width = cssW + "px";
      wrap.style.height = cssH + "px";
      if (inst.renderTask) { try { inst.renderTask.cancel(); } catch (e) {} inst.renderTask = null; }
      const ctx = canvas.getContext("2d");
      ctx.fillStyle = "#ffffff";
      ctx.fillRect(0, 0, canvas.width, canvas.height);
      const task = page.render({ canvasContext: ctx, viewport: vp });
      inst.renderTask = task;
      setLoading("Rendering page\u2026", true);
      try {
        await task.promise;
      } catch (e) {
        if (e && (e.name === "RenderingCancelledException" || e.name === "RenderingCancelled")) return;
      }
      if (ver !== inst.renderVer || inst.disposed) return;
      inst.renderTask = null;
      await buildTextLayer(page, vp, css, dpr);
      if (ver !== inst.renderVer || inst.disposed) return;
      loading.hidden = true;
      updateStatus();
      highlightThumb();
      renderCurrentThumb();
    }

    // Renders just the currently-viewed page's thumbnail (the loop in
    // renderThumbs skips it to avoid a same-page render conflict).
    function renderCurrentThumb() {
      const p = inst.page;
      const item = thumbs.children[p - 1];
      const c = item && item.querySelector("canvas");
      if (c) renderThumb(p, item, c, inst.thumbToken);
    }

    function renderThumb(p, item, c, tok) {
      return (async () => {
        if (inst.disposed || tok !== inst.thumbToken) return;
        let page;
        try { page = await inst.doc.getPage(p); } catch (e) { return; }
        if (tok !== inst.thumbToken || inst.disposed) return;
        const vp1 = page.getViewport({ scale: 1 });
        const ts = 132 / vp1.width;
        const vp = page.getViewport({ scale: ts });
        c.width = Math.floor(vp.width);
        c.height = Math.floor(vp.height);
        const ctx = c.getContext("2d");
        ctx.fillStyle = "#fff";
        ctx.fillRect(0, 0, c.width, c.height);
        try { await page.render({ canvasContext: ctx, viewport: vp }).promise; }
        catch (e) { if (e && (e.name === "RenderingCancelledException" || e.name === "RenderingCancelled")) return; }
        if (tok !== inst.thumbToken || inst.disposed) return;
        item.classList.toggle("pv-thumb-cur", p === inst.page);
      })();
    }

    async function renderThumbs() {
      const tok = ++inst.thumbToken;
      thumbs.innerHTML = "";
      if (!inst.doc) return;
      const n = Math.min(inst.numPages, 60);
      for (let p = 1; p <= n; p++) {
        if (tok !== inst.thumbToken || inst.disposed) return;
        const item = el("div", "pv-thumb");
        const c = el("canvas", "pv-thumb-canvas");
        const lab = el("div", "pv-thumb-num", String(p));
        item.append(c, lab);
        item.addEventListener("click", () => goPage(p));
        thumbs.appendChild(item);
        if (p !== inst.page) renderThumb(p, item, c, tok);
      }
      if (tok === inst.thumbToken && !inst.disposed) renderCurrentThumb();
    }
    function highlightThumb() {
      const items = thumbs.children;
      for (let i = 0; i < items.length; i++) items[i].classList.toggle("pv-thumb-cur", i + 1 === inst.page);
    }

    function renderOpenPanel() {
      openPanel.innerHTML = "";
      const files = scanPdfs();
      if (!files.length) {
        openPanel.appendChild(el("div", "pv-open-empty", "No PDF files found. Drop one onto the window to open it."));
        return;
      }
      openPanel.appendChild(el("div", "pv-open-head", "Open a PDF"));
      for (const f of files.slice(0, 40)) {
        const row = el("button", "pv-open-row");
        row.type = "button";
        row.appendChild(el("span", "pv-open-ico", "\ud83d\udcd5"));
        const box = el("span", "pv-open-box");
        box.appendChild(el("span", "pv-open-name", f.name));
        box.appendChild(el("span", "pv-open-path", f.path));
        row.appendChild(box);
        row.addEventListener("click", () => { openPanel.hidden = true; loadByFsPath(f.path); });
        openPanel.appendChild(row);
      }
    }

    function scanPdfs() {
      const out = [];
      if (!window.FS || !window.FS.root) return out;
      (function walk(node, path) {
        if (!node || node.type !== "folder") return;
        for (const c of node.children) {
          const p = path + "/" + c.name;
          if (c.type === "folder") {
            if (window.FS.isInTrash(p)) continue;
            walk(c, p);
          } else if (isPdfNode(c)) {
            out.push({ path: p, name: c.name });
          }
        }
      })(window.FS.root, "");
      out.sort((a, b) => a.path.localeCompare(b.path));
      return out;
    }

    // ---- loading a document ----
    async function load(src) {
      if (inst.disposed) return;
      if (inst.renderTask) { try { inst.renderTask.cancel(); } catch (e) {} inst.renderTask = null; }
      if (inst.doc) { try { inst.doc.destroy(); } catch (e) {} inst.doc = null; }
      ++inst.thumbToken;
      inst.page = 1;
      inst.numPages = 0;
      inst.zoomMode = "fit-width";
      inst.name = src.name || baseName(src.path) || "PDF document";
      inst.path = src.path || null;
      setTitle();
      textLayer.innerHTML = "";
      canvas.width = 2; canvas.height = 2;
      canvas.style.width = ""; canvas.style.height = "";
      wrap.style.width = ""; wrap.style.height = "";
      closeSearch();
      setLoading("Loading PDF engine\u2026", true);
      let pdfjs;
      try { pdfjs = await ensureEngine(); } catch (e) {
        setError("Couldn't load the PDF engine (check your connection) and retry.");
        return;
      }
      if (inst.disposed) return;
      setLoading("Loading document\u2026", true);
      let bytes;
      try {
        if (src.bytes && src.bytes instanceof Uint8Array) bytes = src.bytes;
        else if (src.file && typeof src.file.arrayBuffer === "function") bytes = new Uint8Array(await src.file.arrayBuffer());
        else if (typeof src.content === "string" && /^data:application\/pdf;base64,/i.test(src.content)) bytes = base64ToBytes(src.content.split(",")[1]);
        else if (typeof src.content === "string") bytes = latin1ToBytes(src.content);
        else { setError("That file isn't a readable PDF."); return; }
      } catch (e) {
        setError("That file couldn't be read.");
        return;
      }
      let doc;
      try {
        doc = await pdfjs.getDocument({ data: bytes, disableAutoFetch: true, stopAtErrors: true }).promise;
      } catch (e) {
        setError("This document couldn't be opened - it may be corrupt or not a PDF.");
        return;
      }
      if (inst.disposed) { try { doc.destroy(); } catch (e) {} return; }
      inst.doc = doc;
      inst.numPages = doc.numPages || 1;
      updateStatus();
      empty.hidden = true;
      loading.hidden = true;
      renderCurrent().then(() => renderThumbs());
    }

    function loadByFsPath(path) {
      const res = window.FSPath && window.FSPath.lookup ? window.FSPath.lookup(path) : null;
      if (!res || !res.ok || !isPdfNode(res.node)) return null;
      return load({ path: res.path, name: res.node.name, content: res.node.meta.content });
    }

    function base64ToBytes(b64) {
      const bin = atob(b64);
      const bytes = new Uint8Array(bin.length);
      for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
      return bytes;
    }

    // ---- search ----
    let searchTimer = null;
    function closeSearch() {
      if (searchTimer) { clearTimeout(searchTimer); searchTimer = null; }
      searchRes.hidden = true;
      searchRes.innerHTML = "";
    }
    function runSearch() {
      const q = searchInput.value.trim();
      if (!q || !inst.doc) { closeSearch(); return; }
      setLoading("Searching\u2026", true);
      (async () => {
        const results = [];
        const lq = q.toLowerCase();
        for (let p = 1; p <= inst.numPages && results.length < 60; p++) {
          let page, tc;
          try { page = await inst.doc.getPage(p); tc = await page.getTextContent(); } catch (e) { continue; }
          const full = tc.items.map((i) => i.str).join(" ").replace(/\s+/g, " ").trim();
          const lf = full.toLowerCase();
          let idx = lf.indexOf(lq);
          let count = 0;
          while (idx !== -1) { count++; idx = lf.indexOf(lq, idx + lq.length); }
          if (count) {
            const at = full.toLowerCase().indexOf(lq);
            const snippet = (at > 40 ? "\u2026" : "") + full.slice(Math.max(0, at - 40), at + 90) + (at + 90 < full.length ? "\u2026" : "");
            results.push({ page: p, count, snippet });
          }
        }
        loading.hidden = true;
        if (inst.disposed) return;
        searchRes.innerHTML = "";
        if (!results.length) {
          searchRes.appendChild(el("div", "pv-search-none", "No matches for \u201c" + q + "\u201d"));
        } else {
          const total = results.reduce((a, r) => a + r.count, 0);
          searchRes.appendChild(el("div", "pv-search-head", results.length + " page" + (results.length === 1 ? "" : "s") + " \u00b7 " + total + " match" + (total === 1 ? "" : "es")));
          for (const r of results) {
            const row = el("button", "pv-search-row");
            row.type = "button";
            row.appendChild(el("span", "pv-search-pg", "p." + r.page));
            row.appendChild(el("span", "pv-search-snip", r.snippet));
            row.addEventListener("click", () => { goPage(r.page); });
            searchRes.appendChild(row);
          }
        }
        searchRes.hidden = false;
      })();
    }

    // ---- events ----
    openBtn.addEventListener("click", () => {
      renderOpenPanel();
      openPanel.hidden = !openPanel.hidden;
    });
    document.addEventListener("click", (ev) => {
      if (!openWrap.contains(ev.target)) openPanel.hidden = true;
    });
    thumbsBtn.addEventListener("click", () => { thumbs.hidden = !thumbs.hidden; });
    prevBtn.addEventListener("click", () => goPage(inst.page - 1));
    nextBtn.addEventListener("click", () => goPage(inst.page + 1));
    jumpInput.addEventListener("keydown", (ev) => {
      if (ev.key === "Enter") { ev.preventDefault(); goPage(parseInt(jumpInput.value, 10) || 1); }
    });
    jumpInput.addEventListener("change", () => goPage(parseInt(jumpInput.value, 10) || 1));
    fitWBtn.addEventListener("click", () => { inst.zoomMode = "fit-width"; renderCurrent(); });
    fitPBtn.addEventListener("click", () => { inst.zoomMode = "fit-page"; renderCurrent(); });
    oneBtn.addEventListener("click", () => { inst.zoomMode = "actual"; renderCurrent(); });
    ziBtn.addEventListener("click", () => zoomBy(1.2));
    zoBtn.addEventListener("click", () => zoomBy(1 / 1.2));
    function zoomBy(f) {
      if (inst.zoomMode === "fit-width" || inst.zoomMode === "fit-page") inst.customScale = inst.cssScale;
      inst.zoomMode = "custom";
      inst.customScale = Math.max(0.05, Math.min(6, inst.customScale * f));
      renderCurrent();
    }
    errRetry.addEventListener("click", () => {
      if (inst.path) loadByFsPath(inst.path);
      else if (inst._lastSrc) load(inst._lastSrc);
    });
    emptyOpen.addEventListener("click", () => {
      renderOpenPanel();
      openPanel.hidden = false;
    });

    // sample shortcuts on the empty state
    function buildSamplesList() {
      emptySamples.innerHTML = "";
      const docs = window.FS && window.FS.resolve ? window.FS.resolve("/home/user/Documents") : null;
      if (!docs) return;
      const pdfs = docs.children.filter(isPdfNode);
      if (!pdfs.length) return;
      emptySamples.appendChild(el("div", "pv-samples-head", "Sample documents"));
      for (const f of pdfs) {
        const chip = el("button", "set-btn pv-sample-chip", "\ud83d\udcd5 " + f.name);
        chip.type = "button";
        chip.addEventListener("click", () => loadByFsPath(window.FS.getPath(f)));
        emptySamples.appendChild(chip);
      }
    }
    buildSamplesList();

    // resize → re-fit (debounced)
    let resizeTimer = null;
    window.addEventListener("resize", () => {
      if (!inst.doc) return;
      if (resizeTimer) clearTimeout(resizeTimer);
      resizeTimer = setTimeout(() => { if (inst.zoomMode === "fit-width" || inst.zoomMode === "fit-page") renderCurrent(); }, 150);
    });
    function stageResize() {
      if (inst.doc && (inst.zoomMode === "fit-width" || inst.zoomMode === "fit-page")) renderCurrent();
    }
    if (typeof ResizeObserver === "function") {
      try {
        new ResizeObserver(() => stageResize()).observe(stage);
      } catch (e) {}
    }

    // drag & drop a real PDF onto the window
    ["dragenter", "dragover"].forEach((evt) => {
      inst.root.addEventListener(evt, (e) => {
        e.preventDefault();
        if (e.dataTransfer && Array.from(e.dataTransfer.types).includes("Files")) dropOverlay.hidden = false;
      });
    });
    ["dragleave", "drop"].forEach((evt) => {
      inst.root.addEventListener(evt, (e) => { e.preventDefault(); dropOverlay.hidden = true; });
    });
    inst.root.addEventListener("drop", (e) => {
      e.preventDefault();
      dropOverlay.hidden = true;
      const f = e.dataTransfer && e.dataTransfer.files && e.dataTransfer.files[0];
      if (!f) return;
      if (!/\.pdf$/i.test(f.name) && !/application\/pdf/i.test(f.type || "")) {
        setError("\u201c" + f.name + "\u201d doesn't look like a PDF.");
        return;
      }
      inst._lastSrc = { file: f, name: f.name };
      load({ file: f, name: f.name });
    });

    // keyboard (routed via the shared document listener below)
    inst.onKey = function (ev) {
      if (ev.ctrlKey || ev.metaKey || ev.altKey) return;
      const ae = document.activeElement;
      const typing = ae && (ae.tagName === "INPUT" || ae.tagName === "TEXTAREA");
      if (ev.ctrlKey && (ev.key === "f" || ev.key === "F")) { ev.preventDefault(); searchInput.focus(); return; }
      if (typing) return;
      switch (ev.key) {
        case "ArrowLeft": case "PageUp": case "p": case "P": ev.preventDefault(); goPage(inst.page - 1); break;
        case "ArrowRight": case "PageDown": case " ": case "n": case "N": ev.preventDefault(); goPage(inst.page + 1); break;
        case "Home": ev.preventDefault(); goPage(1); break;
        case "End": ev.preventDefault(); goPage(inst.numPages); break;
        case "+": case "=": ev.preventDefault(); zoomBy(1.2); break;
        case "-": case "_": ev.preventDefault(); zoomBy(1 / 1.2); break;
        case "0": ev.preventDefault(); inst.zoomMode = "fit-page"; renderCurrent(); break;
        case "f": case "F": ev.preventDefault(); inst.zoomMode = "fit-width"; renderCurrent(); break;
        default: return;
      }
    };

    searchInput.addEventListener("input", () => {
      if (searchTimer) clearTimeout(searchTimer);
      searchTimer = setTimeout(runSearch, 350);
    });
    searchInput.addEventListener("keydown", (ev) => {
      if (ev.key === "Enter") { ev.preventDefault(); runSearch(); }
      if (ev.key === "Escape") { ev.preventDefault(); closeSearch(); searchInput.blur(); }
    });
    document.addEventListener("click", (ev) => {
      if (!searchWrap.contains(ev.target)) searchRes.hidden = true;
    });

    inst.dispose = function () {
      inst.disposed = true;
      if (inst.renderTask) { try { inst.renderTask.cancel(); } catch (e) {} inst.renderTask = null; }
      if (inst.doc) { try { inst.doc.destroy(); } catch (e) {} inst.doc = null; }
      ++inst.thumbToken;
      if (inst.win) instances.delete(inst.win.id);
    };
    inst.load = load;

    // resolve the owning WM window shortly after mount
    setTimeout(() => {
      const winEl = inst.root.closest(".window");
      const win = (window.WM.windows || []).find((x) => x.el === winEl);
      if (win) {
        inst.win = win;
        instances.set(win.id, inst);
        setTitle();
        updateStatus();
      }
    }, 80);

    updateStatus();
    return inst;
  }

  const instances = new Map();
  function onDocKey(ev) {
    const w = window.WM && window.WM.getFocused && window.WM.getFocused();
    if (!w || w.closed) return;
    for (const [id, inst] of instances) {
      if (inst.win && inst.win.id === id && inst.win.el === w.el) {
        if (inst.onKey) inst.onKey(ev);
        return;
      }
    }
  }
  document.addEventListener("keydown", onDocKey);

  // ---------------- public API ---------------------------------------------
  let pendingOpen = null;

  function openPath(path) {
    const res = window.FSPath && window.FSPath.lookup ? window.FSPath.lookup(path) : null;
    if (!res || !res.ok || !isPdfNode(res.node)) return null;
    const src = { path: res.path, name: res.node.name, content: res.node.meta.content };
    pendingOpen = src;
    const existing = window.WM.findByAppId("pdf-viewer");
    if (existing && !existing.closed) {
      window.WM.focus(existing.id);
      const inst = instances.get(existing.id);
      if (inst) inst.load(src);
      return existing;
    }
    return window.Apps.launch("pdf-viewer");
  }

  function openBytes(name, bytes) {
    pendingOpen = { name: name || "document.pdf", bytes };
    const existing = window.WM.findByAppId("pdf-viewer");
    if (existing && !existing.closed) {
      window.WM.focus(existing.id);
      const inst = instances.get(existing.id);
      if (inst) inst.load({ name: name || "document.pdf", bytes });
      return existing;
    }
    return window.Apps.launch("pdf-viewer");
  }

  window.PDFViewer = {
    openPath,
    openBytes,
    buildPdf,
    get samples() { return SAMPLES.map((s) => s.name); },
  };

  window.AppContent = window.AppContent || {};
  window.AppContent["pdf-viewer"] = function () {
    const inst = createViewer();
    const open = pendingOpen;
    pendingOpen = null;
    if (open) setTimeout(() => inst.load(open), 80);
    return { content: inst.root, w: 860, h: 620, minW: 560, minH: 400, onCloseRequest: () => inst.dispose() };
  };

  ensureSamplePdfs();
})();
