// src/framework/assetLibrary.js — the shipped Flexible Asset template library
// (roadmap tasks 12–13).
//
// These are the templates IT-U ships out of the box: Applications, Licensing
// and Virtualization (named by the roadmap) plus the service templates the
// later phases build on (email, backup, network, security, remote access, file
// sharing, printing, vendor, voice/PBX and internet/WAN circuit). They live in
// the ONE global library document (see ./flexibleTypes.js), so a house standard
// is defined once and shared across every client's documentation set; the
// provider can edit a builtin in place, clone it and adapt the clone, or reset
// it to the shipped definition.
//
// Field keys are EXPLICIT and stable so records, exports and tests can rely on
// them even as labels are tuned.

import { ASSET_TYPE_SCHEMA, normalizeField } from "./flexible.js";
import { tierOptions, osOptions } from "./workforce.js";
import { platformOptions, deploymentOptions, authOptions, archiveOptions, migrationOptions } from "./email.js";
import { architectureOptions, backupDeploymentOptions, destinationOptions, scheduleOptions, testResultOptions } from "./backup.js";
import { wanServiceKindOptions, circuitTypeOptions, lanArchitectureOptions, cablingOptions, wirelessStandardOptions, wirelessSecurityOptions, wirelessAuthOptions, bandOptions } from "./network.js";
import { securityPlatformTypeOptions, securityDeploymentOptions, remoteAccessMethodOptions, virtualizationPlatformOptions, fileStorageTypeOptions, fileSharingProtocolOptions, printingDeviceTypeOptions, printServiceModelOptions } from "./serviceAssets.js";
import { voicePlatformOptions, voiceDeploymentOptions, voiceTrunkTypeOptions, voiceSipTransportOptions, voiceCodecOptions, voiceServiceOptions, portingStatusOptions, emergencyServiceOptions } from "./voice.js";
import { accessTechnologyOptions, circuitSourcingOptions, serviceDefinitionOptions, circuitSlaTargetOptions, cpeRoleOptions } from "./circuit.js";
import { billingCycleOptions, prorationPolicyOptions, dataCapPeriodOptions, overageTreatmentOptions } from "./billing.js";

function tpl(id, name, category, icon, description, references, fields) {
  return {
    schema: ASSET_TYPE_SCHEMA,
    id,
    name,
    description,
    category,
    icon,
    fields: fields.map((f) => normalizeField(f)),
    references,
    builtin: true,
    customized: false,
    shipped: true,
    createdAt: 0,
    updatedAt: 0,
    createdBy: "system",
  };
}

export const BUILTIN_ASSET_TYPES = [
  tpl(
    "atype-applications",
    "Applications",
    "applications",
    "box",
    "A business, cloud, internal or supporting application. Relates to the configurations it runs on, its owner, its credentials and its licence.",
    ["configurations", "contacts", "passwords", "flexibleAssets", "documents"],
    [
      { key: "applicationType", label: "Application type", type: "select", required: true, options: [
        { id: "line-of-business", label: "Line-of-business" },
        { id: "server", label: "Server application" },
        { id: "cloud", label: "Cloud / SaaS" },
        { id: "internal", label: "Internal tool" },
        { id: "security", label: "Security application" },
        { id: "remote-access", label: "Remote access" },
        { id: "intranet", label: "Intranet" },
        { id: "other", label: "Other" },
      ] },
      { key: "vendor", label: "Vendor / publisher", type: "text" },
      { key: "vendorRecord", label: "Vendor record", type: "record", of: "flexibleAssets", help: "Link the Vendor template record that supplies this application." },
      { key: "version", label: "Version", type: "text" },
      { key: "environment", label: "Environment", type: "select", options: [
        { id: "production", label: "Production" },
        { id: "staging", label: "Staging" },
        { id: "test", label: "Test / UAT" },
        { id: "training", label: "Training" },
        { id: "development", label: "Development" },
        { id: "retired", label: "Retired" },
      ] },
      { key: "url", label: "URL", type: "url" },
      { key: "supportUrl", label: "Vendor support URL", type: "url" },
      { key: "licenceCount", label: "Licensed seats", type: "number" },
      { key: "database", label: "Database", type: "text" },
      { key: "criticality", label: "Criticality", type: "select", options: [
        { id: "critical", label: "Critical" },
        { id: "important", label: "Important" },
        { id: "standard", label: "Standard" },
      ] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
  ),
  tpl(
    "atype-licences",
    "Licensing & subscriptions",
    "commercial",
    "clipboard",
    "A software licence, subscription or entitlement — what it covers, how many seats, when it renews and who to contact.",
    ["flexibleAssets", "contacts", "documents"],
    [
      { key: "product", label: "Product", type: "text", required: true },
      { key: "vendor", label: "Vendor", type: "text" },
      { key: "licenceType", label: "Licence type", type: "select", required: true, options: [
        { id: "perpetual", label: "Perpetual" },
        { id: "subscription", label: "Subscription" },
        { id: "saas", label: "SaaS" },
        { id: "volume", label: "Volume / enterprise agreement" },
        { id: "oem", label: "OEM" },
        { id: "open-source", label: "Open source (supported)" },
        { id: "other", label: "Other" },
      ] },
      { key: "quantity", label: "Quantity / seats", type: "number" },
      { key: "licenceKey", label: "Licence key / reference", type: "text" },
      { key: "purchaseDate", label: "Purchase date", type: "date" },
      { key: "expiryDate", label: "Renewal / expiry date", type: "date", expiry: true, help: "Drives the renewals board in the Assets station." },
      { key: "startDate", label: "Subscription start date", type: "date" },
      { key: "billingCycle", label: "Billing cycle", type: "select", options: [
        { id: "monthly", label: "Monthly" },
        { id: "quarterly", label: "Quarterly" },
        { id: "annual", label: "Annual" },
        { id: "multi-year", label: "Multi-year" },
        { id: "perpetual", label: "Perpetual / one-off" },
        { id: "other", label: "Other" },
      ] },
      { key: "accountNumber", label: "Vendor account number", type: "text" },
      { key: "renewalAlertDays", label: "Alert days before renewal", type: "number", placeholder: "60", help: "Overrides the default renewal warning window for this record." },
      { key: "annualCost", label: "Annual cost", type: "number" },
      { key: "currency", label: "Currency", type: "text", placeholder: "e.g. GBP" },
      { key: "autoRenew", label: "Auto-renews", type: "checkbox" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
  ),
  tpl(
    "atype-virtualization",
    "Virtualization",
    "infrastructure",
    "layers",
    "A virtualization platform or cluster hosting the client's virtual servers — the platform and version, its hosts and datastores, HA and DR posture and licensing — related to the hosts it runs on, the applications and virtual servers it carries, and its credentials and documentation.",
    ["configurations", "contacts", "passwords", "flexibleAssets", "documents"],
    [
      { key: "platform", label: "Platform", type: "select", required: true, options: virtualizationPlatformOptions(), help: "VMware, Hyper-V, Proxmox and the other hypervisors the provider supports." },
      { key: "version", label: "Version", type: "text" },
      { key: "clusterName", label: "Cluster / host group", type: "text" },
      { key: "hostCount", label: "Host count", type: "number" },
      { key: "datastores", label: "Datastores & storage", type: "textarea", help: "The datastores the cluster presents and where they live, one per line." },
      { key: "haEnabled", label: "High availability enabled", type: "checkbox" },
      { key: "licenceTier", label: "Licence tier", type: "text" },
      { key: "managementUrl", label: "Management URL", type: "url" },
      { key: "drNotes", label: "Disaster-recovery notes", type: "textarea", help: "How the virtual estate is recovered — replication, DR site, failover order." },
      { key: "adminCredential", label: "Administrator credential", type: "record", of: "passwords", help: "The credential that administers the hypervisor or cluster." },
      { key: "vendorRecord", label: "Vendor record", type: "record", of: "flexibleAssets", help: "The Vendor record for the virtualization platform." },
      { key: "licenceRecord", label: "Licence record", type: "record", of: "flexibleAssets", help: "The Licensing record covering the platform." },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
  ),
  tpl(
    "atype-email-system",
    "Email system",
    "applications",
    "chat",
    "The client's email infrastructure as a structured service — platform and deployment, tenant, domains, mail flow, authentication posture and archiving — related to the configurations, applications, documents, domains, passwords and people it touches.",
    ["configurations", "contacts", "passwords", "flexibleAssets", "documents", "domains"],
    [
      { key: "platform", label: "Platform", type: "select", required: true, options: platformOptions() },
      { key: "deployment", label: "Deployment model", type: "select", required: true, options: deploymentOptions(), help: "Where the mailboxes actually live: cloud, hybrid, on-premises or hosted." },
      { key: "tenant", label: "Tenant / account", type: "text", help: "The provider's tenant or account identifier." },
      { key: "primaryDomain", label: "Primary domain", type: "text", placeholder: "example.com" },
      { key: "acceptedDomains", label: "Accepted domains", type: "textarea", help: "Every other domain the tenant accepts mail for, one per line." },
      { key: "mailboxCount", label: "Mailboxes", type: "number" },
      { key: "licensedSeats", label: "Licensed seats", type: "number" },
      { key: "mailFlow", label: "Mail flow / connectors", type: "textarea", help: "How mail enters and leaves — MX direction, smart hosts, hybrid connectors, relay rules." },
      { key: "mxRecord", label: "MX record", type: "text", placeholder: "e.g. example-com.mail.protection.outlook.com" },
      { key: "authentication", label: "Email authentication", type: "multiselect", options: authOptions(), help: "The anti-spoofing mechanisms configured for the domain(s)." },
      { key: "spamFiltering", label: "Spam & malware filtering", type: "text", help: "The filtering service in front of the mailboxes, if any." },
      { key: "archiving", label: "Archiving / journaling", type: "select", options: archiveOptions() },
      { key: "distributionLists", label: "Distribution lists & shared mailboxes", type: "textarea", help: "Shared mailboxes, groups and lists users rely on, one per line." },
      { key: "migrationState", label: "Migration state", type: "select", options: migrationOptions() },
      { key: "adminUrl", label: "Admin centre URL", type: "url" },
      { key: "supportUrl", label: "Support portal", type: "url" },
      { key: "mailHostRecord", label: "Mail host configuration", type: "record", of: "configurations", help: "The server or appliance that hosts or relays the mail." },
      { key: "mailApplication", label: "Mail application", type: "record", of: "flexibleAssets", help: "The Application record for the mail platform, if one is documented." },
      { key: "domainRecord", label: "Primary domain record", type: "record", of: "domains", help: "The Domain tracker record for the primary mail domain." },
      { key: "adminCredential", label: "Administrator credential", type: "record", of: "passwords", help: "The credential that administers the mail service." },
      { key: "supportVendor", label: "Vendor record", type: "record", of: "flexibleAssets", help: "The Vendor record for the mail provider." },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
  ),
  tpl(
    "atype-backup-service",
    "Backup service",
    "infrastructure",
    "database",
    "The client's backup arrangement as a structured service — what it protects, the architecture and deployment, where the copies land, the schedule and retention, and whether recoverability has actually been tested — related to the configurations it protects, its applications and storage, its procedures and recovery documents, and its reference checklists.",
    ["configurations", "contacts", "passwords", "flexibleAssets", "documents", "checklists"],
    [
      { key: "product", label: "Product", type: "text", required: true },
      { key: "provider", label: "Provider", type: "text" },
      { key: "architecture", label: "Architecture", type: "select", required: true, options: architectureOptions(), help: "What the backup actually captures." },
      { key: "deploymentModel", label: "Deployment model", type: "select", options: backupDeploymentOptions(), help: "How the backup reaches the data: agent, agentless, appliance or cloud-managed." },
      { key: "destinations", label: "Destinations", type: "multiselect", options: destinationOptions(), help: "Every place a copy lands — local disk, NAS/SAN, tape, cloud, offsite vault or a secondary site." },
      { key: "schedule", label: "Schedule", type: "select", options: scheduleOptions() },
      { key: "scheduleDetail", label: "Schedule detail", type: "text", placeholder: "e.g. full Sun 22:00, incremental nightly" },
      { key: "rpo", label: "Recovery point objective (RPO)", type: "text", placeholder: "e.g. 4 hours" },
      { key: "rto", label: "Recovery time objective (RTO)", type: "text", placeholder: "e.g. 8 hours" },
      { key: "retention", label: "Retention", type: "text", placeholder: "e.g. 30 daily, 12 monthly" },
      { key: "encryption", label: "Encrypted at rest & in transit", type: "checkbox" },
      { key: "immutability", label: "Immutable / ransomware-protected copies", type: "checkbox" },
      { key: "offsite", label: "Off-site copy", type: "checkbox" },
      { key: "protectedSystems", label: "Protected systems", type: "textarea", help: "What is in scope — servers, workstations, mailboxes, databases, SaaS data — one per line if not linked as records." },
      { key: "dataVolume", label: "Protected data volume", type: "text", placeholder: "e.g. 4.2 TB" },
      { key: "lastRestoreTest", label: "Last restore test", type: "date" },
      { key: "lastRestoreResult", label: "Restore test result", type: "select", options: testResultOptions() },
      { key: "businessRules", label: "Client business rules", type: "textarea", help: "The client-specific rules that govern backups — retention obligations, protected data, recovery priorities and exclusions." },
      { key: "procedureNotes", label: "Backup procedure notes", type: "textarea", help: "How the backup is run, monitored and alerted on day to day." },
      { key: "recoveryNotes", label: "Recovery notes", type: "textarea", help: "How a restore is performed and who authorises it." },
      { key: "managementUrl", label: "Management console URL", type: "url" },
      { key: "supportUrl", label: "Support portal", type: "url" },
      { key: "backupApplication", label: "Backup application", type: "record", of: "flexibleAssets", help: "The Application record for the backup platform, if documented." },
      { key: "backupHost", label: "Backup host / appliance", type: "record", of: "configurations", help: "The server or appliance that runs the backup." },
      { key: "backupStorageRecord", label: "Backup storage", type: "record", of: "flexibleAssets", help: "The file-sharing / storage record the copies land on." },
      { key: "vendorRecord", label: "Vendor record", type: "record", of: "flexibleAssets", help: "The Vendor record for the backup provider." },
      { key: "adminCredential", label: "Administrator credential", type: "record", of: "passwords" },
      { key: "recoveryDocument", label: "Recovery document", type: "record", of: "documents" },
      { key: "procedureDocument", label: "Procedure document", type: "record", of: "documents" },
      { key: "referenceChecklist", label: "Reference checklist", type: "record", of: "checklists", help: "The restore / recovery checklist used when a restore is needed." },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
  ),
  tpl(
    "atype-wan-service",
    "Internet / WAN service",
    "connectivity",
    "rocket",
    "The client's internet/WAN service as a structured record — carrier and service kind, the circuits and how they aggregate, public IP addressing, DNS and SLA — related to the edge firewalls and security that guard it and the LANs it feeds.",
    ["configurations", "contacts", "flexibleAssets", "documents"],
    [
      { key: "carrier", label: "Carrier / ISP", type: "text", required: true },
      { key: "serviceKind", label: "Service kind", type: "select", required: true, options: wanServiceKindOptions(), help: "Primary, failover, MPLS, SD-WAN and so on." },
      { key: "accountNumber", label: "Account number", type: "text" },
      { key: "circuitType", label: "Circuit type", type: "select", options: circuitTypeOptions() },
      { key: "circuitIds", label: "Circuit IDs & aggregation", type: "textarea", help: "Each circuit's ID and how the circuits are aggregated or load-balanced, one per line." },
      { key: "aggregated", label: "Circuits aggregated / bonded", type: "checkbox" },
      { key: "failover", label: "Secondary / failover circuit", type: "checkbox" },
      { key: "addressScheme", label: "Public IP addressing", type: "textarea", help: "The public IPs, ranges or blocks assigned by the carrier." },
      { key: "ipv4Range", label: "IPv4 range", type: "text" },
      { key: "ipv6Range", label: "IPv6 range", type: "text" },
      { key: "dnsServers", label: "Upstream DNS", type: "textarea" },
      { key: "bandwidthDown", label: "Download (Mbps)", type: "number" },
      { key: "bandwidthUp", label: "Upload (Mbps)", type: "number" },
      { key: "contention", label: "Contention / CIR", type: "text" },
      { key: "sla", label: "SLA / availability target", type: "text" },
      { key: "staticIpCount", label: "Static IP count", type: "number" },
      { key: "contractEndDate", label: "Contract end date", type: "date", expiry: true },
      { key: "monthlyCost", label: "Monthly cost", type: "number" },
      { key: "currency", label: "Currency", type: "text", placeholder: "e.g. GBP" },
      { key: "supportPhone", label: "Support phone", type: "phone" },
      { key: "supportUrl", label: "Support portal", type: "url" },
      { key: "firewallRecord", label: "Edge firewall", type: "record", of: "configurations" },
      { key: "securityRecord", label: "Security platform", type: "record", of: "flexibleAssets" },
      { key: "vendorRecord", label: "Vendor record", type: "record", of: "flexibleAssets" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
  ),
  tpl(
    "atype-lan",
    "LAN",
    "connectivity",
    "server",
    "The client's local network as a structured record — architecture, VLANs and subnets, IP addressing, internal DNS, VPN network details, cabling and server topology — related to the switches and servers that make it up and the wireless networks it serves.",
    ["configurations", "contacts", "flexibleAssets", "documents"],
    [
      { key: "architecture", label: "Architecture", type: "select", required: true, options: lanArchitectureOptions(), help: "Flat, VLAN-segmented, routed core, spine-leaf and so on." },
      { key: "vlanCount", label: "VLAN count", type: "number" },
      { key: "vlans", label: "VLANs & purposes", type: "textarea", help: "Each VLAN's ID and what it is for, one per line." },
      { key: "subnets", label: "Subnets", type: "textarea", help: "Each subnet's address range and purpose, one per line." },
      { key: "addressing", label: "IP addressing scheme", type: "textarea", help: "How addressing is allocated — DHCP ranges, static ranges, reservations." },
      { key: "dhcpScope", label: "DHCP scope", type: "text" },
      { key: "internalDns", label: "Internal DNS", type: "textarea", help: "The internal DNS servers and any zones they host." },
      { key: "dnsDomain", label: "Internal DNS domain", type: "text", placeholder: "e.g. corp.example.com" },
      { key: "vpnNetwork", label: "VPN network details", type: "textarea", help: "The VPN address pools, subnets and remote-access network details." },
      { key: "cabling", label: "Cabling", type: "select", options: cablingOptions() },
      { key: "serverTopology", label: "Server topology", type: "textarea", help: "How the servers sit on the LAN — subnets, tiers and links." },
      { key: "coreSwitch", label: "Core switch", type: "record", of: "configurations" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
  ),
  tpl(
    "atype-wireless",
    "Wireless",
    "connectivity",
    "wifi",
    "The client's wireless network as a structured record — SSIDs, security and authentication, controller and access points, bands and guest access — related to the access-point configurations it runs on and the LAN it serves.",
    ["configurations", "contacts", "flexibleAssets", "documents"],
    [
      { key: "ssids", label: "SSIDs", type: "textarea", required: true, help: "Every SSID the wireless network broadcasts, one per line." },
      { key: "standard", label: "Wireless standard", type: "select", options: wirelessStandardOptions() },
      { key: "securityMode", label: "Security mode", type: "select", required: true, options: wirelessSecurityOptions() },
      { key: "authentication", label: "Authentication", type: "select", options: wirelessAuthOptions() },
      { key: "controller", label: "Controller / management", type: "text", help: "The wireless controller or cloud management platform." },
      { key: "apCount", label: "Access points", type: "number" },
      { key: "bands", label: "Bands", type: "multiselect", options: bandOptions() },
      { key: "guestNetwork", label: "Guest network", type: "checkbox" },
      { key: "radiusServer", label: "RADIUS server", type: "text" },
      { key: "coverageNotes", label: "Coverage notes", type: "textarea", help: "Site coverage, dead spots, roaming notes." },
      { key: "securityRecord", label: "Security platform", type: "record", of: "flexibleAssets" },
      { key: "lanRecord", label: "LAN record", type: "record", of: "flexibleAssets" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
  ),
  tpl(
    "atype-security-platform",
    "Security platform",
    "security",
    "shield",
    "A security platform protecting the client — endpoint/EDR, antivirus, email and web filtering, firewalls and VPN security, SIEM or vulnerability management — its deployment and managed services, the scope it protects and its licensing — related to the configurations, remote access, wireless, WAN and email it protects, plus its vendor, credentials and documentation.",
    ["configurations", "contacts", "passwords", "flexibleAssets", "documents"],
    [
      { key: "product", label: "Product", type: "text", required: true },
      { key: "vendor", label: "Vendor", type: "text" },
      { key: "vendorRecord", label: "Vendor record", type: "record", of: "flexibleAssets", help: "The Vendor record that supplies the platform." },
      { key: "platformType", label: "Platform type", type: "select", required: true, options: securityPlatformTypeOptions(), help: "What the platform protects — endpoint, email, web, network, identity or logging." },
      { key: "deploymentModel", label: "Deployment model", type: "select", options: securityDeploymentOptions(), help: "Cloud, on-premises, provider-managed or hybrid." },
      { key: "services", label: "Managed services", type: "textarea", help: "The services the platform or provider runs — monitoring, alert triage, response, patching — one per line." },
      { key: "coverage", label: "Protected scope", type: "textarea", help: "The systems, sites and users the platform covers." },
      { key: "seats", label: "Seats / endpoints", type: "number" },
      { key: "managementUrl", label: "Management console URL", type: "url" },
      { key: "supportUrl", label: "Support portal", type: "url" },
      { key: "adminCredential", label: "Administrator credential", type: "record", of: "passwords", help: "The credential that administers the platform." },
      { key: "expiryDate", label: "Renewal / expiry date", type: "date", expiry: true, help: "Drives the renewals board in the Assets station." },
      { key: "licenceRecord", label: "Licence record", type: "record", of: "flexibleAssets", help: "The Licensing record covering the platform." },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
  ),
  tpl(
    "atype-remote-access",
    "Remote access",
    "security",
    "eye",
    "How the provider and users reach the client's environment remotely — VPN, webmail and remote-support systems, their endpoints and protocols, MFA and split-tunnel posture — related to the configurations and security behind them, their credentials, applications and documentation.",
    ["configurations", "contacts", "passwords", "flexibleAssets", "documents"],
    [
      { key: "product", label: "Product", type: "text" },
      { key: "method", label: "Method", type: "select", required: true, options: remoteAccessMethodOptions(), help: "The access method — VPN, gateway, agent, webmail or zero-trust." },
      { key: "endpoint", label: "Endpoint / URL", type: "text" },
      { key: "protocol", label: "Protocol", type: "text", placeholder: "e.g. SSL/TLS, IPsec, RDP" },
      { key: "port", label: "Port(s)", type: "text" },
      { key: "clientSoftware", label: "Client software", type: "text", help: "The client or agent users install to connect." },
      { key: "mfa", label: "MFA enforced", type: "checkbox" },
      { key: "splitTunnel", label: "Split tunnel", type: "checkbox" },
      { key: "concurrentUsers", label: "Concurrent users", type: "number" },
      { key: "securityRecord", label: "Security platform", type: "record", of: "flexibleAssets", help: "The security platform protecting remote access." },
      { key: "vpnGatewayRecord", label: "VPN gateway / host", type: "record", of: "configurations", help: "The appliance or server terminating the remote connection." },
      { key: "adminCredential", label: "Administrator credential", type: "record", of: "passwords" },
      { key: "applicationRecord", label: "Application record", type: "record", of: "flexibleAssets", help: "The Application record for the remote-access platform, if documented." },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
  ),
  tpl(
    "atype-file-sharing",
    "File sharing & storage",
    "infrastructure",
    "folder",
    "A shared file-storage arrangement — on-premises file server, NAS/SAN/DAS, cloud file service or hybrid — its protocol and capacity, the folders it shares and its access model — related to the configurations and applications behind it, its security, backup, credentials, documentation and the people who use it.",
    ["configurations", "contacts", "passwords", "flexibleAssets", "documents"],
    [
      { key: "product", label: "Product", type: "text" },
      { key: "storageType", label: "Storage type", type: "select", required: true, options: fileStorageTypeOptions(), help: "Where the files actually live." },
      { key: "protocol", label: "Protocol", type: "select", options: fileSharingProtocolOptions() },
      { key: "capacity", label: "Capacity", type: "text", placeholder: "e.g. 8 TB usable" },
      { key: "sharePath", label: "Share path / URL", type: "text" },
      { key: "shares", label: "Shared folders", type: "textarea", help: "The shares users map to, one per line." },
      { key: "permissions", label: "Access model / permissions", type: "textarea", help: "How access is granted — groups, roles, department shares, quotas." },
      { key: "backupRecord", label: "Backup service", type: "record", of: "flexibleAssets", help: "The backup service that protects this storage." },
      { key: "securityRecord", label: "Security platform", type: "record", of: "flexibleAssets", help: "The security platform covering this storage." },
      { key: "adminCredential", label: "Administrator credential", type: "record", of: "passwords" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
  ),
  tpl(
    "atype-printing",
    "Printing",
    "infrastructure",
    "print",
    "A printing arrangement — printers, scanners and plotters, how they are addressed and what print service delivers them — related to the physical device configurations they run on, their supplier, their consumables and the documents that describe them.",
    ["configurations", "contacts", "flexibleAssets", "documents"],
    [
      { key: "printerType", label: "Printer type", type: "select", required: true, options: printingDeviceTypeOptions(), help: "The kind of device — MFP, laser, label, wide-format, plotter, scanner and so on." },
      { key: "model", label: "Make / model", type: "text" },
      { key: "serviceModel", label: "Print service model", type: "select", options: printServiceModelOptions(), help: "How printing is delivered — direct, network shared, print server, managed print or cloud print." },
      { key: "address", label: "Address / queue", type: "text" },
      { key: "supplier", label: "Supplier", type: "text" },
      { key: "supplierRecord", label: "Supplier record", type: "record", of: "flexibleAssets", help: "The Vendor record that supplies the device or service." },
      { key: "printServerRecord", label: "Print server", type: "record", of: "configurations", help: "The server that hosts the print queues." },
      { key: "deviceRecord", label: "Device configuration", type: "record", of: "configurations", help: "The configuration record for the physical device." },
      { key: "consumables", label: "Consumables", type: "text", help: "The toner, cartridge or paper the device takes." },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
  ),
  tpl(
    "atype-vendor",
    "Vendor",
    "commercial",
    "building",
    "A technology supplier or service provider and the account details for it.",
    ["contacts", "flexibleAssets", "documents"],
    [
      { key: "vendorType", label: "Vendor type", type: "select", required: true, options: [
        { id: "hardware", label: "Hardware" },
        { id: "software", label: "Software" },
        { id: "isp-carrier", label: "ISP / carrier" },
        { id: "voice", label: "Voice / telephony" },
        { id: "security", label: "Security" },
        { id: "services", label: "Managed services" },
        { id: "other", label: "Other" },
      ] },
      { key: "accountNumber", label: "Account number", type: "text" },
      { key: "website", label: "Website", type: "url" },
      { key: "supportPhone", label: "Support phone", type: "phone" },
      { key: "supportEmail", label: "Support email", type: "email" },
      { key: "supportUrl", label: "Support portal", type: "url" },
      { key: "accountManager", label: "Account manager", type: "text" },
      { key: "accountManagerRecord", label: "Account manager contact", type: "record", of: "contacts" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
  ),
  tpl(
    "atype-user-role",
    "User role",
    "workforce",
    "building",
    "An organization-specific role: what the user does, the workstation tier they get, the applications and software build they use, and who holds the role.",
    ["flexibleAssets", "contacts", "documents"],
    [
      { key: "roleClassification", label: "Role classification", type: "select", required: true, options: [
        { id: "standard", label: "Standard user" },
        { id: "privileged", label: "Privileged user" },
        { id: "management", label: "Management" },
        { id: "executive", label: "Executive" },
        { id: "service", label: "Service / shared account" },
        { id: "guest", label: "Guest / contractor" },
        { id: "departmental", label: "Departmental" },
      ] },
      { key: "department", label: "Department", type: "text" },
      { key: "typicalTasks", label: "Typical tasks", type: "textarea", help: "What this role actually does day to day — the basis for their access and software." },
      { key: "typicalWorkstationTier", label: "Typical workstation tier", type: "select", options: tierOptions() },
      { key: "headcount", label: "Typical headcount", type: "number" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
  ),
  tpl(
    "atype-software-build",
    "Software build",
    "workforce",
    "layers",
    "A software configuration / build — the operating systems it supports, the applications it installs, the roles it applies to and how it is deployed.",
    ["flexibleAssets", "contacts", "documents"],
    [
      { key: "buildVersion", label: "Build version", type: "text" },
      { key: "supportedOs", label: "Supported operating systems", type: "multiselect", required: true, options: osOptions() },
      { key: "typicalWorkstationTier", label: "Typical workstation tier", type: "select", options: tierOptions() },
      { key: "deploymentMethod", label: "Deployment method", type: "select", required: true, options: [
        { id: "intune", label: "Microsoft Intune" },
        { id: "sccm", label: "MECM / SCCM" },
        { id: "rmm", label: "RMM script" },
        { id: "mdm", label: "MDM (macOS / mobile)" },
        { id: "imaging", label: "Imaging / golden image" },
        { id: "manual", label: "Manual install" },
        { id: "other", label: "Other" },
      ] },
      { key: "installNotes", label: "Installation notes", type: "textarea" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
  ),
  tpl(
    "atype-voice-pbx",
    "Voice / PBX platform",
    "applications",
    "phone",
    "The client's telephony as a structured service — the platform and deployment, the trunking and media, the voice services delivered, the emergency-calling and number inventory — related to the circuits, firewalls/security, configurations, applications, vendor, credentials, licensing, checklists and people behind it.",
    ["configurations", "contacts", "passwords", "flexibleAssets", "documents", "checklists"],
    [
      { key: "platformType", label: "Platform type", type: "select", required: true, options: voicePlatformOptions(), help: "The voice platform or PBX product family." },
      { key: "product", label: "Product / version", type: "text", placeholder: "e.g. RingCentral MVP, 3CX v20, Teams Phone" },
      { key: "deploymentModel", label: "Deployment model", type: "select", required: true, options: voiceDeploymentOptions(), help: "Where the call control actually lives." },
      { key: "provider", label: "Voice service provider / carrier", type: "text" },
      { key: "tenant", label: "Tenant / account reference", type: "text" },
      { key: "extensionCount", label: "Extensions", type: "number" },
      { key: "handsetCount", label: "Handsets / endpoints", type: "number" },
      { key: "simultaneousCalls", label: "Simultaneous calls (channels)", type: "number" },
      { key: "sipDomain", label: "SIP domain / registrar", type: "text" },
      { key: "trunkType", label: "Trunk type", type: "select", options: voiceTrunkTypeOptions(), help: "How calls reach the carrier — a SIP trunk, hosted trunk, PRI or analogue lines." },
      { key: "sipTransport", label: "SIP transport / security", type: "select", options: voiceSipTransportOptions() },
      { key: "codecs", label: "Codecs", type: "multiselect", options: voiceCodecOptions(), help: "The codecs the platform offers, in preference order." },
      { key: "services", label: "Voice services delivered", type: "multiselect", options: voiceServiceOptions(), help: "The features this client actually uses." },
      { key: "emergencyService", label: "Emergency calling", type: "select", options: emergencyServiceOptions(), help: "How emergency calls are routed and their dispatchable location." },
      { key: "emergencyAddress", label: "Emergency address / dispatchable location", type: "text" },
      { key: "numberInventory", label: "Number inventory", type: "textarea", help: "The DIDs, main numbers, toll-free and fax numbers and the extensions in use, one per line." },
      { key: "portingStatus", label: "Number porting status", type: "select", options: portingStatusOptions() },
      { key: "portDate", label: "Port date", type: "date", help: "The date the numbers are (or were) due to port." },
      { key: "failoverNotes", label: "Failover & redundancy", type: "textarea", help: "What happens if the platform, trunk or site link fails." },
      { key: "qualityNotes", label: "QoS & call-quality notes", type: "textarea", help: "VLAN, DSCP/QoS marking, bandwidth per call and any known quality issues." },
      { key: "adminUrl", label: "Admin portal URL", type: "url" },
      { key: "supportUrl", label: "Support portal", type: "url" },
      { key: "pbxHostRecord", label: "PBX / host configuration", type: "record", of: "configurations", help: "The server or appliance running the PBX or SBC." },
      { key: "sbcRecord", label: "Session border controller / firewall", type: "record", of: "configurations", help: "The SBC or firewall the voice traffic traverses." },
      { key: "securityRecord", label: "Security platform", type: "record", of: "flexibleAssets", help: "The Security-platform record protecting the voice service." },
      { key: "voiceApplication", label: "Voice application", type: "record", of: "flexibleAssets", help: "The Application record for the voice platform, if one is documented." },
      { key: "circuit", label: "Internet / WAN circuit", type: "record", of: "flexibleAssets", help: "The circuit that carries the voice traffic." },
      { key: "vendorRecord", label: "Voice vendor", type: "record", of: "flexibleAssets", help: "The Vendor record for the voice provider or carrier." },
      { key: "adminCredential", label: "Administrator credential", type: "record", of: "passwords", help: "The credential that administers the voice platform." },
      { key: "deploymentChecklist", label: "Deployment checklist", type: "record", of: "checklists", help: "The checklist followed to build or cut over the voice service." },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
  ),
  tpl(
    "atype-wan-circuit",
    "Internet / WAN circuit",
    "connectivity",
    "rocket",
    "A resold or managed internet / WAN circuit: the wholesale/upstream carrier it is bought from, the access technology, committed vs burst bandwidth, the static-IP and subnet allocation, the router/CPE, the SLA and contract term, and the reseller's own service definition and price.",
    ["configurations", "contacts", "flexibleAssets", "documents", "passwords"],
    [
      { key: "carrier", label: "Carrier", type: "text", required: true, help: "The carrier the circuit is held with — the name it is sold under." },
      { key: "upstreamCarrier", label: "Upstream / wholesale carrier", type: "text", help: "The wholesale provider the circuit is bought from, if different from the carrier above." },
      { key: "sourcing", label: "Sourcing model", type: "select", options: circuitSourcingOptions(), help: "Resold, wholesale, brokered, managed or own infrastructure." },
      { key: "circuitId", label: "Circuit ID", type: "text" },
      { key: "accountNumber", label: "Account number", type: "text" },
      { key: "serviceDefinition", label: "Service definition (tier)", type: "select", options: serviceDefinitionOptions(), help: "The reseller product this circuit is sold as." },
      { key: "circuitType", label: "Access technology", type: "select", required: true, options: accessTechnologyOptions() },
      { key: "bandwidthDown", label: "Committed download (Mbps)", type: "number" },
      { key: "bandwidthUp", label: "Committed upload (Mbps)", type: "number" },
      { key: "burstDown", label: "Burst download (Mbps)", type: "number", help: "The peak download the circuit may climb to (EIR)." },
      { key: "burstUp", label: "Burst upload (Mbps)", type: "number" },
      { key: "contention", label: "Contention / CIR", type: "text", help: "Leave blank to compute from burst ÷ committed." },
      { key: "slaTarget", label: "SLA target", type: "select", options: circuitSlaTargetOptions() },
      { key: "sla", label: "SLA notes", type: "text", help: "Any specific availability, response or restore terms." },
      { key: "staticIps", label: "Static IP address(es)", type: "textarea", help: "One address per line." },
      { key: "subnets", label: "Subnet allocation", type: "textarea", help: "Each allocated block in CIDR form, one per line (e.g. 203.0.113.0/29)." },
      { key: "vlans", label: "VLANs & segmentation", type: "textarea", help: "The VLANs delivered over this circuit and what each is for, one per line (e.g. 10 voice)." },
      { key: "ipv4Range", label: "IPv4 range", type: "text" },
      { key: "ipv6Range", label: "IPv6 range", type: "text" },
      { key: "publicHostname", label: "Public hostname / reverse DNS", type: "text" },
      { key: "cpeRole", label: "CPE role", type: "select", options: cpeRoleOptions() },
      { key: "cpeModel", label: "CPE make / model", type: "text" },
      { key: "cpeRecord", label: "Router / CPE", type: "record", of: "configurations", help: "The configuration record for the router, firewall or ONT terminating the circuit." },
      { key: "firewallRecord", label: "Edge firewall", type: "record", of: "configurations" },
      { key: "vendorRecord", label: "Vendor record", type: "record", of: "flexibleAssets", help: "The Vendor record for the upstream carrier or provider." },
      { key: "costPrice", label: "Wholesale cost (per month)", type: "number" },
      { key: "sellPrice", label: "Sell price (per month)", type: "number" },
      { key: "currency", label: "Currency", type: "text", placeholder: "e.g. GBP" },
      { key: "billingCycle", label: "Billing cycle", type: "select", options: billingCycleOptions(), help: "How often the circuit is invoiced." },
      { key: "billingDay", label: "Billing day", type: "number", help: "The day of the period the invoice is raised (e.g. 1)." },
      { key: "proration", label: "Proration", type: "select", options: prorationPolicyOptions(), help: "How a part-period (first/last invoice) is charged." },
      { key: "dataCap", label: "Data cap (GB)", type: "number", help: "The usage allowance for the period below. Leave blank if uncapped." },
      { key: "dataCapPeriod", label: "Data cap period", type: "select", options: dataCapPeriodOptions() },
      { key: "overageRate", label: "Overage rate (per GB)", type: "number", help: "Charge per GB once the cap is exceeded." },
      { key: "overageTreatment", label: "Overage treatment", type: "select", options: overageTreatmentOptions(), help: "What happens when the cap is exceeded." },
      { key: "usageMonitoring", label: "Usage monitoring / reporting source", type: "text", help: "Where the usage and cost figures come from (carrier portal, CPE counters, RMM, provider API)." },
      { key: "usageReadings", label: "Usage readings", type: "textarea", help: "One reading per line: period, usage, cost (e.g. 2026-07, 812 GB, 120.50)." },
      { key: "contractStartDate", label: "Contract start date", type: "date" },
      { key: "contractTermMonths", label: "Contract term (months)", type: "number" },
      { key: "contractEndDate", label: "Contract end date", type: "date", expiry: true },
      { key: "supportPhone", label: "Carrier support phone", type: "phone" },
      { key: "supportUrl", label: "Carrier support portal", type: "url" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
  ),
  tpl(
    "atype-custom",
    "Custom asset",
    "custom",
    "box",
    "A general structured record created when a note or free text is converted into an asset — a one-line summary, the detail it holds and where it came from. Clone it into a purpose-built template once its shape is known.",
    ["organizations", "locations", "contacts", "configurations", "flexibleAssets", "documents", "domains"],
    [
      { key: "summary", label: "Summary", type: "text" },
      { key: "details", label: "Detail", type: "textarea", help: "The values or content this record holds." },
      { key: "source", label: "Converted from", type: "text", help: "Where the content lived before it was structured into this asset." },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
  ),
];

export function builtinAssetType(id) {
  return BUILTIN_ASSET_TYPES.find((t) => t.id === id) || null;
}

export const BUILTIN_ASSET_TYPE_IDS = BUILTIN_ASSET_TYPES.map((t) => t.id);
