// src/framework/library.js — the in-application LIBRARY of service processes
// and operational topics (roadmap task 35).
//
// Task 35 asks IT-U to provide a library of service processes and operational
// topics — articles that a technician or administrator can follow as written, or
// adapt to the provider's own context — and to cross-link each article from the
// assets and procedures it supports.
//
// This module is the CATALOG: pure data (the topics and the articles) plus the
// pure functions the rest of the app reads it with. An article declares which
// shipped asset templates it supports (`assetTypeIds`) and which document types
// it belongs to (`docTypes`), so the asset profile can offer "how to run this"
// guidance for a service, the document editor can offer "start from the
// library", and the Library station can browse and search it. The same article
// is adapted into a real document with `articleToDocumentInput`, which is what
// makes a library article usable *as written or adapted*, rather than a static
// help page.
//
// Nothing here is stored in a client's documentation set: the library is
// shared content, like the Flexible Asset template library. What a client's set
// holds is the DOCUMENT an article is adapted into (and the links from it).

import { DOCUMENT_TYPES } from "./document.js";

// ---- topics ----------------------------------------------------------------
// The shelves of the library — the broad operational areas a TSP works in.
export const LIBRARY_TOPICS = [
  { id: "onboarding", label: "Client onboarding", icon: "building", description: "Discovering, documenting and taking over a new client." },
  { id: "email", label: "Email & collaboration", icon: "chat", description: "Mail platforms, authentication, migration and mail security." },
  { id: "backup", label: "Backup & recovery", icon: "history", description: "Designing, testing and recovering a client's data protection." },
  { id: "network", label: "Network & connectivity", icon: "lan", description: "LAN, WAN, wireless, firewalls and connectivity change." },
  { id: "security", label: "Security & access", icon: "shield", description: "Endpoint, identity, incident response and access baselines." },
  { id: "voice", label: "Voice & telephony", icon: "phone", description: "PBX platforms, dial plans, number porting and call quality." },
  { id: "internet", label: "Internet & ISP reselling", icon: "globe", description: "Provisioning, handover and support of resold circuits." },
  { id: "endpoint", label: "Endpoints & users", icon: "server", description: "Building, issuing and retiring the client's devices and accounts." },
  { id: "operations", label: "Operations & governance", icon: "clipboard", description: "Keeping documentation accurate, secure and current." },
];

export const LIBRARY_TOPIC_IDS = LIBRARY_TOPICS.map((t) => t.id);
export const libraryTopic = (id) => LIBRARY_TOPICS.find((t) => t.id === id) || null;
export const libraryTopicLabel = (id) => (libraryTopic(id) || {}).label || id;

// ---- audiences -------------------------------------------------------------
// Who an article is written for. The provider's own staff are the default; a
// client-facing article is one a client's staff can follow unaided.
export const LIBRARY_AUDIENCES = [
  { id: "provider", label: "Provider process", description: "How the technology provider performs the task." },
  { id: "technician", label: "Technician runbook", description: "A step-by-step task for a technician on site or remote." },
  { id: "client", label: "Client-facing", description: "Written so the client's own staff can follow it." },
];

export const LIBRARY_AUDIENCE_IDS = LIBRARY_AUDIENCES.map((a) => a.id);
export const libraryAudience = (id) => LIBRARY_AUDIENCES.find((a) => a.id === id) || null;

// ---- articles --------------------------------------------------------------
// `body` is markdown. `assetTypeIds` and `docTypes` are the CROSS-LINKS: they
// name the shipped asset templates this article supports and the document type
// it reads as, which is how the article is surfaced from an asset profile or a
// document editor.
function art({ id, title, topic, summary, tags = [], audience = "provider", assetTypeIds = [], docTypes = [], related = [], body }) {
  return {
    id,
    title,
    topic,
    summary,
    tags,
    audience,
    assetTypeIds,
    docTypes,
    related,
    body: (body || []).join("\n"),
  };
}

export const LIBRARY_ARTICLES = [
  // ---- Client onboarding ---------------------------------------------------
  art({
    id: "client-onboarding",
    title: "New client onboarding and discovery",
    topic: "onboarding",
    audience: "provider",
    summary: "The end-to-end process for taking on a new client and building their documentation set from nothing.",
    tags: ["onboarding", "discovery", "takeover", "process"],
    docTypes: ["sop", "deployment"],
    assetTypeIds: ["atype-applications", "atype-vendor", "atype-licences"],
    related: ["site-survey", "documentation-standards"],
    body: [
      "# New client onboarding and discovery",
      "",
      "## Purpose",
      "",
      "Bring a new client's environment into IT-U so it can be supported, deployed to and audited. The output is one documentation set that is accurate enough for a technician who has never seen the site.",
      "",
      "## Before you start",
      "",
      "- Confirm the engagement is signed and a point of contact is named.",
      "- Request read-only access to the systems you will document.",
      "- Create the client's documentation set (Organizations station) and add the organization, its locations and its key contacts.",
      "",
      "## Discovery",
      "",
      "1. Record the client's organization, its kind and its sites and locations.",
      "2. Capture the people: the primary contact, any application owners and the escalation contacts.",
      "3. Walk the network: the internet/WAN service, the LAN and its subnets, the wireless networks and the firewall.",
      "4. Inventory the configurations — servers, workstations, laptops, network equipment, printers and other managed devices.",
      "5. Capture the applications the business depends on and the vendors and licences behind them.",
      "6. Record the credentials the provider will need, as embedded credentials where they belong to a device or application.",
      "7. Capture the client's email arrangement, its domains and its certificates.",
      "8. Note the backup arrangement and test it before you rely on it.",
      "",
      "## Document it as structure",
      "",
      "Resist the urge to write prose. Devices become configurations, applications become application assets, suppliers become vendors. Link them so a reader can move from an application to its server, its credential and its owner without knowing where any of it lives.",
      "",
      "## Review",
      "",
      "This process is reviewed every 12 months.",
    ],
  }),
  art({
    id: "documentation-standards",
    title: "Documentation standards and the four information models",
    topic: "onboarding",
    audience: "provider",
    summary: "What belongs in a Core Asset, a Flexible Asset, a Document or an integration-managed record — and why it matters.",
    tags: ["standards", "information-model", "provenance", "governance"],
    docTypes: ["reference", "sop"],
    related: ["client-onboarding", "change-management"],
    body: [
      "# Documentation standards and the four information models",
      "",
      "## The four models",
      "",
      "- **Core Asset** — a record IT-U fixes the shape of: an organization, a location, a contact, a configuration. You may not re-shape these, so reports and audits stay reliable.",
      "- **Flexible Asset** — a record whose fields come from a template: applications, licences, vendors, email, backup, network, security and the other services. Adapt the template to the house standard.",
      "- **Document** — narrative or procedural content: procedures, guides, SOPs, deployment instructions and reference material.",
      "- **Integration-managed record** — a record created and maintained by a connected PSA or RMM. Edit the source system, not the record.",
      "",
      "## Provenance",
      "",
      "Every record also carries where it came from: directly authored, imported once, continuously synchronized, related to another record, linked to an external authoritative source, or stored as an attachment/document. This is what lets a later reader tell a typed-in guess from a synchronized fact.",
      "",
      "## The rules",
      "",
      "1. Record things with identity and relationships as structured assets, never as sentences in a document.",
      "2. Express a fact once and link to it — never retype the same fact into two records.",
      "3. A procedure a client must follow becomes a checklist where a checklist fits better than prose.",
      "4. Give anything with a date a date field, so the renewals board can track it.",
      "5. Keep credentials in password records, never inline in a document or a note.",
    ],
  }),
  art({
    id: "site-survey",
    title: "Site survey",
    topic: "onboarding",
    audience: "technician",
    summary: "What to capture on a first visit to a client site so the documentation set is complete after one trip.",
    tags: ["site", "survey", "discovery", "checklist"],
    docTypes: ["installation-procedure", "reference"],
    assetTypeIds: ["atype-lan", "atype-wireless"],
    related: ["client-onboarding", "network-discovery", "wireless-survey"],
    body: [
      "# Site survey",
      "",
      "## Purpose",
      "",
      "Capture the physical and logical facts about a site in one visit. Work through the list and photograph what you cannot describe.",
      "",
      "## Before you go",
      "",
      "- Bring a laptop, a network tester, a label printer and a camera.",
      "- Get the door codes and the name of the person meeting you.",
      "",
      "## What to capture",
      "",
      "1. The comms room: the rack layout, the patch panels, the switches and the router/firewall, with make, model and serial number.",
      "2. The power: the UPS, its runtime and what it protects.",
      "3. The internet entry point: the circuit ID, the carrier and where the handover lands.",
      "4. The cabling: structured cabling runs, label scheme and any known faults.",
      "5. The wireless: access-point positions, the SSIDs and how the wireless controller (if any) is managed.",
      "6. The endpoints: count and location of workstations, laptops, printers and scanners.",
      "7. The environment: anything that would affect an installation — access, noise, heat, cable routes.",
      "",
      "## Afterwards",
      "",
      "- Create or update the site summary and the diagram records.",
      "- Update the configurations, the LAN/WAN/wireless assets and the location records.",
      "- File the photos against the site diagram, keeping the editable source.",
    ],
  }),

  // ---- Email ---------------------------------------------------------------
  art({
    id: "email-migration",
    title: "Mailbox migration to a cloud mail platform",
    topic: "email",
    audience: "technician",
    summary: "A repeatable runbook for moving a client's mailboxes to Microsoft 365 or Google Workspace with minimal downtime.",
    tags: ["email", "migration", "m365", "google", "runbook"],
    docTypes: ["deployment", "installation-procedure"],
    assetTypeIds: ["atype-email-system", "atype-applications"],
    related: ["email-security-baseline", "email-signature-and-branding"],
    body: [
      "# Mailbox migration to a cloud mail platform",
      "",
      "## Scope",
      "",
      "Move every mailbox from the client's current mail system to the target cloud platform, preserving mail, calendars and contacts, with a planned cutover window.",
      "",
      "## Prerequisites",
      "",
      "- Verified domain ownership in the target tenant.",
      "- Admin credentials recorded for the source and target systems.",
      "- A documented mail-flow plan and a rollback plan.",
      "- The client's agreement on the cutover window and who signs off acceptance.",
      "",
      "## Deployment steps",
      "",
      "1. Provision the target tenant, licences and shared mailboxes.",
      "2. Recreate users, groups and aliases in the target.",
      "3. Start a pre-seed migration of the largest mailboxes.",
      "4. Reconcile the delta during the cutover window.",
      "5. Cut the MX record over to the target and confirm inbound flow.",
      "6. Reconfigure each client (Outlook, mobile) to the target.",
      "7. Confirm outbound flow, signatures and shared calendars.",
      "",
      "## Verification",
      "",
      "1. Send and receive a test message in both directions on each domain.",
      "2. Confirm mail, calendar and contacts are present for a sample of users.",
      "3. Confirm mobile devices reconnect with modern authentication (MFA).",
      "",
      "## Rollback",
      "",
      "1. Point the MX record back to the source system.",
      "2. Keep the source mailboxes online and unmodified until acceptance is signed.",
    ],
  }),
  art({
    id: "email-security-baseline",
    title: "Email authentication baseline (SPF, DKIM, DMARC)",
    topic: "email",
    audience: "provider",
    summary: "The DNS records every client's mail domain should carry, and how to roll them out without breaking mail flow.",
    tags: ["email", "spf", "dkim", "dmarc", "dns", "security"],
    docTypes: ["sop", "reference"],
    assetTypeIds: ["atype-email-system", "atype-security-platform"],
    related: ["email-migration", "security-baseline"],
    body: [
      "# Email authentication baseline",
      "",
      "## Purpose",
      "",
      "Protect the client's mail domain from spoofing and improve deliverability by publishing SPF, DKIM and DMARC.",
      "",
      "## Procedure",
      "",
      "1. Inventory every system that sends mail as the domain — the mail platform, marketing tools, ticketing and any application relay.",
      "2. Publish a single SPF record listing those systems, ending in a strict qualifier, and keep within the lookup limit.",
      "3. Enable DKIM signing in the mail platform and publish the selector's public key.",
      "4. Publish a DMARC record in monitor mode (p=none) with a reporting address.",
      "5. Review the aggregate reports for four weeks and correct anything legitimate that fails.",
      "6. Tighten DMARC to quarantine, then to reject, once reports are clean.",
      "7. Record the records in the email-system asset and link the Domain tracker records.",
      "",
      "## Roles",
      "",
      "The provider publishes the records; the client's mailbox administrator approves the tightening.",
      "",
      "## Review",
      "",
      "This baseline is reviewed every 12 months.",
    ],
  }),
  art({
    id: "email-signature-and-branding",
    title: "Standard email signature and branding",
    topic: "email",
    audience: "provider",
    summary: "Deploy a consistent, centrally managed signature and disclaimer across a client's mailboxes.",
    tags: ["email", "signature", "branding"],
    docTypes: ["sop"],
    assetTypeIds: ["atype-email-system"],
    related: ["email-migration", "user-onboarding"],
    body: [
      "# Standard email signature and branding",
      "",
      "## Purpose",
      "",
      "Give every mailbox a consistent signature and disclaimer without asking each user to build their own.",
      "",
      "## Procedure",
      "",
      "1. Agree the signature content and the disclaimer wording with the client.",
      "2. Configure a central signature rule at the mail platform (transport rule or signature service) so it applies to every mailbox.",
      "3. Populate per-user fields from the directory rather than hard-coding names.",
      "4. Test on a mixture of internal and external recipients, including mobile replies.",
      "5. Record the configuration against the email-system asset.",
      "",
      "## Roles",
      "",
      "The provider configures; the client signs off the wording.",
    ],
  }),
  art({
    id: "email-client-setup",
    title: "Set up your email on a new device",
    topic: "email",
    audience: "client",
    summary: "A plain-language guide for a client's staff to add their work email to a phone, tablet or new computer.",
    tags: ["email", "client-facing", "device", "instructions"],
    docTypes: ["public-instruction"],
    assetTypeIds: ["atype-email-system"],
    related: ["email-migration", "user-onboarding"],
    body: [
      "# Set up your email on a new device",
      "",
      "## Before you start",
      "",
      "You will need your work email address and your password. If you don't know them, or you're asked to set up multi-factor authentication, contact the IT help desk — do not guess.",
      "",
      "## On a phone or tablet",
      "",
      "1. Install the Outlook app (for Microsoft 365) or the Gmail app (for Google Workspace) from your device's app store.",
      "2. Open the app and choose to add an account.",
      "3. Enter your full work email address, then your password on the next screen.",
      "4. Approve the sign-in prompt on your phone if one appears (this is multi-factor authentication).",
      "5. Allow notifications so you see new mail, and allow calendar access if you want your work calendar on the device.",
      "",
      "## On a new computer",
      "",
      "1. Open Outlook or Mail and choose to add an account.",
      "2. Enter your work email address and password, and approve the sign-in prompt.",
      "3. Wait for your mail and calendar to finish downloading — this can take a few minutes the first time.",
      "",
      "## If something doesn't work",
      "",
      "- Check you typed the full email address, with no spaces.",
      "- Make sure the device has internet access.",
      "- If you are asked for a server name or port, stop and call the help desk — those settings are chosen for you.",
      "",
      "## Your responsibilities",
      "",
      "Set a screen lock on the device, and tell the help desk straight away if it is lost or stolen.",
    ],
  }),

  // ---- Backup --------------------------------------------------------------
  art({
    id: "backup-design",
    title: "Designing a backup and recovery arrangement",
    topic: "backup",
    audience: "provider",
    summary: "How to choose an architecture, schedule and destinations that match a client's recovery requirements.",
    tags: ["backup", "design", "rpo", "rto", "3-2-1"],
    docTypes: ["sop", "reference"],
    assetTypeIds: ["atype-backup-service"],
    related: ["restore-test", "disaster-recovery-plan"],
    body: [
      "# Designing a backup and recovery arrangement",
      "",
      "## Purpose",
      "",
      "Choose a backup arrangement that actually meets the client's recovery point and recovery time objectives — and that has been tested.",
      "",
      "## Procedure",
      "",
      "1. Establish the recovery point objective (how much data the client can afford to lose) and the recovery time objective (how long they can be down) for each service.",
      "2. Classify the data: whole systems, databases, files, cloud items.",
      "3. Choose an architecture per class — image, file, application, database or cloud-to-cloud.",
      "4. Apply the 3-2-1 rule: three copies, on two media, one off-site.",
      "5. Set the schedule and retention to meet the objectives, not the other way round.",
      "6. Record the arrangement as a backup-service asset and link the protected configurations, the storage, the vendor, the credential and the recovery document.",
      "7. Schedule the first restore test before you consider the design complete.",
      "",
      "## Roles",
      "",
      "The provider designs; the client's owner approves the objectives.",
      "",
      "## Review",
      "",
      "Review the design every 12 months and whenever a protected service changes.",
    ],
  }),
  art({
    id: "restore-test",
    title: "Restore test",
    topic: "backup",
    audience: "technician",
    summary: "Prove a backup works by restoring from it — the step that turns a backup arrangement into a credible one.",
    tags: ["backup", "restore", "test", "verification"],
    docTypes: ["installation-procedure", "sop"],
    assetTypeIds: ["atype-backup-service"],
    related: ["backup-design", "disaster-recovery-plan"],
    body: [
      "# Restore test",
      "",
      "## Purpose",
      "",
      "Demonstrate that a protected system can be recovered from its backups within the recovery objectives. An untested backup is an assumption.",
      "",
      "## Procedure",
      "",
      "1. Pick the system and the recovery point being tested.",
      "2. Restore to an isolated location — never over the live system.",
      "3. Record how long the restore took and compare it to the recovery time objective.",
      "4. Verify the restored system starts, its data is current and its integrity checks pass.",
      "5. Record the test date and result on the backup-service asset.",
      "6. If the test failed or was partial, raise a fix and re-test.",
      "",
      "## Verification",
      "",
      "1. The restored data matches the chosen recovery point.",
      "2. The restored service is usable by the people who need it.",
      "",
      "## Roles",
      "",
      "A technician performs the test; the account owner reviews the result.",
    ],
  }),
  art({
    id: "disaster-recovery-plan",
    title: "Writing the client disaster-recovery plan",
    topic: "backup",
    audience: "provider",
    summary: "Turn the backup design and the recovery documents into one plan a client can rely on when the worst happens.",
    tags: ["backup", "disaster-recovery", "plan", "recovery"],
    docTypes: ["recovery", "reference"],
    assetTypeIds: ["atype-backup-service", "atype-virtualization"],
    related: ["backup-design", "restore-test"],
    body: [
      "# Client disaster-recovery plan",
      "",
      "## Trigger",
      "",
      "A failure that puts a critical service out of action — a failed server, a lost site, ransomware or a corrupted data store.",
      "",
      "## Contents",
      "",
      "1. The critical services, in recovery order, with their recovery objectives.",
      "2. Where the backups and replicas live, and who can reach them.",
      "3. The recovery steps per service, linked to the recovery-procedure documents.",
      "4. The people to contact, with out-of-hours details.",
      "5. The client's obligations and the provider's obligations.",
      "6. The communication plan for the client's staff and customers.",
      "",
      "## Validation",
      "",
      "1. Walk through the plan with the client once a year.",
      "2. Confirm each recovery step still matches the current backup design.",
      "",
      "## After the event",
      "",
      "Record what happened, what worked, what did not and what changed as a result.",
    ],
  }),

  // ---- Network -------------------------------------------------------------
  art({
    id: "network-discovery",
    title: "LAN and WAN discovery",
    topic: "network",
    audience: "technician",
    summary: "How to map a client's network — circuits, subnets, switching, DNS and routing — into IT-U without guessing.",
    tags: ["network", "lan", "wan", "discovery", "subnet"],
    docTypes: ["installation-procedure", "reference"],
    assetTypeIds: ["atype-wan-service", "atype-lan", "atype-wireless"],
    related: ["client-onboarding", "wireless-survey", "firewall-change"],
    body: [
      "# LAN and WAN discovery",
      "",
      "## Purpose",
      "",
      "Produce an accurate picture of the client's network as structured records, not a diagram nobody can trust.",
      "",
      "## Procedure",
      "",
      "1. Identify the internet/WAN service: the carrier, the circuit ID, the bandwidth and the public addressing. Record it as a WAN service asset.",
      "2. Identify the firewall or edge device terminating the service and record it as a configuration.",
      "3. Walk the LAN: record the subnets, the IP addressing scheme and the internal DNS. Record a LAN asset.",
      "4. Inventory the switches and how they interconnect, and the servers and how they are addressed.",
      "5. Capture the wireless networks, their SSIDs, their access points and their security.",
      "6. Capture the VLAN scheme and any segmentation.",
      "7. Link the records together — firewall to WAN, LAN to its switches and servers, wireless to its access points and LAN.",
      "",
      "## Verification",
      "",
      "1. Every recorded subnet is reachable and documented.",
      "2. Every device that routes or switches traffic is a configuration record.",
      "",
      "## Roles",
      "",
      "A technician performs discovery; the network owner reviews the result.",
    ],
  }),
  art({
    id: "wireless-survey",
    title: "Wireless site survey",
    topic: "network",
    audience: "technician",
    summary: "Plan or troubleshoot a wireless network by measuring coverage, interference and roaming.",
    tags: ["wireless", "wifi", "survey", "coverage", "roaming"],
    docTypes: ["installation-procedure", "troubleshooting"],
    assetTypeIds: ["atype-wireless", "atype-lan"],
    related: ["network-discovery", "site-survey"],
    body: [
      "# Wireless site survey",
      "",
      "## Purpose",
      "",
      "Confirm the wireless network covers the client's space at the required signal strength, with clean roaming and acceptable interference.",
      "",
      "## Procedure",
      "",
      "1. Obtain or draw a floor plan and mark the occupied areas.",
      "2. Walk the space recording signal strength, noise and channel utilisation.",
      "3. Identify sources of interference — neighbouring networks, microwave ovens, metal structures.",
      "4. Place or move access points to deliver the target signal where people actually work.",
      "5. Confirm roaming between access points is seamless and every access point is recorded.",
      "6. Record the design, the SSIDs and the security as wireless and LAN assets.",
      "",
      "## Verification",
      "",
      "1. No coverage hole in an occupied area.",
      "2. Every access point is a configuration record, linked to the wireless network.",
      "",
      "## Roles",
      "",
      "A technician performs the survey; the network owner reviews the design.",
    ],
  }),
  art({
    id: "firewall-change",
    title: "Firewall change-management procedure",
    topic: "network",
    audience: "provider",
    summary: "How to raise, approve, apply and document a firewall rule change without an outage.",
    tags: ["firewall", "change", "security", "rule"],
    docTypes: ["sop", "installation-procedure"],
    assetTypeIds: ["atype-security-platform", "atype-wan-service"],
    related: ["network-discovery", "change-management"],
    body: [
      "# Firewall change-management procedure",
      "",
      "## Purpose",
      "",
      "Make a controlled change to a firewall's rule set, documented and reversible.",
      "",
      "## Procedure",
      "",
      "1. Record the request: what needs to reach what, on which ports, and why.",
      "2. Identify the rule's exact place in the rule order and confirm it will not shadow an existing rule.",
      "3. Prepare the change and a rollback (the previous configuration export).",
      "4. Schedule the change in a window and tell anyone affected.",
      "5. Apply the change and test the intended traffic and the traffic that must still be blocked.",
      "6. Save the new configuration and record the change in the client's documentation.",
      "7. If anything unexpected happens, roll back and raise a fix.",
      "",
      "## Roles",
      "",
      "A technician prepares; a second person approves and witnesses the change.",
      "",
      "## Review",
      "",
      "This procedure is reviewed every 12 months.",
    ],
  }),

  // ---- Security ------------------------------------------------------------
  art({
    id: "security-baseline",
    title: "Endpoint security baseline",
    topic: "security",
    audience: "provider",
    summary: "The security controls every managed endpoint should carry, and how to verify them.",
    tags: ["security", "endpoint", "edr", "baseline", "hardening"],
    docTypes: ["sop", "reference"],
    assetTypeIds: ["atype-security-platform", "atype-software-build"],
    related: ["mfa-rollout", "email-security-baseline"],
    body: [
      "# Endpoint security baseline",
      "",
      "## Purpose",
      "",
      "Give every managed endpoint a consistent minimum of protection and prove it is in place.",
      "",
      "## Controls",
      "",
      "- Endpoint detection and response (EDR) or antivirus, reporting to the management console.",
      "- Full-disk encryption with recovery keys escrowed.",
      "- Automatic patching of the operating system and key applications.",
      "- A screen lock and a strong sign-in requirement.",
      "- A host firewall, with only the required ports open.",
      "- Backup of the endpoint's data where it is not stored centrally.",
      "",
      "## Procedure",
      "",
      "1. Choose the management method — the software build, or the RMM security policy.",
      "2. Apply the controls to each build or role.",
      "3. Verify on a sample of endpoints that the controls are reporting as compliant.",
      "4. Record the controls against the security-platform asset and the software build.",
      "5. Remediate any endpoint that falls out of compliance and record the exception.",
      "",
      "## Review",
      "",
      "This baseline is reviewed every 12 months.",
    ],
  }),
  art({
    id: "mfa-rollout",
    title: "Multi-factor authentication rollout",
    topic: "security",
    audience: "technician",
    summary: "Roll out MFA across a client's identity platforms in waves, without locking people out.",
    tags: ["security", "mfa", "identity", "rollout"],
    docTypes: ["deployment", "installation-procedure"],
    assetTypeIds: ["atype-security-platform", "atype-remote-access"],
    related: ["security-baseline", "user-onboarding"],
    body: [
      "# Multi-factor authentication rollout",
      "",
      "## Scope",
      "",
      "Enforce MFA on the client's identity platform and the remote-access services that depend on it, for every user, in controlled waves.",
      "",
      "## Prerequisites",
      "",
      "- A licensing check for each user.",
      "- A communication to users explaining what will change.",
      "- A registered fallback method and a break-glass admin account exempt from enforcement.",
      "",
      "## Deployment steps",
      "",
      "1. Enable MFA for administrators first and confirm they can sign in.",
      "2. Enable it for a pilot group and gather feedback.",
      "3. Enable it for everyone, with a registration grace period.",
      "4. Enforce it on remote access and any single-sign-on applications.",
      "5. Record the enforcement against the security-platform and remote-access assets.",
      "",
      "## Verification",
      "",
      "1. A sample of users can sign in with MFA on desktop and mobile.",
      "2. The break-glass account is reachable and documented.",
      "",
      "## Rollback",
      "",
      "1. Revert the enforcement policy to the previous state and re-test sign-in.",
    ],
  }),
  art({
    id: "incident-response",
    title: "First-line security incident response",
    topic: "security",
    audience: "technician",
    summary: "What a first-line technician does in the first hour of a suspected security incident.",
    tags: ["security", "incident", "response", "escalation"],
    docTypes: ["help-desk", "recovery"],
    assetTypeIds: ["atype-security-platform"],
    related: ["security-baseline", "disaster-recovery-plan"],
    body: [
      "# First-line security incident response",
      "",
      "## When this applies",
      "",
      "A suspected phishing, malware, ransomware or account-compromise event is reported or detected.",
      "",
      "## Steps",
      "",
      "1. Record the report: who saw what, when and where.",
      "2. Do not power off or wipe anything before capturing evidence.",
      "3. Isolate the affected device from the network if malware is suspected.",
      "4. Reset the credentials of any account believed to be compromised, and revoke its sessions.",
      "5. Check whether the same signal appears on other endpoints or accounts.",
      "6. Escalate to the security owner and, where required, the client's contact.",
      "7. Preserve the evidence and start an incident log.",
      "",
      "## Escalate when",
      "",
      "- Data is lost, encrypted or exfiltrated.",
      "- More than one account or device is affected.",
      "- The incident touches a regulated or client-facing system.",
    ],
  }),

  // ---- Voice ---------------------------------------------------------------
  art({
    id: "voip-deployment",
    title: "VoIP deployment process",
    topic: "voice",
    audience: "provider",
    summary: "The full process for building a voice platform, from design through number porting to acceptance.",
    tags: ["voice", "voip", "pbx", "deployment", "sip"],
    docTypes: ["deployment", "sop"],
    assetTypeIds: ["atype-voice-pbx", "atype-wan-service", "atype-wan-circuit"],
    related: ["number-porting", "voice-quality-troubleshooting", "network-readiness"],
    body: [
      "# VoIP deployment process",
      "",
      "## Scope",
      "",
      "Deliver a working voice platform for a client: dial plan, trunking, numbers, emergency calling and the per-site network readiness behind it.",
      "",
      "## Prerequisites",
      "",
      "- The platform and the trunk design agreed with the client.",
      "- The number inventory and the porting plan confirmed.",
      "- Each site's network ready for voice (see the network readiness checks).",
      "",
      "## Deployment steps",
      "",
      "1. Create or provision the voice platform and record it as a voice/PBX asset.",
      "2. Build the dial plan, extensions and ring groups.",
      "3. Configure the SIP trunk(s) and confirm registration and call routing.",
      "4. Record the number inventory — DIDs, toll-free and blocks — and the porting status.",
      "5. Set the emergency/911 address for each site.",
      "6. Agree the codecs and apply QoS marking end to end.",
      "7. Configure the firewall or SBC for SIP/RTP and NAT traversal.",
      "8. Configure failover and redundancy — a secondary trunk or a secondary platform.",
      "9. Configure and issue the handsets and softphones.",
      "10. Confirm each site's readiness: VLAN, PoE, bandwidth and latency/jitter limits.",
      "",
      "## Verification",
      "",
      "1. Inbound and outbound calls succeed on every trunk.",
      "2. Extensions and ring groups route correctly.",
      "3. Voicemail, recording and emergency calling work.",
      "4. Failover test: the secondary path carries calls.",
      "",
      "## Acceptance",
      "",
      "The client signs off the acceptance checklist; the porting dates and support entitlements are recorded in the trackers.",
    ],
  }),
  art({
    id: "number-porting",
    title: "Number porting process",
    topic: "voice",
    audience: "technician",
    summary: "Move a client's telephone numbers from the losing carrier to the new platform with the least disruption.",
    tags: ["voice", "porting", "numbers", "did", "carrier"],
    docTypes: ["deployment", "installation-procedure"],
    assetTypeIds: ["atype-voice-pbx", "atype-wan-circuit"],
    related: ["voip-deployment"],
    body: [
      "# Number porting process",
      "",
      "## Purpose",
      "",
      "Port the client's numbers to the new voice platform, with the correct service record and legal addresses, without losing calls.",
      "",
      "## Procedure",
      "",
      "1. Build the number inventory: every number, its current carrier, its service use and its emergency address.",
      "2. Confirm the account details and authorization to port each number with the losing carrier.",
      "3. Submit the port order and record the requested date and status.",
      "4. For number blocks, confirm the range and the partial-port implications.",
      "5. On the port date, confirm inbound calls arrive on the new platform and outbound caller ID is correct.",
      "6. Keep the old service reachable until the port is confirmed complete.",
      "7. Update the number inventory and the voice/PBX asset with the final status and dates.",
      "",
      "## Verification",
      "",
      "1. Inbound calls to every ported number land on the platform.",
      "2. Outbound calls present the correct caller ID.",
      "3. Emergency calls resolve to the correct address.",
      "",
      "## Rollback",
      "",
      "1. Where a port fails, escalate to the losing carrier and keep the old service in place.",
    ],
  }),
  art({
    id: "voice-quality-troubleshooting",
    title: "Voice quality troubleshooting",
    topic: "voice",
    audience: "technician",
    summary: "Diagnose choppy, delayed or dropped calls by working from the network up.",
    tags: ["voice", "qos", "jitter", "latency", "troubleshooting"],
    docTypes: ["troubleshooting", "help-desk"],
    assetTypeIds: ["atype-voice-pbx", "atype-lan", "atype-wan-service"],
    related: ["voip-deployment", "network-readiness"],
    body: [
      "# Voice quality troubleshooting",
      "",
      "## Symptoms",
      "",
      "The client reports choppy audio, echo, one-way audio, delay or dropped calls.",
      "",
      "## Diagnosis",
      "",
      "1. Establish whether the problem affects one handset, one site or everyone.",
      "2. Check the site's internet circuit for latency, jitter and packet loss during business hours.",
      "3. Check the LAN: is voice on its own VLAN, and is QoS marking applied end to end?",
      "4. Confirm the codec in use and whether transcoding is happening.",
      "5. Test a call across the trunk in both directions and compare call detail records.",
      "",
      "## Resolution",
      "",
      "1. Fix the layer at fault — WAN, LAN, QoS or platform.",
      "2. Re-test with a call of at least two minutes in each direction.",
      "3. Record the finding and, if it recurs, raise a permanent change.",
      "",
      "## Prevention",
      "",
      "Keep the network-readiness checks current for every voice site.",
    ],
  }),
  art({
    id: "network-readiness",
    title: "Per-site voice network readiness checks",
    topic: "voice",
    audience: "technician",
    summary: "The VLAN, PoE, bandwidth and latency/jitter checks every site must pass before voice goes live.",
    tags: ["voice", "qos", "vlan", "poe", "readiness"],
    docTypes: ["installation-procedure", "sop"],
    assetTypeIds: ["atype-voice-pbx", "atype-lan", "atype-wan-service"],
    related: ["voip-deployment", "network-discovery"],
    body: [
      "# Per-site voice network readiness checks",
      "",
      "## Purpose",
      "",
      "Confirm a site's network can carry voice before the platform goes live, so quality problems are found in the office rather than on a call.",
      "",
      "## Checks",
      "",
      "1. Voice is on its own VLAN, or a documented alternative segmentation is in place.",
      "2. Power over Ethernet (PoE) is available on every handset port, with the budget to spare.",
      "3. The internet circuit has enough bandwidth for the concurrent call count.",
      "4. Measured latency, jitter and packet loss are within the voice thresholds.",
      "5. QoS is configured and honoured on the LAN and the WAN.",
      "6. The firewall or SBC has the SIP and RTP rules and NAT traversal configured.",
      "7. Emergency calling addresses are set for the site.",
      "",
      "## Result",
      "",
      "Record the result per site against the voice/PBX asset; a site that fails a check is not ready to cut over.",
    ],
  }),

  // ---- Internet & ISP reselling --------------------------------------------
  art({
    id: "circuit-provisioning",
    title: "Provisioning and activating a resold circuit",
    topic: "internet",
    audience: "technician",
    summary: "Bring a resold internet circuit live: order, carrier handoff, CPE, addressing, activation and testing.",
    tags: ["internet", "circuit", "isp", "provisioning", "activation"],
    docTypes: ["deployment", "installation-procedure"],
    assetTypeIds: ["atype-wan-circuit", "atype-wan-service", "atype-security-platform"],
    related: ["circuit-handover", "network-discovery"],
    body: [
      "# Provisioning and activating a resold circuit",
      "",
      "## Scope",
      "",
      "Order, bring live and test the wholesale circuit behind a resold internet service.",
      "",
      "## Deployment steps",
      "",
      "1. Capture the order and the sold plan, and record the circuit as an internet/WAN circuit asset.",
      "2. Place the order with the upstream carrier and record the circuit ID and handoff details.",
      "3. Select, configure and record the customer-premises equipment (CPE).",
      "4. Assign the static addressing and subnet(s) and set reverse DNS where required.",
      "5. Apply the firewall and routing changes for the new circuit.",
      "6. Activate the service and confirm the carrier's handoff.",
      "7. Test connectivity, throughput and failover across circuits.",
      "8. Record the customer acceptance.",
      "",
      "## Verification",
      "",
      "1. Latency and throughput meet the sold plan.",
      "2. Routing and firewall rules pass the intended and block the unintended traffic.",
      "3. Failover works if a second circuit is present.",
      "",
      "## Roles",
      "",
      "A technician provisions; the account owner confirms the commercial details.",
    ],
  }),
  art({
    id: "circuit-handover",
    title: "Circuit handover and customer acceptance",
    topic: "internet",
    audience: "provider",
    summary: "Formally hand a resold circuit to the client, with the tests, addresses and escalation path recorded.",
    tags: ["internet", "handover", "acceptance", "circuit"],
    docTypes: ["sop", "reference"],
    assetTypeIds: ["atype-wan-circuit", "atype-wan-service"],
    related: ["circuit-provisioning"],
    body: [
      "# Circuit handover and customer acceptance",
      "",
      "## Purpose",
      "",
      "Close out a circuit deployment so the client — and the provider's own support desk — know exactly what was delivered.",
      "",
      "## Procedure",
      "",
      "1. Walk the client through the delivered service and its packaged bandwidth.",
      "2. Hand over the addressing, the CPE and the support escalation path.",
      "3. Run the acceptance tests with the client watching and record the results.",
      "4. Record the circuit's contract term and its support entitlement in the trackers.",
      "5. Get the client's sign-off and file it against the circuit asset.",
      "6. Update the documentation set so nothing is still marked as 'provisioning'.",
      "",
      "## Roles",
      "",
      "The account owner runs the handover; the client signs acceptance.",
    ],
  }),

  // ---- Endpoints & users ---------------------------------------------------
  art({
    id: "workstation-build",
    title: "Standard workstation build and handover",
    topic: "endpoint",
    audience: "technician",
    summary: "Build, harden and hand over a workstation to a client's user — consistently, every time.",
    tags: ["endpoint", "build", "workstation", "handover"],
    docTypes: ["installation-procedure", "deployment"],
    assetTypeIds: ["atype-software-build", "atype-user-role", "atype-applications"],
    related: ["user-onboarding", "security-baseline"],
    body: [
      "# Standard workstation build and handover",
      "",
      "## Purpose",
      "",
      "Issue a workstation that matches the user's role, carries the security baseline and is documented as a configuration.",
      "",
      "## Procedure",
      "",
      "1. Confirm the user's role and the software build it receives.",
      "2. Deploy the build — the operating system and the role's applications.",
      "3. Join the device to the management platform and apply the security baseline.",
      "4. Record the device as a configuration with its serial number, hostname and user.",
      "5. Sign the user in once, confirm their applications and mapped drives work, and show them how to get help.",
      "6. Give the user their credentials through the agreed secure channel, and record the device's embedded credential.",
      "",
      "## Verification",
      "",
      "1. The build matches the role's standard.",
      "2. The device reports compliant in the security console.",
      "3. The configuration record is complete.",
      "",
      "## Roles",
      "",
      "A technician builds and issues; the user confirms their access.",
    ],
  }),
  art({
    id: "user-onboarding",
    title: "User onboarding and offboarding",
    topic: "endpoint",
    audience: "technician",
    summary: "Give a new user everything they need on day one — and take it all away cleanly when they leave.",
    tags: ["endpoint", "user", "onboarding", "offboarding", "identity"],
    docTypes: ["installation-procedure", "sop"],
    assetTypeIds: ["atype-user-role", "atype-applications", "atype-software-build"],
    related: ["workstation-build", "mfa-rollout"],
    body: [
      "# User onboarding and offboarding",
      "",
      "## Onboarding",
      "",
      "1. Confirm the user's role and who requested the account.",
      "2. Create the identity and the mailbox, and assign the role's applications.",
      "3. Enrol the user in MFA and issue their credentials securely.",
      "4. Prepare and issue the workstation (see the workstation build).",
      "5. Record the user as a contact with their role and the assets they own.",
      "",
      "## Offboarding",
      "",
      "1. Confirm the request and the last working day with the client's approver.",
      "2. Disable the identity, revoke sessions and convert the mailbox as agreed.",
      "3. Recover and wipe the device, saving any data the client needs.",
      "4. Reassign or remove the assets the user owned, and close their credentials.",
      "5. Record the offboarding date against the contact and the device.",
      "",
      "## Roles",
      "",
      "A technician performs both; the client's approver authorises access changes.",
    ],
  }),

  // ---- Operations & governance ---------------------------------------------
  art({
    id: "password-rotation",
    title: "Credential rotation and hygiene",
    topic: "operations",
    audience: "provider",
    summary: "Keep credentials strong, unique, owned and rotated — and understand the limits of automatic rotation.",
    tags: ["credentials", "passwords", "rotation", "hygiene", "security"],
    docTypes: ["sop", "reference"],
    assetTypeIds: ["atype-security-platform"],
    related: ["security-baseline", "incident-response"],
    body: [
      "# Credential rotation and hygiene",
      "",
      "## Purpose",
      "",
      "Keep the credentials the provider holds in good order: strong, unique, attributable and rotated when people or systems change.",
      "",
      "## Procedure",
      "",
      "1. Every credential belongs in a password record, linked to the asset it unlocks — general or embedded, never inline in a document.",
      "2. Generate unique credentials rather than reusing them across systems.",
      "3. Record the rotation path: manual, or via a designated connected password-management product. Automatic rotation depends on the connected product and is never guaranteed by the documentation system itself.",
      "4. Rotate a credential when a person leaves, when a device is retired or when a compromise is suspected.",
      "5. Grant general-credential access by group, so a viewer cannot read a credential they do not need.",
      "",
      "## Roles",
      "",
      "An administrator owns the credential store; technicians request access rather than sharing.",
      "",
      "## Review",
      "",
      "This procedure is reviewed every 12 months.",
    ],
  }),
  art({
    id: "change-management",
    title: "Change management and documentation governance",
    topic: "operations",
    audience: "provider",
    summary: "Make every change to a client's environment leave the documentation more accurate than it found it.",
    tags: ["change", "governance", "documentation", "process"],
    docTypes: ["sop", "reference"],
    related: ["documentation-standards", "firewall-change"],
    body: [
      "# Change management and documentation governance",
      "",
      "## Purpose",
      "",
      "Ensure that a change is made deliberately, reversibly and with the client's documentation updated as part of the change — not as an afterthought.",
      "",
      "## Procedure",
      "",
      "1. Record the request, its impact and its rollback.",
      "2. Get approval from whoever owns the affected service.",
      "3. Schedule the change and advise anyone affected.",
      "4. Apply the change and verify the intended result.",
      "5. Update the documentation set as part of closing the change: the records that changed, the credentials, the configuration and any document.",
      "6. Record what was done, by whom, and when.",
      "",
      "## The documentation test",
      "",
      "A change is not finished until a technician who did not make it could understand the new state from the documentation alone.",
      "",
      "## Review",
      "",
      "This procedure is reviewed every 12 months.",
    ],
  }),
  art({
    id: "quarterly-review",
    title: "Quarterly client documentation review",
    topic: "operations",
    audience: "provider",
    summary: "A standing review that keeps each client's documentation set accurate, complete and lifecycle-aware.",
    tags: ["review", "quality", "lifecycle", "linter", "governance"],
    docTypes: ["sop", "reference"],
    related: ["change-management", "documentation-standards"],
    body: [
      "# Quarterly client documentation review",
      "",
      "## Purpose",
      "",
      "Catch drift before it matters: stale records, missing relationships, imminent expiries and documents past their review date.",
      "",
      "## Procedure",
      "",
      "1. Run the Linter and work through its findings — incomplete configurations, assets with no relationships, expired or imminent items.",
      "2. Review the renewals and lifecycle board: anything overdue or due soon should have an owner.",
      "3. Confirm every document with a review date has been reviewed or rescheduled.",
      "4. Check for records that duplicate structured data in prose and move the facts into a structured asset.",
      "5. Confirm the client's service assets each have the relationships their usefulness depends on.",
      "6. Record what changed and tell the client's owner what needs a decision.",
      "",
      "## Roles",
      "",
      "The account owner runs the review with a technician.",
      "",
      "## Review",
      "",
      "This procedure is reviewed every 12 months.",
    ],
  }),
];

// ---- reads -----------------------------------------------------------------
export const LIBRARY_ARTICLE_IDS = LIBRARY_ARTICLES.map((a) => a.id);
const ARTICLE_INDEX = new Map(LIBRARY_ARTICLES.map((a) => [a.id, a]));

export const libraryArticle = (id) => ARTICLE_INDEX.get(id) || null;
export const libraryArticleExists = (id) => ARTICLE_INDEX.has(id);

const asArray = (v) => (Array.isArray(v) ? v : v == null || v === "" ? [] : [v]);

// The articles matching a set of filters. Every filter is optional and they
// combine AND-wise; `query` matches the title, summary and tags
// case-insensitively.
export function libraryArticles({ topic, audience, assetTypeId, docType, query, ids } = {}) {
  const q = String(query || "").trim().toLowerCase();
  const wantedIds = ids ? new Set(asArray(ids)) : null;
  let list = LIBRARY_ARTICLES.slice();
  if (wantedIds) list = list.filter((a) => wantedIds.has(a.id));
  if (topic) list = list.filter((a) => a.topic === topic);
  if (audience) list = list.filter((a) => a.audience === audience);
  if (assetTypeId) list = list.filter((a) => a.assetTypeIds.includes(assetTypeId));
  if (docType) list = list.filter((a) => a.docTypes.includes(docType));
  if (q) {
    list = list.filter((a) => {
      const haystack = [a.title, a.summary, ...(a.tags || [])].join(" ").toLowerCase();
      return haystack.includes(q);
    });
  }
  return list;
}

// The articles that support a given shipped asset template — the cross-link the
// asset profile reads.
export const libraryForAssetType = (assetTypeId) => libraryArticles({ assetTypeId });

// The library equivalent of a document type — the cross-link the document
// editor reads.
export const libraryForDocType = (docType) => libraryArticles({ docType });

// Free-text search over the library.
export const searchLibrary = (query, opts = {}) => libraryArticles({ ...opts, query });

// Related articles for an article (its declared links, resolved), so the reader
// can walk the library horizontally rather than only by topic.
export function relatedLibraryArticles(article) {
  if (!article) return [];
  return (article.related || []).map((id) => libraryArticle(id)).filter(Boolean);
}

// The library's shape, for the station summary.
export function libraryStats() {
  const byTopic = {};
  for (const t of LIBRARY_TOPICS) byTopic[t.id] = libraryArticles({ topic: t.id }).length;
  return {
    articles: LIBRARY_ARTICLES.length,
    topics: LIBRARY_TOPICS.length,
    byTopic,
    assetTypeLinks: LIBRARY_ARTICLES.reduce((n, a) => n + a.assetTypeIds.length, 0),
    docTypeLinks: LIBRARY_ARTICLES.reduce((n, a) => n + a.docTypes.length, 0),
  };
}

// Which shipped asset templates the library actually has content for. The UI
// uses this to decide whether to offer "how to run this" on a template.
export function libraryAssetTypeIds() {
  const out = new Set();
  for (const a of LIBRARY_ARTICLES) for (const id of a.assetTypeIds) out.add(id);
  return [...out];
}

// The document type an article should become by default: its first declared
// docType that is a real document type, else a plain reference.
const REAL_DOC_TYPES = new Set(DOCUMENT_TYPES.map((d) => d.id));
export function articleDocumentType(article) {
  const list = (article && article.docTypes) || [];
  return list.find((d) => REAL_DOC_TYPES.has(d)) || "reference";
}

// Adapt an article into the input shape `docs.addDocument` accepts — this is the
// "usable as written or adapted" half of task 35. The body is the article's own
// markdown, so the created document can be edited freely without touching the
// library.
export function articleToDocumentInput(article, overrides = {}) {
  if (!article) return null;
  return {
    name: overrides.name || article.title,
    docType: overrides.docType || articleDocumentType(article),
    summary: overrides.summary || article.summary,
    body: overrides.body != null ? overrides.body : article.body,
    tags: overrides.tags || article.tags || [],
    informationModel: "document",
    provenance: "authored",
  };
}

// The header block an article is inserted into an existing document with, so an
// adapted article keeps a trail back to the library it came from.
export function articleInsertionText(article) {
  if (!article) return "";
  return [
    `## From the library: ${article.title}`,
    "",
    `> Adapted from the IT-U service library article “${article.title}” (${libraryTopicLabel(article.topic)}). Edit it freely for this client's context.`,
    "",
    article.body,
  ].join("\n");
}

export { art };
